/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiProblem
} from '../../models';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Asaas payment webhook receiver
 */
export const handleAsaasWebhook = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/webhooks/asaas`, method: 'POST', signal
    },
      options);
    }
  


export const getHandleAsaasWebhookMutationOptions = <TError = void | ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleAsaasWebhook>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof handleAsaasWebhook>>, TError,void, TContext> => {

const mutationKey = ['handleAsaasWebhook'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handleAsaasWebhook>>, void> = () => {
          

          return  handleAsaasWebhook(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type HandleAsaasWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof handleAsaasWebhook>>>
    
    export type HandleAsaasWebhookMutationError = void | ApiProblem

    /**
 * @summary Asaas payment webhook receiver
 */
export const useHandleAsaasWebhook = <TError = void | ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleAsaasWebhook>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handleAsaasWebhook>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getHandleAsaasWebhookMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    