/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AiAgentProfile,
  ApiProblem,
  ProfessionalId
} from '../../models';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the versioned catalog of active clinical AI agent profiles. O agente ativo de uma sessão é selecionado automaticamente pelo backend com base na especialidade do profissional — não há seleção manual pelo usuário.
 * @summary Lists all active AI agent profiles
 */
export const listAgents = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<AiAgentProfile[]>(
      {url: `/api/v1/agents`, method: 'GET', signal
    },
      options);
    }
  



export const getListAgentsQueryKey = () => {
    return [
    `/api/v1/agents`
    ] as const;
    }

    
export const getListAgentsQueryOptions = <TData = Awaited<ReturnType<typeof listAgents>>, TError = ApiProblem>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAgentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAgents>>> = ({ signal }) => listAgents(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAgentsQueryResult = NonNullable<Awaited<ReturnType<typeof listAgents>>>
export type ListAgentsQueryError = ApiProblem


export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ApiProblem>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAgents>>,
          TError,
          Awaited<ReturnType<typeof listAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAgents>>,
          TError,
          Awaited<ReturnType<typeof listAgents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists all active AI agent profiles
 */

export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAgentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Pré-visualiza o agente que seria selecionado automaticamente para o profissional informado. Use este endpoint para exibir "Agente ativo: {agentName}" antes de iniciar o chat.
 * @summary Resolves the AI agent that would be used for a given professional
 */
export const resolveAgentForProfessional = (
    professionalId: ProfessionalId,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<AiAgentProfile>(
      {url: `/api/v1/agents/resolve/${professionalId}`, method: 'GET', signal
    },
      options);
    }
  



export const getResolveAgentForProfessionalQueryKey = (professionalId?: ProfessionalId,) => {
    return [
    `/api/v1/agents/resolve/${professionalId}`
    ] as const;
    }

    
export const getResolveAgentForProfessionalQueryOptions = <TData = Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError = ApiProblem>(professionalId: ProfessionalId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResolveAgentForProfessionalQueryKey(professionalId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveAgentForProfessional>>> = ({ signal }) => resolveAgentForProfessional(professionalId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(professionalId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResolveAgentForProfessionalQueryResult = NonNullable<Awaited<ReturnType<typeof resolveAgentForProfessional>>>
export type ResolveAgentForProfessionalQueryError = ApiProblem


export function useResolveAgentForProfessional<TData = Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError = ApiProblem>(
 professionalId: ProfessionalId, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveAgentForProfessional>>,
          TError,
          Awaited<ReturnType<typeof resolveAgentForProfessional>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveAgentForProfessional<TData = Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError = ApiProblem>(
 professionalId: ProfessionalId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveAgentForProfessional>>,
          TError,
          Awaited<ReturnType<typeof resolveAgentForProfessional>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveAgentForProfessional<TData = Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError = ApiProblem>(
 professionalId: ProfessionalId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolves the AI agent that would be used for a given professional
 */

export function useResolveAgentForProfessional<TData = Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError = ApiProblem>(
 professionalId: ProfessionalId, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveAgentForProfessional>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResolveAgentForProfessionalQueryOptions(professionalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Retorna as regras de correspondência entre especialidade profissional e agente clínico. Útil para diagnóstico e documentação da lógica de resolução automática.
 * @summary Lists the active agent mapping rules (for diagnostics)
 */
export const listMappingRules = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/agents/mapping-rules`, method: 'GET', signal
    },
      options);
    }
  



export const getListMappingRulesQueryKey = () => {
    return [
    `/api/v1/agents/mapping-rules`
    ] as const;
    }

    
export const getListMappingRulesQueryOptions = <TData = Awaited<ReturnType<typeof listMappingRules>>, TError = ApiProblem>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMappingRules>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMappingRulesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMappingRules>>> = ({ signal }) => listMappingRules(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMappingRules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMappingRulesQueryResult = NonNullable<Awaited<ReturnType<typeof listMappingRules>>>
export type ListMappingRulesQueryError = ApiProblem


export function useListMappingRules<TData = Awaited<ReturnType<typeof listMappingRules>>, TError = ApiProblem>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMappingRules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMappingRules>>,
          TError,
          Awaited<ReturnType<typeof listMappingRules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMappingRules<TData = Awaited<ReturnType<typeof listMappingRules>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMappingRules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMappingRules>>,
          TError,
          Awaited<ReturnType<typeof listMappingRules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMappingRules<TData = Awaited<ReturnType<typeof listMappingRules>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMappingRules>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists the active agent mapping rules (for diagnostics)
 */

export function useListMappingRules<TData = Awaited<ReturnType<typeof listMappingRules>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMappingRules>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMappingRulesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




