/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  Clinic,
  CreateClinicDto,
  CreateInsurancePlanDto,
  InsurancePlan,
  UpdateClinicDto
} from '../../models';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Creates a new clinic
 */
export const createClinic = (
    createClinicDto: CreateClinicDto,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<Clinic>(
      {url: `/api/v1/clinics`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClinicDto, signal
    },
      options);
    }
  


export const getCreateClinicMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClinic>>, TError,{data: CreateClinicDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createClinic>>, TError,{data: CreateClinicDto}, TContext> => {

const mutationKey = ['createClinic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createClinic>>, {data: CreateClinicDto}> = (props) => {
          const {data} = props ?? {};

          return  createClinic(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateClinicMutationResult = NonNullable<Awaited<ReturnType<typeof createClinic>>>
    export type CreateClinicMutationBody = CreateClinicDto
    export type CreateClinicMutationError = ApiProblem

    /**
 * @summary Creates a new clinic
 */
export const useCreateClinic = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createClinic>>, TError,{data: CreateClinicDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createClinic>>,
        TError,
        {data: CreateClinicDto},
        TContext
      > => {

      const mutationOptions = getCreateClinicMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get clinic by id
 */
export const getClinic = (
    clinicId: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<Clinic>(
      {url: `/api/v1/clinics/${clinicId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetClinicQueryKey = (clinicId?: string,) => {
    return [
    `/api/v1/clinics/${clinicId}`
    ] as const;
    }

    
export const getGetClinicQueryOptions = <TData = Awaited<ReturnType<typeof getClinic>>, TError = ApiProblem>(clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClinicQueryKey(clinicId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClinic>>> = ({ signal }) => getClinic(clinicId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(clinicId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClinicQueryResult = NonNullable<Awaited<ReturnType<typeof getClinic>>>
export type GetClinicQueryError = ApiProblem


export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ApiProblem>(
 clinicId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClinic>>,
          TError,
          Awaited<ReturnType<typeof getClinic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ApiProblem>(
 clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClinic>>,
          TError,
          Awaited<ReturnType<typeof getClinic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ApiProblem>(
 clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get clinic by id
 */

export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ApiProblem>(
 clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClinicQueryOptions(clinicId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a clinic
 */
export const updateClinic = (
    clinicId: string,
    updateClinicDto: UpdateClinicDto,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<Clinic>(
      {url: `/api/v1/clinics/${clinicId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateClinicDto
    },
      options);
    }
  


export const getUpdateClinicMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClinic>>, TError,{clinicId: string;data: UpdateClinicDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateClinic>>, TError,{clinicId: string;data: UpdateClinicDto}, TContext> => {

const mutationKey = ['updateClinic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateClinic>>, {clinicId: string;data: UpdateClinicDto}> = (props) => {
          const {clinicId,data} = props ?? {};

          return  updateClinic(clinicId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateClinicMutationResult = NonNullable<Awaited<ReturnType<typeof updateClinic>>>
    export type UpdateClinicMutationBody = UpdateClinicDto
    export type UpdateClinicMutationError = ApiProblem

    /**
 * @summary Update a clinic
 */
export const useUpdateClinic = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateClinic>>, TError,{clinicId: string;data: UpdateClinicDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateClinic>>,
        TError,
        {clinicId: string;data: UpdateClinicDto},
        TContext
      > => {

      const mutationOptions = getUpdateClinicMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List insurance plans for a clinic
 */
export const listInsurancePlans = (
    clinicId: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<InsurancePlan[]>(
      {url: `/api/v1/clinics/${clinicId}/insurance-plans`, method: 'GET', signal
    },
      options);
    }
  



export const getListInsurancePlansQueryKey = (clinicId?: string,) => {
    return [
    `/api/v1/clinics/${clinicId}/insurance-plans`
    ] as const;
    }

    
export const getListInsurancePlansQueryOptions = <TData = Awaited<ReturnType<typeof listInsurancePlans>>, TError = ApiProblem>(clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInsurancePlansQueryKey(clinicId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInsurancePlans>>> = ({ signal }) => listInsurancePlans(clinicId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(clinicId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListInsurancePlansQueryResult = NonNullable<Awaited<ReturnType<typeof listInsurancePlans>>>
export type ListInsurancePlansQueryError = ApiProblem


export function useListInsurancePlans<TData = Awaited<ReturnType<typeof listInsurancePlans>>, TError = ApiProblem>(
 clinicId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInsurancePlans>>,
          TError,
          Awaited<ReturnType<typeof listInsurancePlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInsurancePlans<TData = Awaited<ReturnType<typeof listInsurancePlans>>, TError = ApiProblem>(
 clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInsurancePlans>>,
          TError,
          Awaited<ReturnType<typeof listInsurancePlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListInsurancePlans<TData = Awaited<ReturnType<typeof listInsurancePlans>>, TError = ApiProblem>(
 clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List insurance plans for a clinic
 */

export function useListInsurancePlans<TData = Awaited<ReturnType<typeof listInsurancePlans>>, TError = ApiProblem>(
 clinicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListInsurancePlansQueryOptions(clinicId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create an insurance plan for a clinic
 */
export const createInsurancePlan = (
    clinicId: string,
    createInsurancePlanDto: CreateInsurancePlanDto,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<InsurancePlan>(
      {url: `/api/v1/clinics/${clinicId}/insurance-plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInsurancePlanDto, signal
    },
      options);
    }
  


export const getCreateInsurancePlanMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInsurancePlan>>, TError,{clinicId: string;data: CreateInsurancePlanDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createInsurancePlan>>, TError,{clinicId: string;data: CreateInsurancePlanDto}, TContext> => {

const mutationKey = ['createInsurancePlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInsurancePlan>>, {clinicId: string;data: CreateInsurancePlanDto}> = (props) => {
          const {clinicId,data} = props ?? {};

          return  createInsurancePlan(clinicId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateInsurancePlanMutationResult = NonNullable<Awaited<ReturnType<typeof createInsurancePlan>>>
    export type CreateInsurancePlanMutationBody = CreateInsurancePlanDto
    export type CreateInsurancePlanMutationError = ApiProblem

    /**
 * @summary Create an insurance plan for a clinic
 */
export const useCreateInsurancePlan = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInsurancePlan>>, TError,{clinicId: string;data: CreateInsurancePlanDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createInsurancePlan>>,
        TError,
        {clinicId: string;data: CreateInsurancePlanDto},
        TContext
      > => {

      const mutationOptions = getCreateInsurancePlanMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    