import {primary, secondary} from './palette';
import type {ColorMode} from '.';

const {transparent, white, gray, brand, danger, success, warning, accent, info} = primary;
const {
    grayBlue,
    indigo,
    purple,
    pink,
    orange,
    blueLight,
    blue,
    copper,
    fuchsia,
    grayIron,
    green,
    orangeDark,
    teal,
    violet,
    yellow,
} = secondary;

export const darkMode: ColorMode = {
    ui: {
        body: {
            text: gray.dark['300'],
            background: brand['950'],
        },
        style: {
            shadow: {
                color: accent.base,
                ring: {
                    offsetted: white,
                    emphasized: accent.muted,
                    dangerous: `${danger['400']}3D`,
                    neutral: `${gray.dark['400']}24`,
                },
            },
        },
        component: {
            icons: {
                EmptyIcon: {
                    svg1: brand['700'],
                    svg2: brand['700'],
                    svg3: '#232F5A',
                    svg4: brand['25'],
                    svg5: brand['100'],
                    svg6: brand['25'],
                    svg7: brand['100'],
                    svg8: brand['850'],
                    svg9: brand['850'],
                },
            },
            alert: {
                background: brand['900'],
                border: gray.dark['700'],
                title: gray.dark['300'],
                description: gray.dark['400'],
                primaryAction: gray.dark['600'],
                secondaryAction: brand['700'],
                actionBackground: transparent,
            },
            alertDialog: {
                background: brand['900'],
                border: gray.dark['700'],
                title: gray.dark['50'],
                description: grayIron['50'],
                overlay: brand['950'],
            },
            accordion: {
                border: accent.muted,
                emphasized: transparent,
                neutral: brand['900'],
            },
            avatar: {
                backgroundColor: gray.dark['800'],
                color: gray.dark['500'],
            },
            avatarInfo: {
                background: transparent,
                name: gray.dark['25'],
                description: gray.dark['400'],
            },
            avatarUploader: {
                border: brand['500'],
                background: gray.dark['800'],
            },
            badge: {
                badgeClose: {
                    informative: {
                        icon: gray.dark['400'],
                        background: transparent,
                        iconHover: gray.dark['500'],
                        backgroundHover: gray.dark['100'],
                    },
                    emphasized: {
                        icon: brand['400'],
                        background: transparent,
                        iconHover: brand['500'],
                        backgroundHover: brand['100'],
                    },
                    dangerous: {
                        icon: danger['400'],
                        background: transparent,
                        iconHover: danger['500'],
                        backgroundHover: danger['100'],
                    },
                    cautious: {
                        icon: warning['400'],
                        background: transparent,
                        iconHover: warning['500'],
                        backgroundHover: warning['100'],
                    },
                    positive: {
                        icon: success['400'],
                        background: transparent,
                        iconHover: success['500'],
                        backgroundHover: success['100'],
                    },
                    grayBlue: {
                        icon: grayBlue['400'],
                        background: transparent,
                        iconHover: grayBlue['500'],
                        backgroundHover: grayBlue['100'],
                    },
                    blueLight: {
                        icon: blueLight['400'],
                        background: transparent,
                        iconHover: blueLight['500'],
                        backgroundHover: blueLight['100'],
                    },
                    blue: {
                        icon: blue['400'],
                        background: transparent,
                        iconHover: blue['500'],
                        backgroundHover: blue['100'],
                    },
                    indigo: {
                        icon: indigo['400'],
                        background: transparent,
                        iconHover: indigo['500'],
                        backgroundHover: indigo['100'],
                    },
                    purple: {
                        icon: purple['400'],
                        background: transparent,
                        iconHover: purple['500'],
                        backgroundHover: purple['100'],
                    },
                    pink: {
                        icon: pink['400'],
                        background: transparent,
                        iconHover: pink['500'],
                        backgroundHover: pink['100'],
                    },
                    orange: {
                        icon: orange['400'],
                        background: transparent,
                        iconHover: orange['500'],
                        backgroundHover: orange['100'],
                    },
                    green: {
                        icon: green['400'],
                        background: transparent,
                        iconHover: green['500'],
                        backgroundHover: success['100'],
                    },
                    teal: {
                        icon: teal['400'],
                        background: transparent,
                        iconHover: teal['500'],
                        backgroundHover: success['100'],
                    },
                    violet: {
                        icon: violet['400'],
                        background: transparent,
                        iconHover: violet['500'],
                        backgroundHover: violet['100'],
                    },
                    fuchsia: {
                        icon: fuchsia['400'],
                        background: transparent,
                        iconHover: fuchsia['500'],
                        backgroundHover: fuchsia['100'],
                    },
                    orangeDark: {
                        icon: orangeDark['400'],
                        background: transparent,
                        iconHover: orangeDark['500'],
                        backgroundHover: orangeDark['100'],
                    },
                    yellow: {
                        icon: yellow['400'],
                        background: transparent,
                        iconHover: yellow['500'],
                        backgroundHover: yellow['100'],
                    },
                    copper: {
                        icon: copper['400'],
                        background: transparent,
                        backgroundHover: copper['100'],
                    },
                    grayIron: {
                        icon: grayIron['400'],
                        background: transparent,
                        backgroundHover: grayIron['100'],
                    },
                },
                filled: {
                    informative: {
                        label: gray.dark['500'],
                        icon: gray.dark['700'],
                        background: gray.dark['900'],
                        border: gray.dark['950'],
                    },
                    emphasized: {
                        label: brand['500'],
                        icon: brand['700'],
                        background: brand['850'],
                        border: brand['850'],
                    },
                    dangerous: {
                        label: danger['500'],
                        icon: danger['700'],
                        background: danger['950'],
                        border: danger['950'],
                    },
                    cautious: {
                        label: warning['500'],
                        icon: warning['700'],
                        background: warning['950'],
                        border: warning['950'],
                    },
                    positive: {
                        label: success['500'],
                        icon: success['700'],
                        background: success['950'],
                        border: success['950'],
                    },
                    grayBlue: {
                        label: grayBlue['500'],
                        icon: grayBlue['700'],
                        background: grayBlue['900'],
                        border: grayBlue['900'],
                    },
                    blueLight: {
                        label: blueLight['500'],
                        icon: blueLight['700'],
                        background: blueLight['950'],
                        border: blueLight['950'],
                    },
                    blue: {
                        label: blue['200'],
                        icon: blue['700'],
                        background: blue['900'],
                        border: blue['950'],
                    },
                    indigo: {
                        label: indigo['500'],
                        icon: indigo['700'],
                        background: indigo['950'],
                        border: indigo['950'],
                    },
                    purple: {
                        label: purple['500'],
                        icon: purple['700'],
                        background: purple['950'],
                        border: purple['950'],
                    },
                    pink: {
                        label: pink['500'],
                        icon: pink['700'],
                        background: pink['950'],
                        border: pink['950'],
                    },
                    orange: {
                        label: orange['500'],
                        icon: orange['700'],
                        background: orange['950'],
                        border: orange['950'],
                    },
                    green: {
                        label: green['500'],
                        icon: green['700'],
                        background: green['950'],
                        border: green['950'],
                    },
                    teal: {
                        label: teal['500'],
                        icon: teal['700'],
                        background: teal['950'],
                        border: teal['950'],
                    },
                    violet: {
                        label: violet['500'],
                        icon: violet['700'],
                        background: violet['950'],
                        border: violet['950'],
                    },
                    fuchsia: {
                        label: fuchsia['500'],
                        icon: fuchsia['700'],
                        background: fuchsia['950'],
                        border: fuchsia['950'],
                    },
                    orangeDark: {
                        label: orangeDark['200'],
                        icon: orangeDark['700'],
                        background: orangeDark['950'],
                        border: orangeDark['950'],
                    },
                    yellow: {
                        label: yellow['500'],
                        icon: yellow['700'],
                        background: yellow['950'],
                        border: yellow['950'],
                    },
                    copper: {
                        label: copper['300'],
                        icon: copper['700'],
                        background: copper['950'],
                        border: copper['950'],
                    },
                    grayIron: {
                        label: grayIron['500'],
                        icon: grayIron['700'],
                        background: grayIron['950'],
                        border: grayIron['950'],
                    },
                },
                outlined: {
                    informative: {
                        label: gray.dark['700'],
                        icon: gray.dark['600'],
                        background: transparent,
                        border: gray.dark['600'],
                    },
                    emphasized: {
                        label: brand['700'],
                        icon: brand['600'],
                        background: transparent,
                        border: brand['600'],
                    },
                    dangerous: {
                        label: danger['700'],
                        icon: danger['600'],
                        background: transparent,
                        border: danger['600'],
                    },
                    cautious: {
                        label: warning['700'],
                        icon: warning['600'],
                        background: transparent,
                        border: warning['600'],
                    },
                    positive: {
                        label: success['700'],
                        icon: success['600'],
                        background: transparent,
                        border: success['600'],
                    },
                    grayBlue: {
                        label: grayBlue['700'],
                        icon: grayBlue['600'],
                        background: transparent,
                        border: grayBlue['600'],
                    },
                    blueLight: {
                        label: blueLight['700'],
                        icon: blueLight['600'],
                        background: transparent,
                        border: blueLight['600'],
                    },
                    blue: {
                        label: blue['700'],
                        icon: blue['600'],
                        background: transparent,
                        border: blue['600'],
                    },
                    indigo: {
                        label: indigo['700'],
                        icon: indigo['600'],
                        background: transparent,
                        border: indigo['600'],
                    },
                    purple: {
                        label: purple['700'],
                        icon: purple['600'],
                        background: transparent,
                        border: purple['600'],
                    },
                    pink: {
                        label: pink['700'],
                        icon: pink['600'],
                        background: transparent,
                        border: pink['600'],
                    },
                    orange: {
                        label: orange['700'],
                        icon: orange['600'],
                        background: transparent,
                        border: orange['600'],
                    },
                    green: {
                        label: green['700'],
                        icon: green['600'],
                        background: transparent,
                        border: green['600'],
                    },
                    teal: {
                        label: teal['700'],
                        icon: teal['600'],
                        background: transparent,
                        border: teal['600'],
                    },
                    violet: {
                        label: violet['700'],
                        icon: violet['600'],
                        background: transparent,
                        border: violet['600'],
                    },
                    fuchsia: {
                        label: fuchsia['700'],
                        icon: fuchsia['600'],
                        background: transparent,
                        border: fuchsia['600'],
                    },
                    orangeDark: {
                        label: orangeDark['700'],
                        icon: orangeDark['600'],
                        background: transparent,
                        border: orangeDark['600'],
                    },
                    yellow: {
                        label: yellow['700'],
                        icon: yellow['600'],
                        background: transparent,
                        border: yellow['600'],
                    },
                    copper: {
                        label: copper['700'],
                        icon: copper['600'],
                        background: transparent,
                        border: copper['600'],
                    },
                    grayIron: {
                        label: grayIron['700'],
                        icon: grayIron['600'],
                        background: transparent,
                        border: grayIron['600'],
                    },
                },
                neutral: {
                    label: gray.dark['700'],
                    background: gray.dark['700'],
                    border: gray.dark['200'],
                    informative: {
                        icon: gray.dark['600'],
                    },
                    emphasized: {
                        icon: brand['600'],
                    },
                    dangerous: {
                        icon: danger['600'],
                    },
                    cautious: {
                        icon: warning['600'],
                    },
                    positive: {
                        icon: success['600'],
                    },
                    grayBlue: {
                        icon: grayBlue['600'],
                    },
                    blueLight: {
                        icon: blueLight['600'],
                    },
                    blue: {
                        icon: blue['600'],
                    },
                    indigo: {
                        icon: indigo['600'],
                    },
                    purple: {
                        icon: purple['600'],
                    },
                    pink: {
                        icon: pink['600'],
                    },
                    orange: {
                        icon: orange['600'],
                    },
                    green: {
                        icon: green['600'],
                    },
                    teal: {
                        icon: teal['600'],
                    },
                    violet: {
                        icon: violet['600'],
                    },
                    fuchsia: {
                        icon: fuchsia['600'],
                    },
                    orangeDark: {
                        icon: orangeDark['600'],
                    },
                    yellow: {
                        icon: yellow['600'],
                    },
                    copper: {
                        icon: copper['600'],
                    },
                    grayIron: {
                        icon: grayIron['600'],
                    },
                },
                pill: {
                    informative: {
                        icon: white,
                        label: white,
                        background: info['600'],
                        border: transparent,
                    },
                    dangerous: {
                        icon: white,
                        label: white,
                        background: danger['500'],
                        border: transparent,
                    },
                    cautious: {
                        icon: white,
                        label: white,
                        background: warning['500'],
                        border: transparent,
                    },
                    emphasized: {
                        icon: white,
                        label: white,
                        background: brand['500'],
                        border: transparent,
                    },
                    positive: {
                        icon: white,
                        label: white,
                        background: success['500'],
                        border: transparent,
                    },
                    green: {
                        icon: green['950'],
                        label: green['950'],
                        background: green['500'],
                        border: transparent,
                    },
                    teal: {
                        icon: teal['950'],
                        label: teal['950'],
                        background: teal['500'],
                        border: transparent,
                    },
                    violet: {
                        icon: white,
                        label: white,
                        background: violet['500'],
                        border: transparent,
                    },
                    fuchsia: {
                        icon: fuchsia['950'],
                        label: fuchsia['950'],
                        background: fuchsia['500'],
                        border: transparent,
                    },
                    orangeDark: {
                        icon: white,
                        label: white,
                        background: orangeDark['500'],
                        border: transparent,
                    },
                    orange: {
                        icon: white,
                        label: white,
                        background: orange['500'],
                        border: transparent,
                    },
                    yellow: {
                        icon: yellow['950'],
                        label: yellow['950'],
                        background: yellow['500'],
                        border: transparent,
                    },
                    copper: {
                        icon: white,
                        label: white,
                        background: copper['500'],
                        border: transparent,
                    },
                    grayIron: {
                        icon: white,
                        label: white,
                        background: grayIron['500'],
                        border: transparent,
                    },
                    blue: {
                        icon: white,
                        label: white,
                        background: blue['500'],
                        border: transparent,
                    },
                    grayBlue: {
                        icon: white,
                        label: white,
                        background: grayBlue['500'],
                        border: transparent,
                    },
                    blueLight: {
                        icon: white,
                        label: white,
                        background: blueLight['500'],
                        border: transparent,
                    },
                    indigo: {
                        icon: white,
                        label: white,
                        background: indigo['500'],
                        border: transparent,
                    },
                    purple: {
                        icon: white,
                        label: white,
                        background: purple['500'],
                        border: transparent,
                    },
                    pink: {
                        icon: white,
                        label: white,
                        background: pink['500'],
                        border: transparent,
                    },
                },
            },
            button: {
                primary: {
                    emphasized: {
                        background: accent['gradient-light'],
                        backgroundActive: accent['gradient-dark'],
                        backgroundDisabled: brand['800'],
                        backgroundHover: accent['gradient-dark'],
                        backgroundLoading: accent['gradient-light'],
                        text: gray.dark['25'],
                        textDisabled: brand['700'],
                    },
                    neutral: {
                        background: gray.dark['700'],
                        backgroundActive: gray.dark['700'],
                        backgroundDisabled: gray.dark['600'],
                        backgroundHover: gray.dark['800'],
                        backgroundLoading: gray.dark['400'],
                        text: gray.dark['50'],
                        textDisabled: gray.dark['500'],
                    },
                    dangerous: {
                        background: danger['700'],
                        backgroundActive: danger['600'],
                        backgroundDisabled: danger['900'],
                        backgroundHover: danger['800'],
                        backgroundLoading: danger['300'],
                        text: gray.dark['50'],
                        textDisabled: gray.dark['500'],
                    },
                    positive: {
                        background: green['700'],
                        backgroundActive: green['600'],
                        backgroundDisabled: green['900'],
                        backgroundHover: green['800'],
                        backgroundLoading: green['300'],
                        text: gray.dark['50'],
                        textDisabled: gray.dark['500'],
                    },
                    cautious: {
                        background: warning['700'],
                        backgroundActive: warning['600'],
                        backgroundDisabled: warning['900'],
                        backgroundHover: warning['800'],
                        backgroundLoading: orange['300'],
                        text: gray.dark['50'],
                        textDisabled: gray.dark['500'],
                    },
                },
                secondary: {
                    emphasized: {
                        background: transparent,
                        backgroundActive: brand['900'],
                        backgroundHover: brand['900'],
                        backgroundLoading: transparent,
                        backgroundDisabled: transparent,
                        border: accent.muted,
                        borderDisabled: brand['850'],
                        borderLoading: accent.muted,
                        icon: gray.dark['25'],
                        text: gray.dark['25'],
                        textActive: accent.soft,
                        textDisabled: brand['850'],
                        textHover: accent.soft,
                        textLoading: gray.dark['25'],
                    },
                    neutral: {
                        background: transparent,
                        backgroundActive: gray.dark['800'],
                        backgroundHover: gray.dark['900'],
                        border: gray.dark['500'],
                        borderDisabled: gray.dark['700'],
                        borderLoading: gray.dark['400'],
                        icon: gray.dark['300'],
                        text: gray.dark['300'],
                        backgroundLoading: transparent,
                        backgroundDisabled: gray.dark['800'],
                        textActive: gray.dark['300'],
                        textDisabled: gray.dark['700'],
                        textHover: gray.dark['400'],
                        textLoading: gray.dark['500'],
                    },
                    dangerous: {
                        background: 'transparent',
                        backgroundActive: danger['800'],
                        backgroundHover: danger['900'],
                        border: danger['700'],
                        backgroundLoading: transparent,
                        backgroundDisabled: danger['800'],
                        borderDisabled: danger['900'],
                        borderLoading: danger['400'],
                        icon: danger['300'],
                        text: danger['300'],
                        textActive: danger['300'],
                        textDisabled: danger['700'],
                        textHover: danger['400'],
                        textLoading: danger['500'],
                    },
                    positive: {
                        background: 'transparent',
                        backgroundActive: green['800'],
                        backgroundHover: green['900'],
                        border: green['700'],
                        backgroundLoading: transparent,
                        backgroundDisabled: green['800'],
                        borderDisabled: green['900'],
                        borderLoading: green['400'],
                        icon: green['300'],
                        text: green['300'],
                        textActive: green['300'],
                        textDisabled: green['700'],
                        textHover: green['400'],
                        textLoading: green['500'],
                    },
                    cautious: {
                        background: 'transparent',
                        backgroundActive: secondary.yellow['800'],
                        backgroundHover: secondary.yellow['950'],
                        border: warning['700'],
                        backgroundLoading: transparent,
                        backgroundDisabled: warning['800'],
                        borderDisabled: warning['900'],
                        borderLoading: warning['400'],
                        icon: warning['400'],
                        text: warning['400'],
                        textActive: warning['400'],
                        textDisabled: warning['700'],
                        textHover: warning['500'],
                        textLoading: warning['500'],
                    },
                },
                tertiary: {
                    emphasized: {
                        background: 'transparent',
                        backgroundActive: brand['800'],
                        backgroundHover: brand['900'],
                        icon: brand['300'],
                        text: brand['300'],
                        textActive: brand['300'],
                        textDisabled: brand['900'],
                        textHover: brand['400'],
                        textLoading: brand['500'],
                    },
                    neutral: {
                        background: 'transparent',
                        backgroundActive: gray.dark['800'],
                        backgroundHover: brand['850'],
                        icon: gray.dark['300'],
                        text: gray.dark['300'],
                        textActive: gray.dark['300'],
                        textDisabled: gray.dark['700'],
                        textHover: gray.dark['400'],
                        textLoading: gray.dark['500'],
                    },
                    dangerous: {
                        background: 'transparent',
                        backgroundActive: danger['800'],
                        backgroundHover: danger['900'],
                        icon: danger['300'],
                        text: danger['300'],
                        textActive: danger['300'],
                        textDisabled: danger['900'],
                        textHover: danger['400'],
                        textLoading: danger['500'],
                    },
                    positive: {
                        background: 'transparent',
                        backgroundActive: green['800'],
                        backgroundHover: green['900'],
                        icon: green['300'],
                        text: green['300'],
                        textActive: green['300'],
                        textDisabled: green['900'],
                        textHover: green['400'],
                        textLoading: green['500'],
                    },
                    cautious: {
                        background: 'transparent',
                        backgroundActive: warning['800'],
                        backgroundHover: warning['900'],
                        icon: warning['300'],
                        text: warning['300'],
                        textActive: warning['300'],
                        textDisabled: warning['900'],
                        textHover: warning['400'],
                        textLoading: warning['500'],
                    },
                },
                link: {
                    emphasized: {
                        background: transparent,
                        icon: accent.base,
                        text: accent.base,
                        textActive: accent.soft,
                        textDisabled: brand['850'],
                        textHover: accent.soft,
                        textLoading: gray.dark['25'],
                    },
                    neutral: {
                        background: transparent,
                        icon: gray.dark['400'],
                        text: gray.dark['300'],
                        textActive: gray.dark['700'],
                        textDisabled: gray.dark['700'],
                        textHover: gray.dark['400'],
                        textLoading: gray.dark['500'],
                    },
                    dangerous: {
                        background: 'transparent',
                        icon: danger['300'],
                        text: danger['300'],
                        textActive: danger['700'],
                        textDisabled: danger['900'],
                        textHover: danger['400'],
                        textLoading: danger['500'],
                    },
                    positive: {
                        background: 'transparent',
                        icon: green['300'],
                        text: green['300'],
                        textActive: green['700'],
                        textDisabled: green['900'],
                        textHover: green['400'],
                        textLoading: green['500'],
                    },
                    cautious: {
                        background: 'transparent',
                        icon: warning['300'],
                        text: warning['300'],
                        textActive: warning['700'],
                        textDisabled: warning['900'],
                        textHover: warning['400'],
                        textLoading: warning['500'],
                    },
                },
            },
            breadcrumb: {
                separator: gray.dark[200],
                lastPage: accent.base,
                lastPageHover: accent.base,
                text: accent.soft,
                textHover: accent.base,
            },
            carousel: {
                background: primary.brand[900],
                button: accent.soft,
            },
            card: {
                default: {
                    border: accent.muted,
                    background: brand['950'],
                },
                soft: {
                    border: brand['800'],
                    background: brand['850'],
                },
            },
            checkbox: {
                background: transparent,
                backgroundChecked: transparent,
                backgroundDisabled: brand['850'],
                backgroundDisabledChecked: brand['850'],
                backgroundInvalidChecked: danger['600'],
                backgroundInvalidDisabled: danger['300'],
                border: gray.dark['600'],
                borderChecked: accent.soft,
                borderDisabled: accent.soft,
                borderDisabledChecked: accent.soft,
                borderInvalid: danger['400'],
                borderInvalidChecked: danger['600'],
                borderInvalidDisabled: danger['300'],
                borderInvalidDisabledChecked: danger['300'],
                tick: accent.soft,
                tickDisable: accent.soft,
                tickInvalid: white,
                tickInvalidDisabledChecked: white,
                label: gray.dark['700'],
                labelDisabled: gray.dark['400'],
                labelInvalid: danger['600'],
                labelInvalidDisabled: danger['400'],
                description: gray.dark['600'],
                descriptionDisabled: gray.dark['300'],
            },
            checkboxGroup: {
                title: gray.dark['25'],
                subtitle: gray.dark['400'],
                hint: gray.dark['500'],
                hintInvalid: danger['400'],
            },
            circularProgress: {
                label: gray.dark['400'],
                value: gray.dark['100'],
                track: gray.dark['800'],
                indicator: {
                    primary: brand['400'],
                    neutral: gray.dark['400'],
                },
            },
            closeButton: {
                icon: gray.dark['600'],
                iconHover: gray.dark['500'],
                iconBackground: transparent,
                iconBackgroundHover: gray.dark['900'],
            },
            colorPicker: {
                background: brand['900'],
                border: brand['850'],
                inputBorder: gray.dark['500'],
                colorSelectBorder: brand['800'],
                colorSelectBorderActive: brand['700'],
                colorSelectInnerBorder: brand['900'],
                color: gray.dark['25'],
                trigger: {
                    background: transparent,
                    border: gray.dark['500'],
                },
            },
            combobox: {
                menuBackground: brand['900'],
                menuBorder: brand['850'],
                noResults: gray.dark['600'],
                trigger: {
                    background: transparent,
                    backgroundDisabled: brand['800'],
                    border: brand['850'],
                    borderDisabled: brand['700'],
                    borderInvalid: danger['500'],
                    borderFocus: brand['700'],
                    borderSelected: gray.dark['500'],
                    placeholder: brand['700'],
                    placeholderDisabled: brand['700'],
                    text: gray.dark['25'],
                    textDisabled: brand['700'],
                    icon: gray.dark['25'],
                    iconDisabled: brand['700'],
                },
                item: {
                    text: gray.dark['200'],
                    background: transparent,
                    backgroundHover: brand['850'],
                    disabled: gray.dark['600'],
                    icon: brand['400'],
                    iconDisabled: gray.dark['600'],
                },
            },
            datePicker: {
                background: brand['900'],
                label: gray.dark['25'],
                labelHover: gray.dark['100'],
                backgroundHover: brand['850'],
                selectBackground: accent.soft,
                selectBackgroundHover: accent.base,
                selectLabel: white,
                selectLabelRange: gray.dark['25'],
                selectRangeBackground: brand['800'],
                dayOutside: gray.dark['500'],
                border: brand['850'],
                labelDisabled: brand['500'],
            },
            drawer: {
                background: brand['900'],
                border: gray.dark['700'],
                title: gray.dark['100'],
                description: gray.dark['400'],
                overlay: brand['950'],
            },
            dropdown: {
                background: brand['900'],
                border: brand['850'],
                separator: gray.dark['800'],
                item: {
                    backgroundDisabled: gray.dark['800'],
                    hover: brand['850'],
                    icon: gray.dark['500'],
                    iconDisabled: gray.dark['700'],
                    label: gray.dark['25'],
                    labelDisabled: gray.dark['600'],
                    shortcut: gray.dark['500'],
                    shortcutDisabled: gray.dark['600'],
                },
            },
            dropzone: {
                background: transparent,
                disabledBackground: gray.dark['900'],
                border: brand['500'],
                dragActiveBorder: brand['600'],
                icon: brand['700'],
            },
            featuredIcon: {
                border: {
                    neutral: gray.dark['200'],
                    emphasized: accent.muted,
                    informative: gray.dark['500'],
                    positive: success['600'],
                    cautious: warning['600'],
                    dangerous: danger['600'],
                },
                background: {
                    neutral: gray.dark['600'],
                    emphasized: accent.muted,
                    informative: gray.dark['600'],
                    positive: success['600'],
                    cautious: warning['600'],
                    dangerous: danger['600'],
                },
                icon: {
                    neutral: gray.dark['25'],
                    emphasized: gray.dark['25'],
                    informative: gray.dark['25'],
                    positive: gray.dark['25'],
                    cautious: gray.dark['25'],
                    dangerous: gray.dark['25'],
                },
            },
            field: {
                hint: gray.dark['25'],
                hintInvalid: danger['500'],
                hintDisabled: brand['700'],
            },
            galleryModal: {
                border: accent.soft,
                cardBackground: transparent,
            },
            label: {
                title: gray.dark['25'],
                titleDisabled: brand['700'],
                description: gray.dark['500'],
                descriptionDisabled: gray.dark['600'],
                optional: gray.dark['600'],
                hint: accent.base,
            },
            link: {
                dangerous: {
                    text: danger['400'],
                    textHover: danger['300'],
                },
                emphasized: {
                    text: accent.base,
                    textHover: accent.soft,
                },
                neutral: {
                    text: gray.dark['400'],
                    textHover: gray.dark['300'],
                },
                textDisabled: brand['850'],
            },
            linearProgress: {
                teal: {
                    background: `${white}26`,
                    indicator: teal['500'],
                },
                informative: {
                    background: `${white}26`,
                    indicator: info['600'],
                },
                orangeDark: {
                    background: `${white}26`,
                    indicator: orangeDark['500'],
                },
                violet: {
                    background: `${white}1A`,
                    indicator: violet['600'],
                },
                fuchsia: {
                    background: `${white}26`,
                    indicator: fuchsia['600'],
                },
                yellow: {
                    background: `${white}26`,
                    indicator: yellow['600'],
                },
            },
            modal: {
                background: brand['900'],
                border: brand['850'],
                title: white,
                description: gray.dark['100'],
                overlay: brand['950'],
            },
            navigationHeader: {
                background: transparent,
                hoverItem: gray.dark['50'],
                currentPage: gray.dark['50'],
            },
            pageHeader: {
                background: transparent,
                title: gray.dark['200'],
                back: {
                    text: gray.dark['400'],
                    hover: gray.dark['700'],
                },
            },
            popover: {
                background: brand['900'],
                border: brand['850'],
            },
            stepper: {
                pending: {
                    border: accent.soft,
                    badge: accent.soft,
                    text: accent.soft,
                },
                completed: {
                    border: accent.soft,
                    badge: gray.dark['25'],
                    background: accent.soft,
                    text: gray.dark['25'],
                },
                background: transparent,
            },
            pagination: {
                page: {
                    background: transparent,
                    backgroundActive: accent.muted,
                    backgroundHover: gray.dark[800],
                    border: accent.muted,
                    borderActive: accent.muted,
                    text: gray.dark[25],
                    textActive: accent.base,
                    textHover: gray.dark[300],
                },
            },
            radio: {
                background: transparent,
                backgroundChecked: transparent,
                backgroundDisabled: brand['850'],
                backgroundInvalidChecked: danger['600'],
                backgroundInvalidDisabled: danger['300'],
                backgroundIndicator: accent.base,
                backgroundDisabledIndicator: gray.dark['400'],
                backgroundInvalidIndicator: gray.dark['400'],
                backgroundInvalidDisabledIndicator: danger['400'],
                border: gray.dark['600'],
                borderChecked: accent.soft,
                borderDisabled: accent.soft,
                borderInvalid: danger['400'],
                borderInvalidChecked: danger['600'],
                borderInvalidDisabled: danger['300'],
                borderInvalidDisabledChecked: danger['300'],
                label: gray.dark['700'],
                labelDisabled: gray.dark['400'],
                labelInvalid: danger['600'],
                labelInvalidDisabled: danger['400'],
                description: gray.dark['600'],
                descriptionDisabled: gray.dark['300'],
            },
            radioGroup: {
                title: gray.dark['25'],
                subtitle: gray.dark['400'],
                hint: gray.dark['500'],
                hintInvalid: danger['400'],
            },
            scrollArea: {
                scrollbar: {
                    background: transparent,
                    backgroundHover: gray.dark['700'],
                    thumb: gray.dark['800'],
                },
                corner: transparent,
            },
            sectionFooter: {
                background: brand['950'],
            },
            sectionHeader: {
                title: gray.dark['200'],
                description: gray.dark['400'],
                dropdown: gray.dark['600'],
            },
            select: {
                contentBackground: brand['900'],
                contentBorder: brand['850'],
                noResults: gray.dark['600'],
                trigger: {
                    background: transparent,
                    backgroundDisabled: brand['800'],
                    border: brand['850'],
                    borderDisabled: brand['700'],
                    borderInvalid: danger['500'],
                    borderFocus: brand['700'],
                    borderSelected: gray.dark['500'],
                    placeholder: brand['700'],
                    placeholderDisabled: brand['700'],
                    selected: gray.dark['25'],
                    selectedDisabled: brand['700'],
                    icon: gray.dark['25'],
                    iconDisabled: brand['700'],
                },
                item: {
                    text: gray.dark['200'],
                    disabled: gray.dark['600'],
                    icon: brand['300'],
                    iconDisabled: gray.dark['600'],
                    backgroundHover: brand['850'],
                },
            },
            separator: {
                neutral: {
                    background: brand['850'],
                },
                dangerous: {
                    background: danger['300'],
                },
                emphasized: {
                    background: accent.soft,
                },
                filled: {
                    background: gray.dark['500'],
                },
            },
            slider: {
                disabledTrack: gray.dark['400'],
                disabledRange: brand['300'],
                range: brand['600'],
                thumb: {
                    disabledBorder: brand['300'],
                    background: gray.dark['700'],
                    border: brand['600'],
                },
                track: gray.dark['800'],
            },
            sidebar: {
                border: gray.dark['800'],
                background: brand['950'],
                mobileBar: brand['950'],
                collapsible: {
                    background: brand['950'],
                    backgroundHover: brand['850'],
                    border: accent.muted,
                    borderHover: accent.muted,
                    text: gray.dark['25'],
                    textHover: accent.soft,
                },
                item: {
                    groupTitle: gray.dark['300'],
                    icon: gray.dark['25'],
                    iconDisabled: gray.dark['400'],
                    text: gray.dark['25'],
                    textDisabled: gray.dark['400'],
                    iconHover: accent.soft,
                    textHover: accent.soft,
                    backgroundHover: brand['850'],
                },
                trigger: {
                    icon: gray.dark['300'],
                    iconHover: gray.dark['300'],
                    background: gray.dark['800'],
                    backgroundHover: gray.dark['600'],
                    border: gray.dark['700'],
                },
                itemActive: {
                    background: accent['gradient-light'],
                    backgroundHover: accent['gradient-dark'],
                    text: white,
                },
                subItemActive: {
                    text: accent.soft,
                    textHover: accent.base,
                },
                accordion: {
                    background: brand['900'],
                    border: brand['850'],
                },
            },
            skeleton: {
                background: `${brand['850']}33`,
                highlight: `${accent.base}33`,
            },
            table: {
                background: transparent,
                border: brand['850'],
                borderInvalid: danger['700'],
                hover: brand['900'],
                headerBackground: transparent,
                subRowHeaderBackground: `${brand['850']}33`,
                headerText: gray.dark['400'],
                rowSelected: blue['100'],
                rowStriped: `${brand['850']}1A`,
                title: white,
                rowText: gray.dark['50'],
                chevronDownIcon: brand['600'],
            },
            tabs: {
                label: white,
                labelDisabled: gray.dark['700'],
                background: transparent,
                button: {
                    emphasized: {
                        border: accent.muted,
                        background: brand['950'],
                        backgroundActive: brand['900'],
                        labelActive: accent.soft,
                    },
                    neutral: {
                        border: gray.dark['700'],
                        background: transparent,
                        backgroundActive: gray.dark['800'],
                        labelActive: gray.dark['200'],
                    },
                },
                underline: {
                    borderBottom: accent.muted,
                    emphasized: {
                        backgroundActive: transparent,
                        labelActive: accent.soft,
                        borderBottomActive: accent.soft,
                    },
                    neutral: {
                        backgroundActive: transparent,
                        labelActive: gray.dark['200'],
                        borderBottomActive: gray.dark['600'],
                    },
                },
                'underline-filled': {
                    borderBottom: gray.dark['700'],
                    emphasized: {
                        backgroundActive: brand['900'],
                        labelActive: accent.soft,
                        borderBottomActive: accent.soft,
                    },
                    neutral: {
                        backgroundActive: gray.dark['800'],
                        labelActive: gray.dark['200'],
                        borderBottomActive: gray.dark['600'],
                    },
                },
                filled: {
                    emphasized: {
                        backgroundActive: brand['900'],
                        labelActive: accent.soft,
                    },
                    neutral: {
                        labelActive: gray.dark['200'],
                        backgroundActive: gray.dark['700'],
                    },
                },
            },
            tag: {
                tagClose: {
                    icon: gray.dark['600'],
                    background: transparent,
                    iconHover: gray.dark['500'],
                    backgroundHover: gray.dark['900'],
                },
                background: transparent,
                backgroundDisabled: gray.dark['800'],
                label: gray.dark['300'],
                border: gray.dark['700'],
            },
            textArea: {
                background: transparent,
                backgroundDisabled: brand['800'],
                border: brand['850'],
                borderDisabled: brand['700'],
                borderInvalid: danger['700'],
                borderFocus: brand['700'],
                borderFilled: gray.dark['500'],
                text: gray.dark['25'],
                placeholder: brand['700'],
                scrollbar: {
                    background: transparent,
                    backgroundHover: gray.dark['50'],
                    border: gray.dark['800'],
                    thumb: gray.dark['800'],
                },
            },
            textInput: {
                background: transparent,
                backgroundDisabled: brand['800'],
                border: brand['850'],
                borderDisabled: brand['700'],
                borderInvalid: danger['700'],
                borderFocus: brand['700'],
                borderFocusInvalid: danger['700'],
                borderFilled: gray.dark['500'],
                text: gray.dark['25'],
                textDisabled: brand['700'],
                placeholder: brand['700'],
                placeholderInvalid: brand['700'],
                addon: {
                    background: gray.dark['900'],
                    border: gray.dark['700'],
                    text: gray.dark['300'],
                },
            },
            timeline: {
                content: {
                    title: gray.dark['50'],
                    meta: gray.dark['300'],
                },
                connector: brand['850'],
            },
            timePicker: {
                icon: gray.dark['300'],
                iconInvalid: danger['400'],
                text: gray.dark['300'],
                textDisabled: gray.dark['500'],
                textInvalid: danger['400'],
            },
            toggleSwitch: {
                background: gray.dark['400'],
                backgroundInvalid: danger['300'],
                backgroundChecked: accent.soft,
                backgroundDisabled: gray.dark['300'],
                backgroundCheckedHover: accent.base,
                backgroundDisabledChecked: accent.soft,
                backgroundInvalidChecked: danger['600'],
                backgroundInvalidDisabled: danger['100'],
                backgroundInvalidDisabledChecked: danger['400'],
                backgroundThumb: white,
                backgroundThumbDisabled: gray.light['50'],
                label: gray.light['700'],
                labelDisabled: gray.light['400'],
                labelInvalid: danger['600'],
                labelInvalidDisabled: danger['400'],
                description: gray.light['600'],
                descriptionDisabled: gray.light['300'],
            },
            tooltip: {
                background: brand['850'],
                title: gray.dark['100'],
                description: gray.dark['100'],
            },
            toggleButton: {
                label: gray.dark['300'],
                border: accent.muted,
                background: transparent,
                backgroundHover: brand['900'],
                selectedLabel: accent.soft,
                selectedBorder: accent.muted,
                selectedBackground: brand['850'],
                disabledLabel: gray.dark['600'],
                disabledBackground: gray.dark['700'],
                disabledBorder: gray.dark['600'],
            },
            uploader: {
                closeButtonBackground: 'rgba(0, 0, 0, 0.45)',
                closeIcon: gray.dark['200'],
            },
        },
    },
};
