import {primary, secondary} from './palette';
import type {ColorMode} from '.';

const {transparent, white, gray, brand, danger, success, warning, info, accent} = primary;
const {
    grayBlue,
    indigo,
    purple,
    pink,
    orange,
    blueLight,
    blue,
    copper,
    fuchsia,
    grayIron,
    green,
    orangeDark,
    teal,
    violet,
    yellow,
} = secondary;

export const lightMode: ColorMode = {
    ui: {
        body: {
            text: gray.light['700'],
            background: white,
        },
        style: {
            shadow: {
                color: accent.base,
                ring: {
                    offsetted: white,
                    emphasized: accent.muted,
                    dangerous: `${danger['400']}3D`,
                    neutral: `${gray.light['400']}24`,
                },
            },
        },
        component: {
            icons: {
                EmptyIcon: {
                    svg1: gray.dark['300'],
                    svg2: gray.dark['300'],
                    svg3: brand['700'],
                    svg4: gray.dark['700'],
                    svg5: gray.dark['700'],
                    svg6: gray.dark['700'],
                    svg7: gray.dark['700'],
                    svg8: brand['800'],
                    svg9: brand['800'],
                },
            },
            alert: {
                background: gray.dark['25'],
                border: gray.light['300'],
                title: gray.light['700'],
                description: gray.light['600'],
                primaryAction: gray.light['600'],
                secondaryAction: brand['700'],
                actionBackground: transparent,
            },
            alertDialog: {
                background: gray.dark['25'],
                border: gray.light['300'],
                title: gray.light['900'],
                description: gray.dark['600'],
                overlay: gray.light['950'],
            },
            accordion: {
                border: brand['200'],
                emphasized: transparent,
                neutral: gray.dark['50'],
            },
            avatar: {
                backgroundColor: gray.light['100'],
                color: gray.light['500'],
            },
            avatarInfo: {
                background: transparent,
                name: gray.light['700'],
                description: gray.light['600'],
            },
            avatarUploader: {
                border: brand['500'],
                background: white,
            },
            badge: {
                badgeClose: {
                    informative: {
                        icon: gray.light['400'],
                        background: transparent,
                        iconHover: gray.light['500'],
                        backgroundHover: gray.light['100'],
                    },
                    emphasized: {
                        icon: brand['400'],
                        background: transparent,
                        iconHover: brand['500'],
                        backgroundHover: brand['100'],
                    },
                    dangerous: {
                        icon: danger['400'],
                        background: transparent,
                        iconHover: danger['500'],
                        backgroundHover: danger['100'],
                    },
                    cautious: {
                        icon: warning['400'],
                        background: transparent,
                        iconHover: warning['500'],
                        backgroundHover: warning['100'],
                    },
                    positive: {
                        icon: success['400'],
                        background: transparent,
                        iconHover: success['500'],
                        backgroundHover: success['100'],
                    },
                    grayBlue: {
                        icon: grayBlue['400'],
                        background: transparent,
                        iconHover: grayBlue['500'],
                        backgroundHover: grayBlue['100'],
                    },
                    blueLight: {
                        icon: blueLight['400'],
                        background: transparent,
                        iconHover: blueLight['500'],
                        backgroundHover: blueLight['100'],
                    },
                    blue: {
                        icon: blue['400'],
                        background: transparent,
                        iconHover: blue['500'],
                        backgroundHover: blue['100'],
                    },
                    indigo: {
                        icon: indigo['400'],
                        background: transparent,
                        iconHover: indigo['500'],
                        backgroundHover: indigo['100'],
                    },
                    purple: {
                        icon: purple['400'],
                        background: transparent,
                        iconHover: purple['500'],
                        backgroundHover: purple['100'],
                    },
                    pink: {
                        icon: pink['400'],
                        background: transparent,
                        iconHover: pink['500'],
                        backgroundHover: pink['100'],
                    },
                    orange: {
                        icon: orange['400'],
                        background: transparent,
                        iconHover: orange['500'],
                        backgroundHover: orange['100'],
                    },
                    green: {
                        icon: green['400'],
                        background: transparent,
                        iconHover: green['500'],
                        backgroundHover: success['100'],
                    },
                    teal: {
                        icon: teal['400'],
                        background: transparent,
                        iconHover: teal['500'],
                        backgroundHover: success['100'],
                    },
                    violet: {
                        icon: violet['400'],
                        background: transparent,
                        iconHover: violet['500'],
                        backgroundHover: violet['100'],
                    },
                    fuchsia: {
                        icon: fuchsia['400'],
                        background: transparent,
                        iconHover: fuchsia['500'],
                        backgroundHover: fuchsia['100'],
                    },
                    orangeDark: {
                        icon: orangeDark['400'],
                        background: transparent,
                        iconHover: orangeDark['500'],
                        backgroundHover: orangeDark['100'],
                    },
                    yellow: {
                        icon: yellow['400'],
                        background: transparent,
                        iconHover: yellow['500'],
                        backgroundHover: yellow['100'],
                    },
                    copper: {
                        icon: copper['400'],
                        background: transparent,
                        backgroundHover: copper['100'],
                    },
                    grayIron: {
                        icon: grayIron['400'],
                        background: transparent,
                        backgroundHover: grayIron['100'],
                    },
                },
                filled: {
                    informative: {
                        label: gray.light['700'],
                        icon: gray.light['500'],
                        background: gray.light['50'],
                        border: gray.light['200'],
                    },
                    emphasized: {
                        label: brand['700'],
                        icon: brand['500'],
                        background: brand['50'],
                        border: brand['200'],
                    },
                    dangerous: {
                        label: danger['700'],
                        icon: danger['500'],
                        background: danger['50'],
                        border: danger['200'],
                    },
                    cautious: {
                        label: warning['700'],
                        icon: warning['500'],
                        background: warning['50'],
                        border: warning['200'],
                    },
                    positive: {
                        label: success['700'],
                        icon: success['500'],
                        background: success['50'],
                        border: success['200'],
                    },
                    grayBlue: {
                        label: grayBlue['700'],
                        icon: grayBlue['500'],
                        background: grayBlue['50'],
                        border: grayBlue['200'],
                    },
                    blueLight: {
                        label: blueLight['700'],
                        icon: blueLight['500'],
                        background: blueLight['50'],
                        border: blueLight['200'],
                    },
                    blue: {
                        label: blue['700'],
                        icon: blue['500'],
                        background: blue['50'],
                        border: blue['200'],
                    },
                    indigo: {
                        label: indigo['700'],
                        icon: indigo['500'],
                        background: indigo['50'],
                        border: indigo['200'],
                    },
                    purple: {
                        label: purple['700'],
                        icon: purple['500'],
                        background: purple['50'],
                        border: purple['200'],
                    },
                    pink: {
                        label: pink['700'],
                        icon: pink['500'],
                        background: pink['50'],
                        border: pink['200'],
                    },
                    orange: {
                        label: orange['700'],
                        icon: orange['500'],
                        background: orange['50'],
                        border: orange['200'],
                    },
                    green: {
                        icon: green['700'],
                        label: green['500'],
                        background: green['50'],
                        border: green['200'],
                    },
                    teal: {
                        icon: teal['700'],
                        label: teal['500'],
                        background: teal['50'],
                        border: teal['200'],
                    },
                    violet: {
                        icon: violet['700'],
                        label: violet['500'],
                        background: violet['50'],
                        border: violet['200'],
                    },
                    fuchsia: {
                        icon: fuchsia['700'],
                        label: fuchsia['500'],
                        background: fuchsia['50'],
                        border: fuchsia['200'],
                    },
                    orangeDark: {
                        icon: orangeDark['700'],
                        label: orangeDark['500'],
                        background: orangeDark['50'],
                        border: orangeDark['200'],
                    },
                    yellow: {
                        icon: yellow['700'],
                        label: yellow['500'],
                        background: yellow['50'],
                        border: orangeDark['200'],
                    },
                    copper: {
                        icon: copper['700'],
                        label: copper['500'],
                        background: copper['50'],
                        border: copper['200'],
                    },
                    grayIron: {
                        icon: grayIron['700'],
                        label: grayIron['500'],
                        background: grayIron['50'],
                        border: grayIron['200'],
                    },
                },
                outlined: {
                    informative: {
                        label: gray.light['700'],
                        icon: gray.light['600'],
                        background: transparent,
                        border: gray.light['600'],
                    },
                    emphasized: {
                        label: brand['700'],
                        icon: brand['600'],
                        background: transparent,
                        border: brand['600'],
                    },
                    dangerous: {
                        label: danger['700'],
                        icon: danger['600'],
                        background: transparent,
                        border: danger['600'],
                    },
                    cautious: {
                        label: warning['700'],
                        icon: warning['600'],
                        background: transparent,
                        border: warning['600'],
                    },
                    positive: {
                        label: success['700'],
                        icon: success['600'],
                        background: transparent,
                        border: success['600'],
                    },
                    grayBlue: {
                        label: grayBlue['700'],
                        icon: grayBlue['600'],
                        background: transparent,
                        border: grayBlue['600'],
                    },
                    blueLight: {
                        label: blueLight['700'],
                        icon: blueLight['600'],
                        background: transparent,
                        border: blueLight['600'],
                    },
                    blue: {
                        label: blue['700'],
                        icon: blue['600'],
                        background: transparent,
                        border: blue['600'],
                    },
                    indigo: {
                        label: indigo['700'],
                        icon: indigo['600'],
                        background: transparent,
                        border: indigo['600'],
                    },
                    purple: {
                        label: purple['700'],
                        icon: purple['600'],
                        background: transparent,
                        border: purple['600'],
                    },
                    pink: {
                        label: pink['700'],
                        icon: pink['600'],
                        background: transparent,
                        border: pink['600'],
                    },
                    orange: {
                        label: orange['700'],
                        icon: orange['600'],
                        background: transparent,
                        border: orange['600'],
                    },
                    green: {
                        label: green['700'],
                        icon: green['600'],
                        background: transparent,
                        border: green['600'],
                    },
                    teal: {
                        label: teal['700'],
                        icon: teal['600'],
                        background: transparent,
                        border: teal['600'],
                    },
                    violet: {
                        label: violet['700'],
                        icon: violet['600'],
                        background: transparent,
                        border: violet['600'],
                    },
                    fuchsia: {
                        label: fuchsia['700'],
                        icon: fuchsia['600'],
                        background: transparent,
                        border: fuchsia['600'],
                    },
                    orangeDark: {
                        label: orangeDark['700'],
                        icon: orangeDark['600'],
                        background: transparent,
                        border: orangeDark['600'],
                    },
                    yellow: {
                        label: yellow['700'],
                        icon: yellow['600'],
                        background: transparent,
                        border: yellow['600'],
                    },
                    copper: {
                        label: copper['700'],
                        icon: copper['600'],
                        background: transparent,
                        border: copper['600'],
                    },
                    grayIron: {
                        label: grayIron['700'],
                        icon: grayIron['600'],
                        background: transparent,
                        border: grayIron['600'],
                    },
                },
                neutral: {
                    label: gray.light['700'],
                    background: gray.light['700'],
                    border: gray.light['200'],
                    informative: {
                        icon: gray.light['600'],
                    },
                    emphasized: {
                        icon: brand['600'],
                    },
                    dangerous: {
                        icon: danger['600'],
                    },
                    cautious: {
                        icon: warning['600'],
                    },
                    positive: {
                        icon: success['600'],
                    },
                    grayBlue: {
                        icon: grayBlue['600'],
                    },
                    blueLight: {
                        icon: blueLight['600'],
                    },
                    blue: {
                        icon: blue['600'],
                    },
                    indigo: {
                        icon: indigo['600'],
                    },
                    purple: {
                        icon: purple['600'],
                    },
                    pink: {
                        icon: pink['600'],
                    },
                    orange: {
                        icon: orange['600'],
                    },
                    green: {
                        icon: green['600'],
                    },
                    teal: {
                        icon: teal['600'],
                    },
                    violet: {
                        icon: violet['600'],
                    },
                    fuchsia: {
                        icon: fuchsia['600'],
                    },
                    orangeDark: {
                        icon: orangeDark['600'],
                    },
                    yellow: {
                        icon: yellow['600'],
                    },
                    copper: {
                        icon: copper['600'],
                    },
                    grayIron: {
                        icon: grayIron['600'],
                    },
                },
                pill: {
                    informative: {
                        icon: white,
                        label: white,
                        background: info['600'],
                        border: transparent,
                    },
                    dangerous: {
                        icon: white,
                        label: white,
                        background: danger['500'],
                        border: transparent,
                    },
                    cautious: {
                        icon: white,
                        label: white,
                        background: warning['500'],
                        border: transparent,
                    },
                    emphasized: {
                        icon: white,
                        label: white,
                        background: brand['500'],
                        border: transparent,
                    },
                    positive: {
                        icon: white,
                        label: white,
                        background: success['500'],
                        border: transparent,
                    },
                    green: {
                        icon: white,
                        label: white,
                        background: green['500'],
                        border: transparent,
                    },
                    teal: {
                        icon: white,
                        label: white,
                        background: teal['500'],
                        border: transparent,
                    },
                    violet: {
                        icon: white,
                        label: white,
                        background: violet['500'],
                        border: transparent,
                    },
                    fuchsia: {
                        icon: white,
                        label: white,
                        background: fuchsia['500'],
                        border: transparent,
                    },
                    orangeDark: {
                        icon: white,
                        label: white,
                        background: orangeDark['500'],
                        border: transparent,
                    },
                    orange: {
                        icon: white,
                        label: white,
                        background: orange['500'],
                        border: transparent,
                    },
                    yellow: {
                        icon: yellow['950'],
                        label: yellow['950'],
                        background: yellow['500'],
                        border: transparent,
                    },
                    copper: {
                        icon: white,
                        label: white,
                        background: copper['500'],
                        border: transparent,
                    },
                    grayIron: {
                        icon: white,
                        label: white,
                        background: grayIron['500'],
                        border: transparent,
                    },
                    blue: {
                        icon: white,
                        label: white,
                        background: blue['500'],
                        border: transparent,
                    },
                    grayBlue: {
                        icon: white,
                        label: white,
                        background: grayBlue['500'],
                        border: transparent,
                    },
                    blueLight: {
                        icon: white,
                        label: white,
                        background: blueLight['500'],
                        border: transparent,
                    },
                    indigo: {
                        icon: white,
                        label: white,
                        background: indigo['500'],
                        border: transparent,
                    },
                    purple: {
                        icon: white,
                        label: white,
                        background: purple['500'],
                        border: transparent,
                    },
                    pink: {
                        icon: white,
                        label: white,
                        background: pink['500'],
                        border: transparent,
                    },
                },
            },
            button: {
                primary: {
                    emphasized: {
                        background: accent['gradient-light'],
                        backgroundActive: accent['gradient-dark'],
                        backgroundDisabled: gray.dark['200'],
                        backgroundHover: accent['gradient-dark'],
                        backgroundLoading: accent['gradient-light'],
                        text: white,
                        textDisabled: gray.dark['300'],
                    },
                    neutral: {
                        background: gray.light['600'],
                        backgroundActive: gray.light['800'],
                        backgroundDisabled: gray.light['300'],
                        backgroundHover: gray.light['700'],
                        backgroundLoading: gray.light['300'],
                        text: white,
                        textDisabled: white,
                    },
                    dangerous: {
                        background: danger['600'],
                        backgroundActive: danger['800'],
                        backgroundDisabled: danger['300'],
                        backgroundHover: danger['700'],
                        backgroundLoading: danger['300'],
                        text: white,
                        textDisabled: white,
                    },
                    cautious: {
                        background: warning['600'],
                        backgroundActive: warning['800'],
                        backgroundDisabled: warning['300'],
                        backgroundHover: warning['700'],
                        backgroundLoading: warning['300'],
                        text: white,
                        textDisabled: white,
                    },
                    positive: {
                        background: success['600'],
                        backgroundActive: success['800'],
                        backgroundDisabled: success['300'],
                        backgroundHover: success['700'],
                        backgroundLoading: success['300'],
                        text: white,
                        textDisabled: white,
                    },
                },
                secondary: {
                    emphasized: {
                        background: transparent,
                        backgroundActive: gray.dark['25'],
                        backgroundHover: gray.dark['25'],
                        backgroundDisabled: gray.dark['200'],
                        backgroundLoading: transparent,
                        border: accent.muted,
                        borderDisabled: transparent,
                        borderLoading: accent.muted,
                        icon: brand['700'],
                        text: brand['700'],
                        textActive: accent.base,
                        textDisabled: gray.dark['300'],
                        textHover: accent.base,
                        textLoading: brand['700'],
                    },
                    neutral: {
                        background: transparent,
                        backgroundActive: gray.light['200'],
                        backgroundHover: gray.light['100'],
                        backgroundDisabled: gray.light['200'],
                        border: gray.light['300'],
                        borderDisabled: gray.light['200'],
                        backgroundLoading: transparent,
                        borderLoading: gray.light['200'],
                        icon: gray.light['700'],
                        text: gray.light['700'],
                        textActive: gray.light['700'],
                        textDisabled: gray.light['300'],
                        textHover: gray.light['600'],
                        textLoading: gray.light['300'],
                    },
                    dangerous: {
                        background: transparent,
                        backgroundActive: danger['200'],
                        backgroundHover: danger['100'],
                        backgroundDisabled: danger['200'],
                        border: danger['300'],
                        borderDisabled: danger['200'],
                        backgroundLoading: transparent,
                        borderLoading: danger['200'],
                        icon: danger['700'],
                        text: danger['700'],
                        textActive: danger['700'],
                        textDisabled: danger['300'],
                        textHover: danger['600'],
                        textLoading: danger['300'],
                    },
                    cautious: {
                        background: transparent,
                        backgroundActive: warning['200'],
                        backgroundHover: warning['100'],
                        backgroundDisabled: warning['200'],
                        backgroundLoading: transparent,
                        border: warning['300'],
                        borderDisabled: warning['200'],
                        borderLoading: warning['200'],
                        icon: warning['700'],
                        text: warning['700'],
                        textActive: warning['700'],
                        textDisabled: warning['300'],
                        textHover: warning['600'],
                        textLoading: warning['300'],
                    },
                    positive: {
                        background: transparent,
                        backgroundActive: success['200'],
                        backgroundHover: success['100'],
                        backgroundDisabled: success['200'],
                        backgroundLoading: transparent,
                        border: success['300'],
                        borderDisabled: success['200'],
                        borderLoading: success['200'],
                        icon: success['700'],
                        text: success['700'],
                        textActive: success['700'],
                        textDisabled: success['300'],
                        textHover: success['600'],
                        textLoading: success['300'],
                    },
                },
                tertiary: {
                    emphasized: {
                        background: transparent,
                        backgroundActive: brand['200'],
                        backgroundHover: brand['100'],
                        icon: brand['700'],
                        text: brand['700'],
                        textActive: brand['700'],
                        textDisabled: brand['300'],
                        textHover: brand['600'],
                        textLoading: brand['300'],
                    },
                    neutral: {
                        background: transparent,
                        backgroundActive: gray.light['200'],
                        backgroundHover: brand['50'],
                        icon: gray.light['700'],
                        text: gray.light['700'],
                        textActive: gray.light['700'],
                        textDisabled: gray.light['300'],
                        textHover: gray.light['600'],
                        textLoading: gray.light['300'],
                    },
                    dangerous: {
                        background: transparent,
                        backgroundActive: danger['200'],
                        backgroundHover: danger['100'],
                        icon: danger['700'],
                        text: danger['700'],
                        textActive: danger['700'],
                        textDisabled: danger['300'],
                        textHover: danger['600'],
                        textLoading: danger['300'],
                    },
                    cautious: {
                        background: transparent,
                        backgroundActive: warning['200'],
                        backgroundHover: warning['100'],
                        icon: warning['700'],
                        text: warning['700'],
                        textActive: warning['700'],
                        textDisabled: warning['300'],
                        textHover: warning['600'],
                        textLoading: warning['300'],
                    },
                    positive: {
                        background: transparent,
                        backgroundActive: success['200'],
                        backgroundHover: success['100'],
                        icon: success['700'],
                        text: success['700'],
                        textActive: success['700'],
                        textDisabled: success['300'],
                        textHover: success['600'],
                        textLoading: success['300'],
                    },
                },
                link: {
                    emphasized: {
                        background: transparent,
                        icon: accent.base,
                        text: accent.base,
                        textActive: accent.soft,
                        textDisabled: gray.dark['300'],
                        textHover: accent.soft,
                        textLoading: brand['700'],
                    },
                    neutral: {
                        background: transparent,
                        icon: gray.light['600'],
                        text: gray.light['600'],
                        textActive: gray.light['600'],
                        textDisabled: gray.light['300'],
                        textHover: gray.light['700'],
                        textLoading: gray.light['300'],
                    },
                    dangerous: {
                        background: transparent,
                        icon: danger['700'],
                        text: danger['700'],
                        textActive: danger['700'],
                        textDisabled: danger['300'],
                        textHover: danger['800'],
                        textLoading: danger['300'],
                    },
                    cautious: {
                        background: transparent,
                        icon: warning['700'],
                        text: warning['700'],
                        textActive: warning['700'],
                        textDisabled: warning['300'],
                        textHover: warning['600'],
                        textLoading: warning['300'],
                    },
                    positive: {
                        background: transparent,
                        icon: success['700'],
                        text: success['700'],
                        textActive: success['700'],
                        textDisabled: success['300'],
                        textHover: success['600'],
                        textLoading: success['300'],
                    },
                },
            },
            breadcrumb: {
                separator: gray.dark[300],
                lastPage: accent.soft,
                lastPageHover: accent.soft,
                text: accent.base,
                textHover: accent.soft,
            },
            carousel: {
                background: gray.dark['25'],
                button: accent.base,
            },
            card: {
                default: {
                    border: accent.muted,
                    background: gray.dark['25'],
                },
                soft: {
                    border: gray.dark['200'],
                    background: gray.light['100'],
                },
            },
            checkbox: {
                background: transparent,
                backgroundChecked: transparent,
                backgroundDisabled: gray.light['300'],
                backgroundDisabledChecked: gray.light['300'],
                backgroundInvalidChecked: danger['600'],
                backgroundInvalidDisabled: danger['300'],
                border: gray.dark['600'],
                borderChecked: accent.soft,
                borderDisabled: accent.soft,
                borderDisabledChecked: accent.soft,
                borderInvalid: danger['400'],
                borderInvalidChecked: danger['600'],
                borderInvalidDisabled: danger['300'],
                borderInvalidDisabledChecked: danger['300'],
                tick: accent.soft,
                tickDisable: accent.soft,
                tickInvalid: white,
                tickInvalidDisabledChecked: white,
                label: gray.dark['700'],
                labelDisabled: gray.dark['400'],
                labelInvalid: danger['600'],
                labelInvalidDisabled: danger['400'],
                description: gray.dark['600'],
                descriptionDisabled: gray.dark['300'],
            },
            checkboxGroup: {
                title: brand['700'],
                subtitle: gray.light['600'],
                hint: gray.light['500'],
                hintInvalid: danger['600'],
            },
            circularProgress: {
                label: gray.light['600'],
                value: gray.light['900'],
                track: gray.light['100'],
                indicator: {
                    primary: brand['600'],
                    neutral: gray.light['600'],
                },
            },
            closeButton: {
                icon: gray.light['400'],
                iconHover: gray.light['500'],
                iconBackground: transparent,
                iconBackgroundHover: gray.light['50'],
            },
            colorPicker: {
                background: gray.dark['25'],
                border: gray.dark['200'],
                inputBorder: brand['500'],
                colorSelectBorder: gray.dark['200'],
                colorSelectBorderActive: gray.dark['900'],
                colorSelectInnerBorder: gray.dark['200'],
                color: brand['700'],
                trigger: {
                    background: transparent,
                    border: brand['500'],
                },
            },
            combobox: {
                menuBackground: gray.dark['25'],
                menuBorder: brand['500'],
                noResults: gray.light['400'],
                trigger: {
                    background: white,
                    backgroundDisabled: gray.light['200'],
                    border: brand['500'],
                    borderDisabled: gray.light['300'],
                    borderInvalid: danger['500'],
                    borderFocus: brand['300'],
                    borderSelected: brand['500'],
                    placeholder: gray.light['300'],
                    placeholderDisabled: gray.light['300'],
                    text: brand['700'],
                    textDisabled: gray.light['300'],
                    icon: brand['700'],
                    iconDisabled: gray.light['300'],
                },
                item: {
                    text: brand['700'],
                    background: transparent,
                    backgroundHover: brand['50'],
                    disabled: gray.light['400'],
                    icon: brand['600'],
                    iconDisabled: gray.light['400'],
                },
            },
            datePicker: {
                background: gray.dark['25'],
                label: gray.dark['700'],
                labelHover: gray.dark['800'],
                backgroundHover: brand['50'],
                selectBackground: accent.soft,
                selectBackgroundHover: accent.base,
                selectLabel: white,
                selectLabelRange: gray.dark['700'],
                selectRangeBackground: gray.dark['100'],
                dayOutside: gray.dark['400'],
                border: gray.dark['50'],
                labelDisabled: gray.light['400'],
            },
            drawer: {
                background: gray.dark['25'],
                border: gray.light['300'],
                title: gray.light['900'],
                description: gray.light['600'],
                overlay: gray.light['950'],
            },
            dropdown: {
                background: gray.dark['25'],
                border: gray.dark['200'],
                separator: gray.light['200'],
                item: {
                    backgroundDisabled: gray.light['50'],
                    hover: brand['50'],
                    icon: gray.light['500'],
                    iconDisabled: gray.light['400'],
                    label: brand['700'],
                    labelDisabled: gray.light['500'],
                    shortcut: gray.light['500'],
                    shortcutDisabled: gray.light['400'],
                },
            },
            dropzone: {
                background: transparent,
                disabledBackground: gray.light['50'],
                border: brand['500'],
                dragActiveBorder: brand['600'],
                icon: brand['700'],
            },
            featuredIcon: {
                border: {
                    neutral: gray.dark['200'],
                    emphasized: accent.muted,
                    informative: gray.dark['500'],
                    positive: success['600'],
                    cautious: warning['600'],
                    dangerous: danger['600'],
                },
                background: {
                    neutral: gray.dark['200'],
                    emphasized: accent.muted,
                    informative: gray.light['100'],
                    positive: success['100'],
                    cautious: warning['100'],
                    dangerous: danger['100'],
                },
                icon: {
                    neutral: gray.dark['700'],
                    emphasized: brand['700'],
                    informative: gray.dark['500'],
                    positive: success['600'],
                    cautious: warning['600'],
                    dangerous: danger['600'],
                },
            },
            field: {
                hint: brand['700'],
                hintInvalid: danger['500'],
                hintDisabled: gray.dark['300'],
            },
            galleryModal: {
                border: accent.soft,
                cardBackground: transparent,
            },
            label: {
                title: brand['700'],
                titleDisabled: gray.dark['300'],
                description: brand['700'],
                descriptionDisabled: gray.dark['300'],
                optional: gray.light['400'],
                hint: accent.base,
            },
            link: {
                dangerous: {
                    text: danger['600'],
                    textHover: danger['700'],
                },
                emphasized: {
                    text: accent.base,
                    textHover: accent.soft,
                },
                neutral: {
                    text: gray.light['600'],
                    textHover: gray.light['700'],
                },
                textDisabled: gray.dark['300'],
            },
            linearProgress: {
                teal: {
                    background: `${teal['700']}26`,
                    indicator: teal['500'],
                },
                informative: {
                    background: `${info['700']}26`,
                    indicator: info['500'],
                },
                orangeDark: {
                    background: `${orangeDark['800']}26`,
                    indicator: orangeDark['500'],
                },
                violet: {
                    background: `${violet['700']}1A`,
                    indicator: violet['500'],
                },
                fuchsia: {
                    background: `${fuchsia['700']}1A`,
                    indicator: fuchsia['500'],
                },
                yellow: {
                    background: `${yellow['700']}1A`,
                    indicator: yellow['500'],
                },
            },
            modal: {
                background: gray.dark['25'],
                border: gray.dark['200'],
                title: brand['850'],
                description: gray.dark['600'],
                overlay: gray.dark['950'],
            },
            navigationHeader: {
                background: transparent,
                hoverItem: gray.light['200'],
                currentPage: gray.light['200'],
            },
            pageHeader: {
                background: transparent,
                title: brand['850'],
                back: {
                    hover: gray.light['400'],
                    text: gray.light['700'],
                },
            },
            popover: {
                background: gray.dark['25'],
                border: gray.dark['200'],
            },
            stepper: {
                pending: {
                    border: accent.base,
                    badge: accent.base,
                    text: accent.base,
                },
                completed: {
                    border: accent.base,
                    badge: gray.dark['25'],
                    background: accent.base,
                    text: gray.dark['600'],
                },
                background: transparent,
            },
            pagination: {
                page: {
                    background: transparent,
                    backgroundActive: gray.light[100],
                    border: gray.light[300],
                    backgroundHover: gray.light[100],
                    text: gray.light[700],
                    textHover: gray.light[800],
                    borderActive: gray.light[200],
                    textActive: gray.light[700],
                },
            },
            radio: {
                background: white,
                backgroundChecked: white,
                backgroundDisabled: gray.light['100'],
                backgroundInvalidChecked: danger['600'],
                backgroundInvalidDisabled: danger['200'],
                backgroundIndicator: accent.soft,
                backgroundDisabledIndicator: gray.light['300'],
                backgroundInvalidDisabledIndicator: danger['300'],
                backgroundInvalidIndicator: white,
                border: gray.light['300'],
                borderChecked: accent.soft,
                borderDisabled: gray.light['300'],
                borderInvalid: danger['400'],
                borderInvalidChecked: danger['600'],
                borderInvalidDisabled: danger['300'],
                borderInvalidDisabledChecked: danger['200'],
                label: gray.light['700'],
                labelDisabled: gray.light['400'],
                labelInvalid: danger['600'],
                labelInvalidDisabled: danger['400'],
                description: gray.light['600'],
                descriptionDisabled: gray.light['300'],
            },
            radioGroup: {
                title: brand['700'],
                subtitle: gray.light['600'],
                hint: gray.light['500'],
                hintInvalid: danger['600'],
            },
            scrollArea: {
                scrollbar: {
                    background: transparent,
                    backgroundHover: gray.light['50'],
                    thumb: gray.light['200'],
                },
                corner: transparent,
            },
            sectionFooter: {
                background: white,
            },
            sectionHeader: {
                title: gray.light['900'],
                description: gray.light['600'],
                dropdown: gray.light['400'],
            },
            select: {
                contentBackground: gray.dark['25'],
                contentBorder: brand['100'],
                noResults: gray.light['400'],
                trigger: {
                    background: white,
                    backgroundDisabled: gray.light['200'],
                    border: brand['500'],
                    borderDisabled: gray.light['300'],
                    borderInvalid: danger['500'],
                    borderFocus: brand['300'],
                    borderSelected: brand['500'],
                    placeholder: gray.light['300'],
                    placeholderDisabled: gray.light['300'],
                    selected: brand['700'],
                    selectedDisabled: gray.light['300'],
                    icon: brand['700'],
                    iconDisabled: gray.light['300'],
                },
                item: {
                    text: brand['700'],
                    disabled: gray.light['400'],
                    icon: brand['600'],
                    iconDisabled: gray.light['400'],
                    backgroundHover: brand['50'],
                },
            },
            separator: {
                neutral: {
                    background: gray.light['200'],
                },
                dangerous: {
                    background: danger['300'],
                },
                emphasized: {
                    background: accent.base,
                },
                filled: {
                    background: gray.light['50'],
                },
            },
            sidebar: {
                border: gray.light['200'],
                collapsible: {
                    background: white,
                    backgroundHover: gray.light['100'],
                    border: accent.muted,
                    borderHover: accent.muted,
                    text: brand['700'],
                    textHover: brand['600'],
                },
                background: white,
                mobileBar: white,
                item: {
                    groupTitle: gray.dark['400'],
                    icon: brand['700'],
                    iconDisabled: gray.light['300'],
                    text: brand['700'],
                    textDisabled: gray.light['400'],
                    textHover: brand['600'],
                    iconHover: brand['600'],
                    backgroundHover: gray.light['100'],
                },
                trigger: {
                    icon: gray.dark['400'],
                    iconHover: gray.dark['500'],
                    background: transparent,
                    backgroundHover: gray.light['50'],
                    border: gray.dark['200'],
                },
                itemActive: {
                    background: accent['gradient-light'],
                    backgroundHover: accent['gradient-dark'],
                    text: white,
                },
                subItemActive: {
                    text: accent.base,
                    textHover: accent.soft,
                },
                accordion: {
                    background: gray.dark['25'],
                    border: gray.dark['200'],
                },
            },
            skeleton: {
                background: `${brand['850']}1A`,
                highlight: `${accent.base}40`,
            },
            slider: {
                disabledTrack: gray.light['100'],
                disabledRange: brand['200'],
                range: brand['600'],
                thumb: {
                    disabledBorder: brand['200'],
                    background: white,
                    border: brand['600'],
                },
                track: gray.light['200'],
            },
            table: {
                background: transparent,
                border: gray.dark['300'],
                borderInvalid: danger['400'],
                hover: gray.dark['100'],
                headerBackground: transparent,
                subRowHeaderBackground: `${brand['850']}0D`,
                headerText: gray.dark['600'],
                rowSelected: blue['100'],
                rowStriped: `${brand['850']}0D`,
                title: brand['850'],
                rowText: gray.dark['600'],
                chevronDownIcon: brand['600'],
            },
            tabs: {
                label: gray.light['500'],
                labelDisabled: gray.light['400'],
                background: transparent,
                button: {
                    emphasized: {
                        border: accent.muted,
                        background: transparent,
                        backgroundActive: accent.muted,
                        labelActive: accent.base,
                    },
                    neutral: {
                        border: gray.light['300'],
                        background: transparent,
                        backgroundActive: gray.dark['200'],
                        labelActive: gray.light['700'],
                    },
                },
                underline: {
                    borderBottom: gray.dark['200'],
                    emphasized: {
                        backgroundActive: transparent,
                        labelActive: accent.base,
                        borderBottomActive: accent.base,
                    },
                    neutral: {
                        backgroundActive: transparent,
                        labelActive: gray.light['700'],
                        borderBottomActive: brand['700'],
                    },
                },
                'underline-filled': {
                    borderBottom: accent.muted,
                    emphasized: {
                        backgroundActive: accent.muted,
                        labelActive: accent.base,
                        borderBottomActive: accent.base,
                    },
                    neutral: {
                        backgroundActive: gray.light['200'],
                        labelActive: gray.light['700'],
                        borderBottomActive: brand['700'],
                    },
                },
                filled: {
                    emphasized: {
                        backgroundActive: accent.muted,
                        labelActive: accent.base,
                    },
                    neutral: {
                        backgroundActive: gray.dark['200'],
                        labelActive: gray.light['700'],
                    },
                },
            },
            tag: {
                tagClose: {
                    icon: gray.light['400'],
                    background: transparent,
                    iconHover: gray.light['500'],
                    backgroundHover: gray.light['100'],
                },
                background: transparent,
                backgroundDisabled: gray.light['50'],
                label: gray.light['700'],
                border: gray.light['300'],
            },
            textArea: {
                background: white,
                backgroundDisabled: gray.dark['200'],
                border: brand['500'],
                borderDisabled: gray.dark['300'],
                borderInvalid: danger['500'],
                borderFocus: brand['300'],
                borderFilled: brand['500'],
                text: brand['700'],
                placeholder: gray.dark['300'],
                scrollbar: {
                    background: transparent,
                    backgroundHover: gray.light['50'],
                    border: gray.light['200'],
                    thumb: gray.light['200'],
                },
            },
            textInput: {
                background: white,
                backgroundDisabled: gray.dark['200'],
                border: brand['500'],
                borderDisabled: gray.dark['300'],
                borderInvalid: danger['500'],
                borderFocus: brand['300'],
                borderFilled: brand['500'],
                borderFocusInvalid: danger['300'],
                text: brand['700'],
                textDisabled: gray.dark['300'],
                placeholder: gray.dark['300'],
                placeholderInvalid: gray.dark['300'],
                addon: {
                    background: white,
                    border: gray.light['300'],
                    text: gray.light['600'],
                },
            },
            timeline: {
                content: {
                    title: gray.dark['600'],
                    meta: gray.dark['400'],
                },
                connector: gray.dark['200'],
            },
            timePicker: {
                icon: gray.light['700'],
                iconInvalid: danger['600'],
                text: gray.light['700'],
                textDisabled: gray.light['500'],
                textInvalid: danger['600'],
            },
            toggleSwitch: {
                background: gray.dark['400'],
                backgroundInvalid: danger['300'],
                backgroundChecked: accent.soft,
                backgroundDisabled: gray.dark['200'],
                backgroundCheckedHover: accent.base,
                backgroundDisabledChecked: accent.soft,
                backgroundInvalidChecked: danger['600'],
                backgroundInvalidDisabled: danger['100'],
                backgroundInvalidDisabledChecked: danger['200'],
                backgroundThumb: white,
                backgroundThumbDisabled: gray.light['50'],
                label: gray.light['700'],
                labelDisabled: gray.light['400'],
                labelInvalid: danger['600'],
                labelInvalidDisabled: danger['400'],
                description: gray.light['600'],
                descriptionDisabled: gray.light['300'],
            },
            tooltip: {
                background: gray.dark['100'],
                title: brand['600'],
                description: brand['600'],
            },
            toggleButton: {
                label: brand['700'],
                border: accent.muted,
                background: transparent,
                backgroundHover: accent.muted,
                selectedLabel: accent.base,
                selectedBorder: accent.muted,
                selectedBackground: accent.muted,
                disabledLabel: gray.light['400'],
                disabledBackground: gray.light['50'],
                disabledBorder: gray.light['200'],
            },
            uploader: {
                closeButtonBackground: 'rgba(0, 0, 0, 0.45)',
                closeIcon: gray.light['200'],
            },
        },
    },
};
