/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  PrepareUploadInputDto,
  PreparedUploadDto,
  TempUploadDto,
  UploadLocalInputDto
} from '../../models';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Prepare a file upload and get upload instructions
 */
export const prepareUpload = (
    prepareUploadInputDto: PrepareUploadInputDto,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PreparedUploadDto>(
      {url: `/api/v1/upload/prepare`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: prepareUploadInputDto, signal
    },
      options);
    }
  


export const getPrepareUploadMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof prepareUpload>>, TError,{data: PrepareUploadInputDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof prepareUpload>>, TError,{data: PrepareUploadInputDto}, TContext> => {

const mutationKey = ['prepareUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof prepareUpload>>, {data: PrepareUploadInputDto}> = (props) => {
          const {data} = props ?? {};

          return  prepareUpload(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PrepareUploadMutationResult = NonNullable<Awaited<ReturnType<typeof prepareUpload>>>
    export type PrepareUploadMutationBody = PrepareUploadInputDto
    export type PrepareUploadMutationError = ApiProblem

    /**
 * @summary Prepare a file upload and get upload instructions
 */
export const usePrepareUpload = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof prepareUpload>>, TError,{data: PrepareUploadInputDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof prepareUpload>>,
        TError,
        {data: PrepareUploadInputDto},
        TContext
      > => {

      const mutationOptions = getPrepareUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Upload a file directly to the server (local storage only)
 */
export const uploadLocal = (
    uploadLocalInputDto: UploadLocalInputDto,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`tempPath`, uploadLocalInputDto.tempPath)

      return apiClient<TempUploadDto>(
      {url: `/api/v1/upload/local`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getUploadLocalMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadLocal>>, TError,{data: UploadLocalInputDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadLocal>>, TError,{data: UploadLocalInputDto}, TContext> => {

const mutationKey = ['uploadLocal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadLocal>>, {data: UploadLocalInputDto}> = (props) => {
          const {data} = props ?? {};

          return  uploadLocal(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadLocalMutationResult = NonNullable<Awaited<ReturnType<typeof uploadLocal>>>
    export type UploadLocalMutationBody = UploadLocalInputDto
    export type UploadLocalMutationError = ApiProblem

    /**
 * @summary Upload a file directly to the server (local storage only)
 */
export const useUploadLocal = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadLocal>>, TError,{data: UploadLocalInputDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadLocal>>,
        TError,
        {data: UploadLocalInputDto},
        TContext
      > => {

      const mutationOptions = getUploadLocalMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    