/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  CreateProfessionalDto,
  Professional,
  SearchProfessionalsParams,
  UpdateProfessionalInputDto
} from '../../models';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Creates a new professional
 */
export const createProfessional = (
    createProfessionalDto: CreateProfessionalDto,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<Professional>(
      {url: `/api/v1/professionals`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProfessionalDto, signal
    },
      options);
    }
  


export const getCreateProfessionalMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfessional>>, TError,{data: CreateProfessionalDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof createProfessional>>, TError,{data: CreateProfessionalDto}, TContext> => {

const mutationKey = ['createProfessional'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProfessional>>, {data: CreateProfessionalDto}> = (props) => {
          const {data} = props ?? {};

          return  createProfessional(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProfessionalMutationResult = NonNullable<Awaited<ReturnType<typeof createProfessional>>>
    export type CreateProfessionalMutationBody = CreateProfessionalDto
    export type CreateProfessionalMutationError = ApiProblem

    /**
 * @summary Creates a new professional
 */
export const useCreateProfessional = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProfessional>>, TError,{data: CreateProfessionalDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProfessional>>,
        TError,
        {data: CreateProfessionalDto},
        TContext
      > => {

      const mutationOptions = getCreateProfessionalMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Lists and searches professionals
 */
export const searchProfessionals = (
    params: SearchProfessionalsParams,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/professionals`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchProfessionalsQueryKey = (params?: SearchProfessionalsParams,) => {
    return [
    `/api/v1/professionals`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchProfessionalsQueryOptions = <TData = Awaited<ReturnType<typeof searchProfessionals>>, TError = ApiProblem>(params: SearchProfessionalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProfessionals>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchProfessionalsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProfessionals>>> = ({ signal }) => searchProfessionals(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchProfessionals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchProfessionalsQueryResult = NonNullable<Awaited<ReturnType<typeof searchProfessionals>>>
export type SearchProfessionalsQueryError = ApiProblem


export function useSearchProfessionals<TData = Awaited<ReturnType<typeof searchProfessionals>>, TError = ApiProblem>(
 params: SearchProfessionalsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProfessionals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProfessionals>>,
          TError,
          Awaited<ReturnType<typeof searchProfessionals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProfessionals<TData = Awaited<ReturnType<typeof searchProfessionals>>, TError = ApiProblem>(
 params: SearchProfessionalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProfessionals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProfessionals>>,
          TError,
          Awaited<ReturnType<typeof searchProfessionals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchProfessionals<TData = Awaited<ReturnType<typeof searchProfessionals>>, TError = ApiProblem>(
 params: SearchProfessionalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProfessionals>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists and searches professionals
 */

export function useSearchProfessionals<TData = Awaited<ReturnType<typeof searchProfessionals>>, TError = ApiProblem>(
 params: SearchProfessionalsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchProfessionals>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchProfessionalsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Gets a professional by ID
 */
export const getProfessional = (
    id: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<Professional>(
      {url: `/api/v1/professionals/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProfessionalQueryKey = (id?: string,) => {
    return [
    `/api/v1/professionals/${id}`
    ] as const;
    }

    
export const getGetProfessionalQueryOptions = <TData = Awaited<ReturnType<typeof getProfessional>>, TError = ApiProblem>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfessional>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProfessionalQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfessional>>> = ({ signal }) => getProfessional(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProfessional>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProfessionalQueryResult = NonNullable<Awaited<ReturnType<typeof getProfessional>>>
export type GetProfessionalQueryError = ApiProblem


export function useGetProfessional<TData = Awaited<ReturnType<typeof getProfessional>>, TError = ApiProblem>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfessional>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfessional>>,
          TError,
          Awaited<ReturnType<typeof getProfessional>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfessional<TData = Awaited<ReturnType<typeof getProfessional>>, TError = ApiProblem>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfessional>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfessional>>,
          TError,
          Awaited<ReturnType<typeof getProfessional>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfessional<TData = Awaited<ReturnType<typeof getProfessional>>, TError = ApiProblem>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfessional>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Gets a professional by ID
 */

export function useGetProfessional<TData = Awaited<ReturnType<typeof getProfessional>>, TError = ApiProblem>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfessional>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProfessionalQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Updates a professional
 */
export const updateProfessional = (
    id: string,
    updateProfessionalInputDto: UpdateProfessionalInputDto,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<Professional>(
      {url: `/api/v1/professionals/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateProfessionalInputDto
    },
      options);
    }
  


export const getUpdateProfessionalMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfessional>>, TError,{id: string;data: UpdateProfessionalInputDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProfessional>>, TError,{id: string;data: UpdateProfessionalInputDto}, TContext> => {

const mutationKey = ['updateProfessional'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProfessional>>, {id: string;data: UpdateProfessionalInputDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProfessional(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProfessionalMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfessional>>>
    export type UpdateProfessionalMutationBody = UpdateProfessionalInputDto
    export type UpdateProfessionalMutationError = ApiProblem

    /**
 * @summary Updates a professional
 */
export const useUpdateProfessional = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfessional>>, TError,{id: string;data: UpdateProfessionalInputDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProfessional>>,
        TError,
        {id: string;data: UpdateProfessionalInputDto},
        TContext
      > => {

      const mutationOptions = getUpdateProfessionalMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Deletes a professional
 */
export const deleteProfessional = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/professionals/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteProfessionalMutationOptions = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfessional>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProfessional>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteProfessional'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProfessional>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteProfessional(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProfessionalMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProfessional>>>
    
    export type DeleteProfessionalMutationError = ApiProblem

    /**
 * @summary Deletes a professional
 */
export const useDeleteProfessional = <TError = ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProfessional>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProfessional>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteProfessionalMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    