import type {AxiosError, AxiosRequestConfig} from 'axios';
import axios from 'axios';

export {AxiosError} from 'axios';
export type {AxiosRequestHeaders} from 'axios';

export const getBaseURL = () => {
    if (import.meta.env.VITE_API_URL) {
        return import.meta.env.VITE_API_URL;
    }

    if (globalThis.window === undefined) {
        return 'http://localhost:3000';
    }

    const {origin} = globalThis.location;

    if (import.meta.env.PROD) {
        return origin;
    }

    return `${origin.replace(/:\d+$/, '')}:${import.meta.env.VITE_API_PORT ?? 3000}`;
};

export const AXIOS_INSTANCE = axios.create({
    baseURL: getBaseURL(),
    withCredentials: true,
});

export const apiClient = <T>(config: AxiosRequestConfig, options?: AxiosRequestConfig): Promise<T> =>
    AXIOS_INSTANCE({...config, ...options}).then(({data}) => data);

export type ErrorType<Error> = AxiosError<Error>;

export type DownloadedFile = {content: Blob; fileName: string | null};

const FILENAME_PATTERN = /filename="?([^";]+)"?/i;

/**
 * Not generated by Orval — this is the one place file-download endpoints (e.g. report export)
 * are allowed to call Axios by hand, since Orval's generated hooks assume a JSON response body.
 */
export const downloadFile = (url: string, params?: Record<string, unknown>): Promise<DownloadedFile> =>
    AXIOS_INSTANCE.get<Blob>(url, {responseType: 'blob', params}).then(({data, headers}) => ({
        content: data,
        fileName: FILENAME_PATTERN.exec(String(headers['content-disposition'] ?? ''))?.[1] ?? null,
    }));
