import type {AtRule} from 'csstype';
import {breakpoints} from '../responsiveness';
import type {Theme as StyledTheme, ThemeSpacing} from '.';

const spacing: ThemeSpacing = {
    0: '0',
    0.5: '0.125rem',
    1: '0.25rem',
    1.5: '0.375rem',
    2: '0.5rem',
    2.25: '0.5625rem',
    2.5: '0.625rem',
    2.75: '0.6875rem',
    3: '0.75rem',
    3.5: '0.875rem',
    3.75: '0.9375rem',
    4: '1rem',
    4.5: '1.125rem',
    5: '1.25rem',
    5.5: '1.375rem',
    6: '1.5rem',
    6.5: '1.625rem',
    7: '1.75rem',
    7.5: '1.875rem',
    8: '2rem',
    9: '2.25rem',
    10: '2.5rem',
    11: '2.75rem',
    12: '3rem',
    13: '3.25rem',
    14: '3.5rem',
    15: '3.75rem',
    16: '4rem',
    18: '4.5rem',
    20: '5rem',
    24: '6rem',
    26: '6.5rem',
    28: '7rem',
    30: '7.5rem',
    32: '8rem',
    40: '10rem',
    44: '11rem',
    48: '12rem',
    50: '12.5rem',
    56: '14rem',
    60: '15rem',
    64: '16rem',
    70: '17.5rem',
    72: '18rem',
    80: '20rem',
    96: '24rem',
    112: '28rem',
    128: '32rem',
};

export const theme: Omit<StyledTheme, 'colors'> = {
    breakpoints,
    fonts: {
        default: 'Readex Pro, Inter, -apple-system, "Helvetica Neue", sans-serif',
        monospace: 'Roboto Mono, Menlo, monospace',
    },
    fontSizes: {
        text: {
            xs: '0.75rem',
            sm: '0.875rem',
            md: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
        },
        display: {
            xs: '1.5rem',
            sm: '1.875rem',
            md: '2.25rem',
            lg: '3rem',
            xl: '3.75rem',
            '2xl': '4.5rem',
        },
    },
    lineHeights: {
        text: {
            xs: '1.125rem',
            sm: '1.25rem',
            md: '1.5rem',
            lg: '1.75rem',
            xl: '1.875rem',
        },
        display: {
            xs: '2rem',
            sm: '2.375rem',
            md: '2.75rem',
            lg: '3.75rem',
            xl: '4.5rem',
            '2xl': '5.625rem',
        },
    },
    fontWeights: {
        extraLight: 200,
        regular: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
    },
    space: {
        ...spacing,
        none: '0',
        xxs: '0.125rem',
        xs: '0.25rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
        '6xl': '3rem',
        '7xl': '4rem',
        '8xl': '5rem',
        '9xl': '6rem',
        '10xl': '8rem',
        '11xl': '10rem',
    },
    sizes: {
        ...spacing,
        xs: breakpoints[0],
        sm: breakpoints[1],
        md: breakpoints[2],
        lg: breakpoints[3],
        xl: breakpoints[4],
        '2xl': breakpoints[5],
    },
    radii: {
        none: '0',
        xxs: '0.125rem',
        xs: '0.25rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.625rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
        '4xl': '1.5rem',
        full: '9999px',
    },
    root: {
        '@font-face': {
            fontFamily: 'Readex Pro',
            src: "url('/fonts/ReadexPro.ttf') format('truetype')",
            fontWeight: '200 700',
            fontStyle: 'normal',
        } as AtRule.FontFace,

        fontFamily: 'default',
        lineHeight: 'tight',
        fontWeight: 'regular',
        color: 'ui.body.text',
        backgroundColor: 'ui.body.background',

        '*': {
            outline: 'none',
            boxSizing: 'border-box',
            margin: 0,
            padding: 0,
        },

        'button, input, optgroup, select, textarea': {
            fontFamily: 'default',
            lineHeight: 'tight',
        },

        'button, input': {
            overflow: 'visible',
        },

        'b, strong': {
            fontWeight: 'medium',
        },

        a: {
            textDecoration: 'inherit',
            color: 'inherit',

            '&:hover': {
                color: 'inherit',
            },
        },
    },
};
