import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {SearchParams} from '../models';
import type {ApiProblem, PaginatedAuditLog} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lists append-only audit entries for the authenticated clinic
 */
export const search = (params?: SearchParams, options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<PaginatedAuditLog>({url: `/api/v1/audit-logs`, method: 'GET', params, signal}, options);
};

export const getSearchQueryKey = (params?: SearchParams) => {
    return [`/api/v1/audit-logs`, ...(params ? [params] : [])] as const;
};

export const getSearchQueryOptions = <TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({signal}) =>
        search(params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof search>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>;
export type SearchQueryError = ErrorType<ApiProblem>;

export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params: undefined | SearchParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof search>>,
                    TError,
                    Awaited<ReturnType<typeof search>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof search>>,
                    TError,
                    Awaited<ReturnType<typeof search>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Lists append-only audit entries for the authenticated clinic
 */

export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getSearchQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getSearchSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof search>>,
    TError = ErrorType<ApiProblem>,
>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({signal}) =>
        search(params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof search>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type SearchSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>;
export type SearchSuspenseQueryError = ErrorType<ApiProblem>;

export function useSearchSuspense<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params: undefined | SearchParams,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchSuspense<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchSuspense<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Lists append-only audit entries for the authenticated clinic
 */

export function useSearchSuspense<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiProblem>>(
    params?: SearchParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getSearchSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getSearchResponseMock = (overrideResponse: Partial<PaginatedAuditLog> = {}): PaginatedAuditLog => ({
    data: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        id: faker.string.alpha({length: {min: 10, max: 20}}),
        clinicId: faker.string.alpha({length: {min: 10, max: 20}}),
        actorUserId: faker.string.alpha({length: {min: 10, max: 20}}),
        actorMemberId: faker.string.alpha({length: {min: 10, max: 20}}),
        resource: faker.string.alpha({length: {min: 10, max: 20}}),
        resourceId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]),
        action: faker.string.alpha({length: {min: 10, max: 20}}),
        result: faker.helpers.arrayElement(['SUCCESS', 'DENIED', 'ERROR'] as const),
        statusCode: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        ip: faker.string.alpha({length: {min: 10, max: 20}}),
        occurredAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    })),
    totalCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    ...overrideResponse,
});

export const getSearchResponseMock200 = (overrideResponse: Partial<PaginatedAuditLog> = {}): PaginatedAuditLog => ({
    data: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        id: faker.string.alpha({length: {min: 10, max: 20}}),
        clinicId: faker.string.alpha({length: {min: 10, max: 20}}),
        actorUserId: faker.string.alpha({length: {min: 10, max: 20}}),
        actorMemberId: faker.string.alpha({length: {min: 10, max: 20}}),
        resource: faker.string.alpha({length: {min: 10, max: 20}}),
        resourceId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]),
        action: faker.string.alpha({length: {min: 10, max: 20}}),
        result: faker.helpers.arrayElement(['SUCCESS', 'DENIED', 'ERROR'] as const),
        statusCode: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        ip: faker.string.alpha({length: {min: 10, max: 20}}),
        occurredAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    })),
    totalCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    ...overrideResponse,
});

export const getSearchResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getSearchMockHandler = (
    overrideResponse?:
        | PaginatedAuditLog
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedAuditLog> | PaginatedAuditLog),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/audit-logs',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSearchResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getSearchMockHandler200 = (
    overrideResponse?:
        | PaginatedAuditLog
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedAuditLog> | PaginatedAuditLog),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/audit-logs',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSearchResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getSearchMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/audit-logs',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSearchResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getAuditLogMock = () => [getSearchMockHandler()];
