import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {CreateClinicDto, CreateInsurancePlanDto, UpdateClinicDto} from '../models';
import type {ApiProblem, Clinic, InsurancePlan} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Creates a new clinic
 */
export const createClinic = (
    createClinicDto: CreateClinicDto,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<Clinic>(
        {
            url: `/api/v1/clinics`,
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            data: createClinicDto,
            signal,
        },
        options
    );
};

export const getCreateClinicMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createClinic>>, TError, {data: CreateClinicDto}, TContext>;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof createClinic>>, TError, {data: CreateClinicDto}, TContext> => {
    const mutationKey = ['createClinic'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof createClinic>>, {data: CreateClinicDto}> = (props) => {
        const {data} = props ?? {};

        return createClinic(data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type CreateClinicMutationResult = NonNullable<Awaited<ReturnType<typeof createClinic>>>;
export type CreateClinicMutationBody = CreateClinicDto;
export type CreateClinicMutationError = ErrorType<ApiProblem>;

/**
 * @summary Creates a new clinic
 */
export const useCreateClinic = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createClinic>>,
            TError,
            {data: CreateClinicDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof createClinic>>, TError, {data: CreateClinicDto}, TContext> => {
    const mutationOptions = getCreateClinicMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get clinic by id
 */
export const getClinic = (clinicId: string, options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<Clinic>({url: `/api/v1/clinics/${clinicId}`, method: 'GET', signal}, options);
};

export const getGetClinicQueryKey = (clinicId?: string) => {
    return [`/api/v1/clinics/${clinicId}`] as const;
};

export const getGetClinicQueryOptions = <TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetClinicQueryKey(clinicId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClinic>>> = ({signal}) =>
        getClinic(clinicId, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!clinicId, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getClinic>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetClinicQueryResult = NonNullable<Awaited<ReturnType<typeof getClinic>>>;
export type GetClinicQueryError = ErrorType<ApiProblem>;

export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getClinic>>,
                    TError,
                    Awaited<ReturnType<typeof getClinic>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getClinic>>,
                    TError,
                    Awaited<ReturnType<typeof getClinic>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get clinic by id
 */

export function useGetClinic<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetClinicQueryOptions(clinicId, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetClinicSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getClinic>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetClinicQueryKey(clinicId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClinic>>> = ({signal}) =>
        getClinic(clinicId, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getClinic>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetClinicSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getClinic>>>;
export type GetClinicSuspenseQueryError = ErrorType<ApiProblem>;

export function useGetClinicSuspense<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetClinicSuspense<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetClinicSuspense<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get clinic by id
 */

export function useGetClinicSuspense<TData = Awaited<ReturnType<typeof getClinic>>, TError = ErrorType<ApiProblem>>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClinic>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetClinicSuspenseQueryOptions(clinicId, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Update a clinic
 */
export const updateClinic = (
    clinicId: string,
    updateClinicDto: UpdateClinicDto,
    options?: SecondParameter<typeof apiClient>
) => {
    return apiClient<Clinic>(
        {
            url: `/api/v1/clinics/${clinicId}`,
            method: 'PATCH',
            headers: {'Content-Type': 'application/json'},
            data: updateClinicDto,
        },
        options
    );
};

export const getUpdateClinicMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateClinic>>,
        TError,
        {clinicId: string; data: UpdateClinicDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateClinic>>,
    TError,
    {clinicId: string; data: UpdateClinicDto},
    TContext
> => {
    const mutationKey = ['updateClinic'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateClinic>>,
        {clinicId: string; data: UpdateClinicDto}
    > = (props) => {
        const {clinicId, data} = props ?? {};

        return updateClinic(clinicId, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type UpdateClinicMutationResult = NonNullable<Awaited<ReturnType<typeof updateClinic>>>;
export type UpdateClinicMutationBody = UpdateClinicDto;
export type UpdateClinicMutationError = ErrorType<ApiProblem>;

/**
 * @summary Update a clinic
 */
export const useUpdateClinic = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateClinic>>,
            TError,
            {clinicId: string; data: UpdateClinicDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updateClinic>>,
    TError,
    {clinicId: string; data: UpdateClinicDto},
    TContext
> => {
    const mutationOptions = getUpdateClinicMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary List insurance plans for a clinic
 */
export const listInsurancePlans = (
    clinicId: string,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<InsurancePlan[]>(
        {url: `/api/v1/clinics/${clinicId}/insurance-plans`, method: 'GET', signal},
        options
    );
};

export const getListInsurancePlansQueryKey = (clinicId?: string) => {
    return [`/api/v1/clinics/${clinicId}/insurance-plans`] as const;
};

export const getListInsurancePlansQueryOptions = <
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListInsurancePlansQueryKey(clinicId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInsurancePlans>>> = ({signal}) =>
        listInsurancePlans(clinicId, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!clinicId, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof listInsurancePlans>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type ListInsurancePlansQueryResult = NonNullable<Awaited<ReturnType<typeof listInsurancePlans>>>;
export type ListInsurancePlansQueryError = ErrorType<ApiProblem>;

export function useListInsurancePlans<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listInsurancePlans>>,
                    TError,
                    Awaited<ReturnType<typeof listInsurancePlans>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListInsurancePlans<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listInsurancePlans>>,
                    TError,
                    Awaited<ReturnType<typeof listInsurancePlans>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListInsurancePlans<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary List insurance plans for a clinic
 */

export function useListInsurancePlans<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getListInsurancePlansQueryOptions(clinicId, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getListInsurancePlansSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListInsurancePlansQueryKey(clinicId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInsurancePlans>>> = ({signal}) =>
        listInsurancePlans(clinicId, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listInsurancePlans>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type ListInsurancePlansSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listInsurancePlans>>>;
export type ListInsurancePlansSuspenseQueryError = ErrorType<ApiProblem>;

export function useListInsurancePlansSuspense<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListInsurancePlansSuspense<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListInsurancePlansSuspense<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary List insurance plans for a clinic
 */

export function useListInsurancePlansSuspense<
    TData = Awaited<ReturnType<typeof listInsurancePlans>>,
    TError = ErrorType<ApiProblem>,
>(
    clinicId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listInsurancePlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getListInsurancePlansSuspenseQueryOptions(clinicId, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Create an insurance plan for a clinic
 */
export const createInsurancePlan = (
    clinicId: string,
    createInsurancePlanDto: CreateInsurancePlanDto,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<InsurancePlan>(
        {
            url: `/api/v1/clinics/${clinicId}/insurance-plans`,
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            data: createInsurancePlanDto,
            signal,
        },
        options
    );
};

export const getCreateInsurancePlanMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createInsurancePlan>>,
        TError,
        {clinicId: string; data: CreateInsurancePlanDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createInsurancePlan>>,
    TError,
    {clinicId: string; data: CreateInsurancePlanDto},
    TContext
> => {
    const mutationKey = ['createInsurancePlan'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createInsurancePlan>>,
        {clinicId: string; data: CreateInsurancePlanDto}
    > = (props) => {
        const {clinicId, data} = props ?? {};

        return createInsurancePlan(clinicId, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type CreateInsurancePlanMutationResult = NonNullable<Awaited<ReturnType<typeof createInsurancePlan>>>;
export type CreateInsurancePlanMutationBody = CreateInsurancePlanDto;
export type CreateInsurancePlanMutationError = ErrorType<ApiProblem>;

/**
 * @summary Create an insurance plan for a clinic
 */
export const useCreateInsurancePlan = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createInsurancePlan>>,
            TError,
            {clinicId: string; data: CreateInsurancePlanDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof createInsurancePlan>>,
    TError,
    {clinicId: string; data: CreateInsurancePlanDto},
    TContext
> => {
    const mutationOptions = getCreateInsurancePlanMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getCreateClinicResponseMock = (overrideResponse: Partial<Clinic> = {}): Clinic => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: {},
    phone: {},
    email: {},
    isPersonalClinic: faker.datatype.boolean(),
    street: {},
    number: {},
    complement: {},
    neighborhood: {},
    city: {},
    state: {},
    zipCode: {},
    country: {},
    logoUrl: {},
    clinicSpecialties: faker.helpers.arrayElements([
        'SAUDE_MENTAL',
        'REABILITACAO',
        'MEDICINA_GERAL',
        'MEDICINA_ESPECIALIZADA',
        'NUTRICAO_DIETETICA',
        'ENFERMAGEM',
        'OUTROS',
    ] as const),
    ...overrideResponse,
});

export const getCreateClinicResponseMock201 = (overrideResponse: Partial<Clinic> = {}): Clinic => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: {},
    phone: {},
    email: {},
    isPersonalClinic: faker.datatype.boolean(),
    street: {},
    number: {},
    complement: {},
    neighborhood: {},
    city: {},
    state: {},
    zipCode: {},
    country: {},
    logoUrl: {},
    clinicSpecialties: faker.helpers.arrayElements([
        'SAUDE_MENTAL',
        'REABILITACAO',
        'MEDICINA_GERAL',
        'MEDICINA_ESPECIALIZADA',
        'NUTRICAO_DIETETICA',
        'ENFERMAGEM',
        'OUTROS',
    ] as const),
    ...overrideResponse,
});

export const getCreateClinicResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetClinicResponseMock = (overrideResponse: Partial<Clinic> = {}): Clinic => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: {},
    phone: {},
    email: {},
    isPersonalClinic: faker.datatype.boolean(),
    street: {},
    number: {},
    complement: {},
    neighborhood: {},
    city: {},
    state: {},
    zipCode: {},
    country: {},
    logoUrl: {},
    clinicSpecialties: faker.helpers.arrayElements([
        'SAUDE_MENTAL',
        'REABILITACAO',
        'MEDICINA_GERAL',
        'MEDICINA_ESPECIALIZADA',
        'NUTRICAO_DIETETICA',
        'ENFERMAGEM',
        'OUTROS',
    ] as const),
    ...overrideResponse,
});

export const getGetClinicResponseMock200 = (overrideResponse: Partial<Clinic> = {}): Clinic => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: {},
    phone: {},
    email: {},
    isPersonalClinic: faker.datatype.boolean(),
    street: {},
    number: {},
    complement: {},
    neighborhood: {},
    city: {},
    state: {},
    zipCode: {},
    country: {},
    logoUrl: {},
    clinicSpecialties: faker.helpers.arrayElements([
        'SAUDE_MENTAL',
        'REABILITACAO',
        'MEDICINA_GERAL',
        'MEDICINA_ESPECIALIZADA',
        'NUTRICAO_DIETETICA',
        'ENFERMAGEM',
        'OUTROS',
    ] as const),
    ...overrideResponse,
});

export const getGetClinicResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getUpdateClinicResponseMock = (overrideResponse: Partial<Clinic> = {}): Clinic => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: {},
    phone: {},
    email: {},
    isPersonalClinic: faker.datatype.boolean(),
    street: {},
    number: {},
    complement: {},
    neighborhood: {},
    city: {},
    state: {},
    zipCode: {},
    country: {},
    logoUrl: {},
    clinicSpecialties: faker.helpers.arrayElements([
        'SAUDE_MENTAL',
        'REABILITACAO',
        'MEDICINA_GERAL',
        'MEDICINA_ESPECIALIZADA',
        'NUTRICAO_DIETETICA',
        'ENFERMAGEM',
        'OUTROS',
    ] as const),
    ...overrideResponse,
});

export const getUpdateClinicResponseMock200 = (overrideResponse: Partial<Clinic> = {}): Clinic => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: {},
    phone: {},
    email: {},
    isPersonalClinic: faker.datatype.boolean(),
    street: {},
    number: {},
    complement: {},
    neighborhood: {},
    city: {},
    state: {},
    zipCode: {},
    country: {},
    logoUrl: {},
    clinicSpecialties: faker.helpers.arrayElements([
        'SAUDE_MENTAL',
        'REABILITACAO',
        'MEDICINA_GERAL',
        'MEDICINA_ESPECIALIZADA',
        'NUTRICAO_DIETETICA',
        'ENFERMAGEM',
        'OUTROS',
    ] as const),
    ...overrideResponse,
});

export const getUpdateClinicResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getListInsurancePlansResponseMock = (): InsurancePlan[] =>
    Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        id: faker.string.uuid(),
        createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        clinicId: faker.string.uuid(),
        name: faker.string.alpha({length: {min: 10, max: 20}}),
        code: {},
        isActive: faker.datatype.boolean(),
    }));

export const getListInsurancePlansResponseMock200 = (): InsurancePlan[] =>
    Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        id: faker.string.uuid(),
        createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        clinicId: faker.string.uuid(),
        name: faker.string.alpha({length: {min: 10, max: 20}}),
        code: {},
        isActive: faker.datatype.boolean(),
    }));

export const getListInsurancePlansResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getCreateInsurancePlanResponseMock = (overrideResponse: Partial<InsurancePlan> = {}): InsurancePlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    code: {},
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getCreateInsurancePlanResponseMock201 = (
    overrideResponse: Partial<InsurancePlan> = {}
): InsurancePlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    code: {},
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getCreateInsurancePlanResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getCreateClinicMockHandler = (
    overrideResponse?: Clinic | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Clinic> | Clinic),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/clinics',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateClinicResponseMock()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateClinicMockHandler201 = (
    overrideResponse?: Clinic | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Clinic> | Clinic),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/clinics',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateClinicResponseMock201()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateClinicMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/clinics',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateClinicResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetClinicMockHandler = (
    overrideResponse?: Clinic | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Clinic> | Clinic),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetClinicResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetClinicMockHandler200 = (
    overrideResponse?: Clinic | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Clinic> | Clinic),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetClinicResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetClinicMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetClinicResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdateClinicMockHandler = (
    overrideResponse?: Clinic | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Clinic> | Clinic),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/clinics/:clinicId',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdateClinicResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdateClinicMockHandler200 = (
    overrideResponse?: Clinic | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Clinic> | Clinic),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/clinics/:clinicId',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdateClinicResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdateClinicMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/clinics/:clinicId',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdateClinicResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getListInsurancePlansMockHandler = (
    overrideResponse?:
        | InsurancePlan[]
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InsurancePlan[]> | InsurancePlan[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/insurance-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListInsurancePlansResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getListInsurancePlansMockHandler200 = (
    overrideResponse?:
        | InsurancePlan[]
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<InsurancePlan[]> | InsurancePlan[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/insurance-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListInsurancePlansResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getListInsurancePlansMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/insurance-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListInsurancePlansResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateInsurancePlanMockHandler = (
    overrideResponse?:
        | InsurancePlan
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<InsurancePlan> | InsurancePlan),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/clinics/:clinicId/insurance-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateInsurancePlanResponseMock()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateInsurancePlanMockHandler201 = (
    overrideResponse?:
        | InsurancePlan
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<InsurancePlan> | InsurancePlan),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/clinics/:clinicId/insurance-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateInsurancePlanResponseMock201()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateInsurancePlanMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/clinics/:clinicId/insurance-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateInsurancePlanResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getClinicMock = () => [
    getCreateClinicMockHandler(),
    getGetClinicMockHandler(),
    getUpdateClinicMockHandler(),
    getListInsurancePlansMockHandler(),
    getCreateInsurancePlanMockHandler(),
];
