import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {GetRevenueReportParams, GetRevenueSummaryParams} from '../models';
import {AppointmentPaymentStatus} from '../models';
import type {ApiProblem, RevenueReport, RevenueSummaryReport} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get revenue report for a clinic
 */
export const getRevenueReport = (
    clinicId: string,
    params: GetRevenueReportParams,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<RevenueReport>(
        {url: `/api/v1/clinics/${clinicId}/financial/report`, method: 'GET', params, signal},
        options
    );
};

export const getGetRevenueReportQueryKey = (clinicId?: string, params?: GetRevenueReportParams) => {
    return [`/api/v1/clinics/${clinicId}/financial/report`, ...(params ? [params] : [])] as const;
};

export const getGetRevenueReportQueryOptions = <
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetRevenueReportQueryKey(clinicId, params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueReport>>> = ({signal}) =>
        getRevenueReport(clinicId, params, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!clinicId, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getRevenueReport>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetRevenueReportQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueReport>>>;
export type GetRevenueReportQueryError = ErrorType<void | ApiProblem>;

export function useGetRevenueReport<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRevenueReport>>,
                    TError,
                    Awaited<ReturnType<typeof getRevenueReport>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueReport<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRevenueReport>>,
                    TError,
                    Awaited<ReturnType<typeof getRevenueReport>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueReport<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get revenue report for a clinic
 */

export function useGetRevenueReport<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetRevenueReportQueryOptions(clinicId, params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetRevenueReportSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetRevenueReportQueryKey(clinicId, params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueReport>>> = ({signal}) =>
        getRevenueReport(clinicId, params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getRevenueReport>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetRevenueReportSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueReport>>>;
export type GetRevenueReportSuspenseQueryError = ErrorType<void | ApiProblem>;

export function useGetRevenueReportSuspense<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueReportSuspense<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueReportSuspense<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get revenue report for a clinic
 */

export function useGetRevenueReportSuspense<
    TData = Awaited<ReturnType<typeof getRevenueReport>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueReportParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueReport>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetRevenueReportSuspenseQueryOptions(clinicId, params, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Get revenue summary for a clinic (dashboard)
 */
export const getRevenueSummary = (
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<RevenueSummaryReport>(
        {url: `/api/v1/clinics/${clinicId}/financial/summary`, method: 'GET', params, signal},
        options
    );
};

export const getGetRevenueSummaryQueryKey = (clinicId?: string, params?: GetRevenueSummaryParams) => {
    return [`/api/v1/clinics/${clinicId}/financial/summary`, ...(params ? [params] : [])] as const;
};

export const getGetRevenueSummaryQueryOptions = <
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetRevenueSummaryQueryKey(clinicId, params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueSummary>>> = ({signal}) =>
        getRevenueSummary(clinicId, params, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!clinicId, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getRevenueSummary>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetRevenueSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueSummary>>>;
export type GetRevenueSummaryQueryError = ErrorType<void | ApiProblem>;

export function useGetRevenueSummary<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRevenueSummary>>,
                    TError,
                    Awaited<ReturnType<typeof getRevenueSummary>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueSummary<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRevenueSummary>>,
                    TError,
                    Awaited<ReturnType<typeof getRevenueSummary>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueSummary<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get revenue summary for a clinic (dashboard)
 */

export function useGetRevenueSummary<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetRevenueSummaryQueryOptions(clinicId, params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetRevenueSummarySuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetRevenueSummaryQueryKey(clinicId, params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevenueSummary>>> = ({signal}) =>
        getRevenueSummary(clinicId, params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getRevenueSummary>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetRevenueSummarySuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getRevenueSummary>>>;
export type GetRevenueSummarySuspenseQueryError = ErrorType<void | ApiProblem>;

export function useGetRevenueSummarySuspense<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueSummarySuspense<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetRevenueSummarySuspense<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get revenue summary for a clinic (dashboard)
 */

export function useGetRevenueSummarySuspense<
    TData = Awaited<ReturnType<typeof getRevenueSummary>>,
    TError = ErrorType<void | ApiProblem>,
>(
    clinicId: string,
    params: GetRevenueSummaryParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getRevenueSummary>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetRevenueSummarySuspenseQueryOptions(clinicId, params, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetRevenueReportResponseMock = (overrideResponse: Partial<RevenueReport> = {}): RevenueReport => ({
    period: {},
    filters: {},
    summary: {
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPaid: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPending: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalExempt: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalRefunded: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        appointmentCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        avgTicketBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    },
    byPaymentMethod: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        method: faker.helpers.arrayElement([
            'CASH',
            'PIX',
            'CREDIT_CARD',
            'DEBIT_CARD',
            'BANK_TRANSFER',
            'INSURANCE',
            'COURTESY',
        ] as const),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    byProfessional: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        memberId: faker.string.uuid(),
        displayName: faker.string.alpha({length: {min: 10, max: 20}}),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    payments: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        paymentId: faker.string.uuid(),
        appointmentId: faker.string.uuid(),
        patientName: faker.string.alpha({length: {min: 10, max: 20}}),
        professionalName: faker.string.alpha({length: {min: 10, max: 20}}),
        appointmentDate: `${faker.date.past().toISOString().split('.')[0]}Z`,
        paymentMethod: faker.helpers.arrayElement([
            'CASH',
            'PIX',
            'CREDIT_CARD',
            'DEBIT_CARD',
            'BANK_TRANSFER',
            'INSURANCE',
            'COURTESY',
        ] as const),
        status: faker.helpers.arrayElement(Object.values(AppointmentPaymentStatus)),
        amountBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        paidAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
        insurancePlanName: {},
    })),
    pagination: {},
    ...overrideResponse,
});

export const getGetRevenueReportResponseMock200 = (overrideResponse: Partial<RevenueReport> = {}): RevenueReport => ({
    period: {},
    filters: {},
    summary: {
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPaid: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPending: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalExempt: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalRefunded: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        appointmentCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        avgTicketBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    },
    byPaymentMethod: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        method: faker.helpers.arrayElement([
            'CASH',
            'PIX',
            'CREDIT_CARD',
            'DEBIT_CARD',
            'BANK_TRANSFER',
            'INSURANCE',
            'COURTESY',
        ] as const),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    byProfessional: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        memberId: faker.string.uuid(),
        displayName: faker.string.alpha({length: {min: 10, max: 20}}),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    payments: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        paymentId: faker.string.uuid(),
        appointmentId: faker.string.uuid(),
        patientName: faker.string.alpha({length: {min: 10, max: 20}}),
        professionalName: faker.string.alpha({length: {min: 10, max: 20}}),
        appointmentDate: `${faker.date.past().toISOString().split('.')[0]}Z`,
        paymentMethod: faker.helpers.arrayElement([
            'CASH',
            'PIX',
            'CREDIT_CARD',
            'DEBIT_CARD',
            'BANK_TRANSFER',
            'INSURANCE',
            'COURTESY',
        ] as const),
        status: faker.helpers.arrayElement(Object.values(AppointmentPaymentStatus)),
        amountBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        paidAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
        insurancePlanName: {},
    })),
    pagination: {},
    ...overrideResponse,
});

export const getGetRevenueReportResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetRevenueSummaryResponseMock = (
    overrideResponse: Partial<RevenueSummaryReport> = {}
): RevenueSummaryReport => ({
    period: {},
    filters: {},
    summary: {
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPaid: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPending: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalExempt: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalRefunded: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        appointmentCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        avgTicketBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    },
    byPaymentMethod: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        method: faker.helpers.arrayElement([
            'CASH',
            'PIX',
            'CREDIT_CARD',
            'DEBIT_CARD',
            'BANK_TRANSFER',
            'INSURANCE',
            'COURTESY',
        ] as const),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    byProfessional: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        memberId: faker.string.uuid(),
        displayName: faker.string.alpha({length: {min: 10, max: 20}}),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    ...overrideResponse,
});

export const getGetRevenueSummaryResponseMock200 = (
    overrideResponse: Partial<RevenueSummaryReport> = {}
): RevenueSummaryReport => ({
    period: {},
    filters: {},
    summary: {
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPaid: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalPending: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalExempt: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalRefunded: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        appointmentCount: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        avgTicketBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    },
    byPaymentMethod: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        method: faker.helpers.arrayElement([
            'CASH',
            'PIX',
            'CREDIT_CARD',
            'DEBIT_CARD',
            'BANK_TRANSFER',
            'INSURANCE',
            'COURTESY',
        ] as const),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    byProfessional: Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        memberId: faker.string.uuid(),
        displayName: faker.string.alpha({length: {min: 10, max: 20}}),
        count: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        totalBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    })),
    ...overrideResponse,
});

export const getGetRevenueSummaryResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetRevenueReportMockHandler = (
    overrideResponse?:
        | RevenueReport
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RevenueReport> | RevenueReport),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/report',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetRevenueReportResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetRevenueReportMockHandler200 = (
    overrideResponse?:
        | RevenueReport
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RevenueReport> | RevenueReport),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/report',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetRevenueReportResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetRevenueReportMockHandler400 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/report',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 400});
        },
        options
    );
};

export const getGetRevenueReportMockHandler404 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/report',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 404});
        },
        options
    );
};

export const getGetRevenueReportMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/report',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetRevenueReportResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetRevenueSummaryMockHandler = (
    overrideResponse?:
        | RevenueSummaryReport
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0]
          ) => Promise<RevenueSummaryReport> | RevenueSummaryReport),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/summary',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetRevenueSummaryResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetRevenueSummaryMockHandler200 = (
    overrideResponse?:
        | RevenueSummaryReport
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0]
          ) => Promise<RevenueSummaryReport> | RevenueSummaryReport),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/summary',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetRevenueSummaryResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetRevenueSummaryMockHandler400 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/summary',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 400});
        },
        options
    );
};

export const getGetRevenueSummaryMockHandler404 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/summary',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 404});
        },
        options
    );
};

export const getGetRevenueSummaryMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/clinics/:clinicId/financial/summary',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetRevenueSummaryResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getFinancialReportMock = () => [getGetRevenueReportMockHandler(), getGetRevenueSummaryMockHandler()];
