import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {CreateFormTemplateVersionInputDto, SearchFormTemplatesParams} from '../models';
import type {ApiProblem, FormTemplate, FormTemplateVersion} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List form templates (filterable by specialty and scope)
 */
export const searchFormTemplates = (
    params: SearchFormTemplatesParams,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<void>({url: `/api/v1/form-templates`, method: 'GET', params, signal}, options);
};

export const getSearchFormTemplatesQueryKey = (params?: SearchFormTemplatesParams) => {
    return [`/api/v1/form-templates`, ...(params ? [params] : [])] as const;
};

export const getSearchFormTemplatesQueryOptions = <
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchFormTemplatesQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchFormTemplates>>> = ({signal}) =>
        searchFormTemplates(params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof searchFormTemplates>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type SearchFormTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof searchFormTemplates>>>;
export type SearchFormTemplatesQueryError = ErrorType<ApiProblem>;

export function useSearchFormTemplates<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchFormTemplates>>,
                    TError,
                    Awaited<ReturnType<typeof searchFormTemplates>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchFormTemplates<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchFormTemplates>>,
                    TError,
                    Awaited<ReturnType<typeof searchFormTemplates>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchFormTemplates<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary List form templates (filterable by specialty and scope)
 */

export function useSearchFormTemplates<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getSearchFormTemplatesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getSearchFormTemplatesSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchFormTemplatesQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchFormTemplates>>> = ({signal}) =>
        searchFormTemplates(params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof searchFormTemplates>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type SearchFormTemplatesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof searchFormTemplates>>>;
export type SearchFormTemplatesSuspenseQueryError = ErrorType<ApiProblem>;

export function useSearchFormTemplatesSuspense<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchFormTemplatesSuspense<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchFormTemplatesSuspense<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary List form templates (filterable by specialty and scope)
 */

export function useSearchFormTemplatesSuspense<
    TData = Awaited<ReturnType<typeof searchFormTemplates>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchFormTemplatesParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchFormTemplates>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getSearchFormTemplatesSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Clone a public template for a professional
 */
export const clone = (templateId: string, options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<FormTemplate>(
        {url: `/api/v1/form-templates/${templateId}/clone`, method: 'POST', signal},
        options
    );
};

export const getCloneMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof clone>>, TError, {templateId: string}, TContext>;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof clone>>, TError, {templateId: string}, TContext> => {
    const mutationKey = ['clone'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof clone>>, {templateId: string}> = (props) => {
        const {templateId} = props ?? {};

        return clone(templateId, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type CloneMutationResult = NonNullable<Awaited<ReturnType<typeof clone>>>;

export type CloneMutationError = ErrorType<ApiProblem>;

/**
 * @summary Clone a public template for a professional
 */
export const useClone = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof clone>>, TError, {templateId: string}, TContext>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof clone>>, TError, {templateId: string}, TContext> => {
    const mutationOptions = getCloneMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary List all versions of a template
 */
export const listVersions = (templateId: string, options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<void>({url: `/api/v1/form-templates/${templateId}/versions`, method: 'GET', signal}, options);
};

export const getListVersionsQueryKey = (templateId?: string) => {
    return [`/api/v1/form-templates/${templateId}/versions`] as const;
};

export const getListVersionsQueryOptions = <
    TData = Awaited<ReturnType<typeof listVersions>>,
    TError = ErrorType<ApiProblem>,
>(
    templateId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListVersionsQueryKey(templateId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVersions>>> = ({signal}) =>
        listVersions(templateId, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!templateId, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof listVersions>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type ListVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof listVersions>>>;
export type ListVersionsQueryError = ErrorType<ApiProblem>;

export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = ErrorType<ApiProblem>>(
    templateId: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listVersions>>,
                    TError,
                    Awaited<ReturnType<typeof listVersions>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = ErrorType<ApiProblem>>(
    templateId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listVersions>>,
                    TError,
                    Awaited<ReturnType<typeof listVersions>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = ErrorType<ApiProblem>>(
    templateId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary List all versions of a template
 */

export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = ErrorType<ApiProblem>>(
    templateId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getListVersionsQueryOptions(templateId, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getListVersionsSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listVersions>>,
    TError = ErrorType<ApiProblem>,
>(
    templateId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListVersionsQueryKey(templateId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVersions>>> = ({signal}) =>
        listVersions(templateId, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listVersions>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type ListVersionsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listVersions>>>;
export type ListVersionsSuspenseQueryError = ErrorType<ApiProblem>;

export function useListVersionsSuspense<
    TData = Awaited<ReturnType<typeof listVersions>>,
    TError = ErrorType<ApiProblem>,
>(
    templateId: string,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListVersionsSuspense<
    TData = Awaited<ReturnType<typeof listVersions>>,
    TError = ErrorType<ApiProblem>,
>(
    templateId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListVersionsSuspense<
    TData = Awaited<ReturnType<typeof listVersions>>,
    TError = ErrorType<ApiProblem>,
>(
    templateId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary List all versions of a template
 */

export function useListVersionsSuspense<
    TData = Awaited<ReturnType<typeof listVersions>>,
    TError = ErrorType<ApiProblem>,
>(
    templateId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getListVersionsSuspenseQueryOptions(templateId, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Create a new version for a template
 */
export const createVersion = (
    templateId: string,
    createFormTemplateVersionInputDto: CreateFormTemplateVersionInputDto,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<FormTemplateVersion>(
        {
            url: `/api/v1/form-templates/${templateId}/versions`,
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            data: createFormTemplateVersionInputDto,
            signal,
        },
        options
    );
};

export const getCreateVersionMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createVersion>>,
        TError,
        {templateId: string; data: CreateFormTemplateVersionInputDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createVersion>>,
    TError,
    {templateId: string; data: CreateFormTemplateVersionInputDto},
    TContext
> => {
    const mutationKey = ['createVersion'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createVersion>>,
        {templateId: string; data: CreateFormTemplateVersionInputDto}
    > = (props) => {
        const {templateId, data} = props ?? {};

        return createVersion(templateId, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type CreateVersionMutationResult = NonNullable<Awaited<ReturnType<typeof createVersion>>>;
export type CreateVersionMutationBody = CreateFormTemplateVersionInputDto;
export type CreateVersionMutationError = ErrorType<ApiProblem>;

/**
 * @summary Create a new version for a template
 */
export const useCreateVersion = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createVersion>>,
            TError,
            {templateId: string; data: CreateFormTemplateVersionInputDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof createVersion>>,
    TError,
    {templateId: string; data: CreateFormTemplateVersionInputDto},
    TContext
> => {
    const mutationOptions = getCreateVersionMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Publish a template version
 */
export const publishVersion = (
    versionId: string,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<FormTemplateVersion>(
        {url: `/api/v1/form-templates/versions/${versionId}/publish`, method: 'POST', signal},
        options
    );
};

export const getPublishVersionMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof publishVersion>>, TError, {versionId: string}, TContext>;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof publishVersion>>, TError, {versionId: string}, TContext> => {
    const mutationKey = ['publishVersion'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishVersion>>, {versionId: string}> = (props) => {
        const {versionId} = props ?? {};

        return publishVersion(versionId, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type PublishVersionMutationResult = NonNullable<Awaited<ReturnType<typeof publishVersion>>>;

export type PublishVersionMutationError = ErrorType<ApiProblem>;

/**
 * @summary Publish a template version
 */
export const usePublishVersion = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof publishVersion>>,
            TError,
            {versionId: string},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof publishVersion>>, TError, {versionId: string}, TContext> => {
    const mutationOptions = getPublishVersionMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Deprecate a template version
 */
export const deprecateVersion = (
    versionId: string,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<FormTemplateVersion>(
        {url: `/api/v1/form-templates/versions/${versionId}/deprecate`, method: 'POST', signal},
        options
    );
};

export const getDeprecateVersionMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deprecateVersion>>, TError, {versionId: string}, TContext>;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof deprecateVersion>>, TError, {versionId: string}, TContext> => {
    const mutationKey = ['deprecateVersion'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof deprecateVersion>>, {versionId: string}> = (props) => {
        const {versionId} = props ?? {};

        return deprecateVersion(versionId, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type DeprecateVersionMutationResult = NonNullable<Awaited<ReturnType<typeof deprecateVersion>>>;

export type DeprecateVersionMutationError = ErrorType<ApiProblem>;

/**
 * @summary Deprecate a template version
 */
export const useDeprecateVersion = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deprecateVersion>>,
            TError,
            {versionId: string},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deprecateVersion>>, TError, {versionId: string}, TContext> => {
    const mutationOptions = getDeprecateVersionMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getSearchFormTemplatesResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getCloneResponseMock = (overrideResponse: Partial<FormTemplate> = {}): FormTemplate => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    code: faker.string.alpha({length: {min: 10, max: 20}}),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    specialty: {},
    isPublic: faker.datatype.boolean(),
    clinicId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    createdByMemberId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    ...overrideResponse,
});

export const getCloneResponseMock201 = (overrideResponse: Partial<FormTemplate> = {}): FormTemplate => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    code: faker.string.alpha({length: {min: 10, max: 20}}),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    specialty: {},
    isPublic: faker.datatype.boolean(),
    clinicId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    createdByMemberId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    ...overrideResponse,
});

export const getCloneResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getListVersionsResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getCreateVersionResponseMock = (
    overrideResponse: Partial<FormTemplateVersion> = {}
): FormTemplateVersion => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    templateId: faker.string.uuid(),
    versionNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    status: faker.helpers.arrayElement(['DRAFT', 'PUBLISHED', 'DEPRECATED'] as const),
    definitionJson: {},
    schemaJson: {},
    publishedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    ...overrideResponse,
});

export const getCreateVersionResponseMock201 = (
    overrideResponse: Partial<FormTemplateVersion> = {}
): FormTemplateVersion => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    templateId: faker.string.uuid(),
    versionNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    status: faker.helpers.arrayElement(['DRAFT', 'PUBLISHED', 'DEPRECATED'] as const),
    definitionJson: {},
    schemaJson: {},
    publishedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    ...overrideResponse,
});

export const getCreateVersionResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getPublishVersionResponseMock = (
    overrideResponse: Partial<FormTemplateVersion> = {}
): FormTemplateVersion => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    templateId: faker.string.uuid(),
    versionNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    status: faker.helpers.arrayElement(['DRAFT', 'PUBLISHED', 'DEPRECATED'] as const),
    definitionJson: {},
    schemaJson: {},
    publishedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    ...overrideResponse,
});

export const getPublishVersionResponseMock200 = (
    overrideResponse: Partial<FormTemplateVersion> = {}
): FormTemplateVersion => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    templateId: faker.string.uuid(),
    versionNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    status: faker.helpers.arrayElement(['DRAFT', 'PUBLISHED', 'DEPRECATED'] as const),
    definitionJson: {},
    schemaJson: {},
    publishedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    ...overrideResponse,
});

export const getPublishVersionResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getDeprecateVersionResponseMock = (
    overrideResponse: Partial<FormTemplateVersion> = {}
): FormTemplateVersion => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    templateId: faker.string.uuid(),
    versionNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    status: faker.helpers.arrayElement(['DRAFT', 'PUBLISHED', 'DEPRECATED'] as const),
    definitionJson: {},
    schemaJson: {},
    publishedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    ...overrideResponse,
});

export const getDeprecateVersionResponseMock200 = (
    overrideResponse: Partial<FormTemplateVersion> = {}
): FormTemplateVersion => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    templateId: faker.string.uuid(),
    versionNumber: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    status: faker.helpers.arrayElement(['DRAFT', 'PUBLISHED', 'DEPRECATED'] as const),
    definitionJson: {},
    schemaJson: {},
    publishedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    ...overrideResponse,
});

export const getDeprecateVersionResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getSearchFormTemplatesMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/form-templates',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getSearchFormTemplatesMockHandler200 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/form-templates',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getSearchFormTemplatesMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/form-templates',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSearchFormTemplatesResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCloneMockHandler = (
    overrideResponse?:
        | FormTemplate
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<FormTemplate> | FormTemplate),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/:templateId/clone',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCloneResponseMock()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCloneMockHandler201 = (
    overrideResponse?:
        | FormTemplate
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<FormTemplate> | FormTemplate),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/:templateId/clone',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCloneResponseMock201()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCloneMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/:templateId/clone',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCloneResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getListVersionsMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/form-templates/:templateId/versions',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getListVersionsMockHandler200 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/form-templates/:templateId/versions',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getListVersionsMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/form-templates/:templateId/versions',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListVersionsResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateVersionMockHandler = (
    overrideResponse?:
        | FormTemplateVersion
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<FormTemplateVersion> | FormTemplateVersion),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/:templateId/versions',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateVersionResponseMock()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateVersionMockHandler201 = (
    overrideResponse?:
        | FormTemplateVersion
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<FormTemplateVersion> | FormTemplateVersion),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/:templateId/versions',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateVersionResponseMock201()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreateVersionMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/:templateId/versions',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreateVersionResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getPublishVersionMockHandler = (
    overrideResponse?:
        | FormTemplateVersion
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<FormTemplateVersion> | FormTemplateVersion),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/versions/:versionId/publish',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPublishVersionResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getPublishVersionMockHandler200 = (
    overrideResponse?:
        | FormTemplateVersion
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<FormTemplateVersion> | FormTemplateVersion),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/versions/:versionId/publish',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPublishVersionResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getPublishVersionMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/versions/:versionId/publish',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getPublishVersionResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeprecateVersionMockHandler = (
    overrideResponse?:
        | FormTemplateVersion
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<FormTemplateVersion> | FormTemplateVersion),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/versions/:versionId/deprecate',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeprecateVersionResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeprecateVersionMockHandler200 = (
    overrideResponse?:
        | FormTemplateVersion
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<FormTemplateVersion> | FormTemplateVersion),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/versions/:versionId/deprecate',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeprecateVersionResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeprecateVersionMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/form-templates/versions/:versionId/deprecate',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeprecateVersionResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getFormTemplateMock = () => [
    getSearchFormTemplatesMockHandler(),
    getCloneMockHandler(),
    getListVersionsMockHandler(),
    getCreateVersionMockHandler(),
    getPublishVersionMockHandler(),
    getDeprecateVersionMockHandler(),
];
