import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {ApiProblem} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get structured AI context payload for a patient
 */
export const getAiContext = (patientId: string, options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<void>({url: `/api/v1/patients/${patientId}/ai-context`, method: 'GET', signal}, options);
};

export const getGetAiContextQueryKey = (patientId?: string) => {
    return [`/api/v1/patients/${patientId}/ai-context`] as const;
};

export const getGetAiContextQueryOptions = <
    TData = Awaited<ReturnType<typeof getAiContext>>,
    TError = ErrorType<ApiProblem>,
>(
    patientId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAiContextQueryKey(patientId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiContext>>> = ({signal}) =>
        getAiContext(patientId, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!patientId, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getAiContext>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAiContextQueryResult = NonNullable<Awaited<ReturnType<typeof getAiContext>>>;
export type GetAiContextQueryError = ErrorType<ApiProblem>;

export function useGetAiContext<TData = Awaited<ReturnType<typeof getAiContext>>, TError = ErrorType<ApiProblem>>(
    patientId: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAiContext>>,
                    TError,
                    Awaited<ReturnType<typeof getAiContext>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetAiContext<TData = Awaited<ReturnType<typeof getAiContext>>, TError = ErrorType<ApiProblem>>(
    patientId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAiContext>>,
                    TError,
                    Awaited<ReturnType<typeof getAiContext>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetAiContext<TData = Awaited<ReturnType<typeof getAiContext>>, TError = ErrorType<ApiProblem>>(
    patientId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get structured AI context payload for a patient
 */

export function useGetAiContext<TData = Awaited<ReturnType<typeof getAiContext>>, TError = ErrorType<ApiProblem>>(
    patientId: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetAiContextQueryOptions(patientId, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetAiContextSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getAiContext>>,
    TError = ErrorType<ApiProblem>,
>(
    patientId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAiContextQueryKey(patientId);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiContext>>> = ({signal}) =>
        getAiContext(patientId, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAiContext>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetAiContextSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getAiContext>>>;
export type GetAiContextSuspenseQueryError = ErrorType<ApiProblem>;

export function useGetAiContextSuspense<
    TData = Awaited<ReturnType<typeof getAiContext>>,
    TError = ErrorType<ApiProblem>,
>(
    patientId: string,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetAiContextSuspense<
    TData = Awaited<ReturnType<typeof getAiContext>>,
    TError = ErrorType<ApiProblem>,
>(
    patientId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetAiContextSuspense<
    TData = Awaited<ReturnType<typeof getAiContext>>,
    TError = ErrorType<ApiProblem>,
>(
    patientId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Get structured AI context payload for a patient
 */

export function useGetAiContextSuspense<
    TData = Awaited<ReturnType<typeof getAiContext>>,
    TError = ErrorType<ApiProblem>,
>(
    patientId: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAiContext>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetAiContextSuspenseQueryOptions(patientId, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetAiContextResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetAiContextMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients/:patientId/ai-context',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getGetAiContextMockHandler200 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients/:patientId/ai-context',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getGetAiContextMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients/:patientId/ai-context',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetAiContextResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getFormAiContextMock = () => [getGetAiContextMockHandler()];
