import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {CreatePatientDto, SearchPatientsParams, UpdatePatientInputDto} from '../models';
import type {ApiProblem, Patient} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Creates a new patient
 */
export const createPatient = (
    createPatientDto: CreatePatientDto,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<Patient>(
        {
            url: `/api/v1/patients`,
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            data: createPatientDto,
            signal,
        },
        options
    );
};

export const getCreatePatientMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createPatient>>,
        TError,
        {data: CreatePatientDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof createPatient>>, TError, {data: CreatePatientDto}, TContext> => {
    const mutationKey = ['createPatient'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPatient>>, {data: CreatePatientDto}> = (
        props
    ) => {
        const {data} = props ?? {};

        return createPatient(data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type CreatePatientMutationResult = NonNullable<Awaited<ReturnType<typeof createPatient>>>;
export type CreatePatientMutationBody = CreatePatientDto;
export type CreatePatientMutationError = ErrorType<ApiProblem>;

/**
 * @summary Creates a new patient
 */
export const useCreatePatient = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createPatient>>,
            TError,
            {data: CreatePatientDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof createPatient>>, TError, {data: CreatePatientDto}, TContext> => {
    const mutationOptions = getCreatePatientMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Lists and searches patients
 */
export const searchPatients = (
    params: SearchPatientsParams,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<void>({url: `/api/v1/patients`, method: 'GET', params, signal}, options);
};

export const getSearchPatientsQueryKey = (params?: SearchPatientsParams) => {
    return [`/api/v1/patients`, ...(params ? [params] : [])] as const;
};

export const getSearchPatientsQueryOptions = <
    TData = Awaited<ReturnType<typeof searchPatients>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchPatientsQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPatients>>> = ({signal}) =>
        searchPatients(params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof searchPatients>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type SearchPatientsQueryResult = NonNullable<Awaited<ReturnType<typeof searchPatients>>>;
export type SearchPatientsQueryError = ErrorType<ApiProblem>;

export function useSearchPatients<TData = Awaited<ReturnType<typeof searchPatients>>, TError = ErrorType<ApiProblem>>(
    params: SearchPatientsParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchPatients>>,
                    TError,
                    Awaited<ReturnType<typeof searchPatients>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchPatients<TData = Awaited<ReturnType<typeof searchPatients>>, TError = ErrorType<ApiProblem>>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchPatients>>,
                    TError,
                    Awaited<ReturnType<typeof searchPatients>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchPatients<TData = Awaited<ReturnType<typeof searchPatients>>, TError = ErrorType<ApiProblem>>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Lists and searches patients
 */

export function useSearchPatients<TData = Awaited<ReturnType<typeof searchPatients>>, TError = ErrorType<ApiProblem>>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getSearchPatientsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getSearchPatientsSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof searchPatients>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchPatientsQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPatients>>> = ({signal}) =>
        searchPatients(params, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof searchPatients>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type SearchPatientsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof searchPatients>>>;
export type SearchPatientsSuspenseQueryError = ErrorType<ApiProblem>;

export function useSearchPatientsSuspense<
    TData = Awaited<ReturnType<typeof searchPatients>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchPatientsParams,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchPatientsSuspense<
    TData = Awaited<ReturnType<typeof searchPatients>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useSearchPatientsSuspense<
    TData = Awaited<ReturnType<typeof searchPatients>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Lists and searches patients
 */

export function useSearchPatientsSuspense<
    TData = Awaited<ReturnType<typeof searchPatients>>,
    TError = ErrorType<ApiProblem>,
>(
    params: SearchPatientsParams,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof searchPatients>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getSearchPatientsSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Gets a patient by ID
 */
export const getPatient = (id: string, options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<Patient>({url: `/api/v1/patients/${id}`, method: 'GET', signal}, options);
};

export const getGetPatientQueryKey = (id?: string) => {
    return [`/api/v1/patients/${id}`] as const;
};

export const getGetPatientQueryOptions = <
    TData = Awaited<ReturnType<typeof getPatient>>,
    TError = ErrorType<ApiProblem>,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetPatientQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPatient>>> = ({signal}) =>
        getPatient(id, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getPatient>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetPatientQueryResult = NonNullable<Awaited<ReturnType<typeof getPatient>>>;
export type GetPatientQueryError = ErrorType<ApiProblem>;

export function useGetPatient<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPatient>>,
                    TError,
                    Awaited<ReturnType<typeof getPatient>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetPatient<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPatient>>,
                    TError,
                    Awaited<ReturnType<typeof getPatient>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetPatient<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Gets a patient by ID
 */

export function useGetPatient<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetPatientQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetPatientSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getPatient>>,
    TError = ErrorType<ApiProblem>,
>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetPatientQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPatient>>> = ({signal}) =>
        getPatient(id, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPatient>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetPatientSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getPatient>>>;
export type GetPatientSuspenseQueryError = ErrorType<ApiProblem>;

export function useGetPatientSuspense<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetPatientSuspense<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetPatientSuspense<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Gets a patient by ID
 */

export function useGetPatientSuspense<TData = Awaited<ReturnType<typeof getPatient>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPatient>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetPatientSuspenseQueryOptions(id, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Updates a patient
 */
export const updatePatient = (
    id: string,
    updatePatientInputDto: UpdatePatientInputDto,
    options?: SecondParameter<typeof apiClient>
) => {
    return apiClient<Patient>(
        {
            url: `/api/v1/patients/${id}`,
            method: 'PUT',
            headers: {'Content-Type': 'application/json'},
            data: updatePatientInputDto,
        },
        options
    );
};

export const getUpdatePatientMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updatePatient>>,
        TError,
        {id: string; data: UpdatePatientInputDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updatePatient>>,
    TError,
    {id: string; data: UpdatePatientInputDto},
    TContext
> => {
    const mutationKey = ['updatePatient'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updatePatient>>,
        {id: string; data: UpdatePatientInputDto}
    > = (props) => {
        const {id, data} = props ?? {};

        return updatePatient(id, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type UpdatePatientMutationResult = NonNullable<Awaited<ReturnType<typeof updatePatient>>>;
export type UpdatePatientMutationBody = UpdatePatientInputDto;
export type UpdatePatientMutationError = ErrorType<ApiProblem>;

/**
 * @summary Updates a patient
 */
export const useUpdatePatient = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updatePatient>>,
            TError,
            {id: string; data: UpdatePatientInputDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updatePatient>>,
    TError,
    {id: string; data: UpdatePatientInputDto},
    TContext
> => {
    const mutationOptions = getUpdatePatientMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Deletes a patient
 */
export const deletePatient = (id: string, options?: SecondParameter<typeof apiClient>) => {
    return apiClient<void>({url: `/api/v1/patients/${id}`, method: 'DELETE'}, options);
};

export const getDeletePatientMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deletePatient>>, TError, {id: string}, TContext>;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof deletePatient>>, TError, {id: string}, TContext> => {
    const mutationKey = ['deletePatient'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePatient>>, {id: string}> = (props) => {
        const {id} = props ?? {};

        return deletePatient(id, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type DeletePatientMutationResult = NonNullable<Awaited<ReturnType<typeof deletePatient>>>;

export type DeletePatientMutationError = ErrorType<ApiProblem>;

/**
 * @summary Deletes a patient
 */
export const useDeletePatient = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof deletePatient>>, TError, {id: string}, TContext>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deletePatient>>, TError, {id: string}, TContext> => {
    const mutationOptions = getDeletePatientMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getCreatePatientResponseMock = (overrideResponse: Partial<Patient> = {}): Patient => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: faker.string.alpha({length: {min: 10, max: 20}}),
    phone: {},
    gender: faker.helpers.arrayElement([faker.helpers.arrayElement(['MALE', 'FEMALE', 'OTHER'] as const), null]),
    personType: faker.helpers.arrayElement(['NATURAL', 'LEGAL'] as const),
    clinicId: faker.string.uuid(),
    birthDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    email: {},
    emergencyContactName: {},
    emergencyContactPhone: {},
    address: {
        ...{street: {}, number: {}, complement: {}, neighborhood: {}, city: {}, state: {}, zipCode: {}, country: {}},
    },
    insurancePlanId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    insuranceCardNumber: {},
    insuranceValidUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    insurancePlan: {
        ...{
            id: faker.string.uuid(),
            name: faker.string.alpha({length: {min: 10, max: 20}}),
            code: {},
            isActive: faker.datatype.boolean(),
        },
    },
    ...overrideResponse,
});

export const getCreatePatientResponseMock201 = (overrideResponse: Partial<Patient> = {}): Patient => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: faker.string.alpha({length: {min: 10, max: 20}}),
    phone: {},
    gender: faker.helpers.arrayElement([faker.helpers.arrayElement(['MALE', 'FEMALE', 'OTHER'] as const), null]),
    personType: faker.helpers.arrayElement(['NATURAL', 'LEGAL'] as const),
    clinicId: faker.string.uuid(),
    birthDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    email: {},
    emergencyContactName: {},
    emergencyContactPhone: {},
    address: {
        ...{street: {}, number: {}, complement: {}, neighborhood: {}, city: {}, state: {}, zipCode: {}, country: {}},
    },
    insurancePlanId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    insuranceCardNumber: {},
    insuranceValidUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    insurancePlan: {
        ...{
            id: faker.string.uuid(),
            name: faker.string.alpha({length: {min: 10, max: 20}}),
            code: {},
            isActive: faker.datatype.boolean(),
        },
    },
    ...overrideResponse,
});

export const getCreatePatientResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getSearchPatientsResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetPatientResponseMock = (overrideResponse: Partial<Patient> = {}): Patient => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: faker.string.alpha({length: {min: 10, max: 20}}),
    phone: {},
    gender: faker.helpers.arrayElement([faker.helpers.arrayElement(['MALE', 'FEMALE', 'OTHER'] as const), null]),
    personType: faker.helpers.arrayElement(['NATURAL', 'LEGAL'] as const),
    clinicId: faker.string.uuid(),
    birthDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    email: {},
    emergencyContactName: {},
    emergencyContactPhone: {},
    address: {
        ...{street: {}, number: {}, complement: {}, neighborhood: {}, city: {}, state: {}, zipCode: {}, country: {}},
    },
    insurancePlanId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    insuranceCardNumber: {},
    insuranceValidUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    insurancePlan: {
        ...{
            id: faker.string.uuid(),
            name: faker.string.alpha({length: {min: 10, max: 20}}),
            code: {},
            isActive: faker.datatype.boolean(),
        },
    },
    ...overrideResponse,
});

export const getGetPatientResponseMock200 = (overrideResponse: Partial<Patient> = {}): Patient => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: faker.string.alpha({length: {min: 10, max: 20}}),
    phone: {},
    gender: faker.helpers.arrayElement([faker.helpers.arrayElement(['MALE', 'FEMALE', 'OTHER'] as const), null]),
    personType: faker.helpers.arrayElement(['NATURAL', 'LEGAL'] as const),
    clinicId: faker.string.uuid(),
    birthDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    email: {},
    emergencyContactName: {},
    emergencyContactPhone: {},
    address: {
        ...{street: {}, number: {}, complement: {}, neighborhood: {}, city: {}, state: {}, zipCode: {}, country: {}},
    },
    insurancePlanId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    insuranceCardNumber: {},
    insuranceValidUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    insurancePlan: {
        ...{
            id: faker.string.uuid(),
            name: faker.string.alpha({length: {min: 10, max: 20}}),
            code: {},
            isActive: faker.datatype.boolean(),
        },
    },
    ...overrideResponse,
});

export const getGetPatientResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getUpdatePatientResponseMock = (overrideResponse: Partial<Patient> = {}): Patient => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: faker.string.alpha({length: {min: 10, max: 20}}),
    phone: {},
    gender: faker.helpers.arrayElement([faker.helpers.arrayElement(['MALE', 'FEMALE', 'OTHER'] as const), null]),
    personType: faker.helpers.arrayElement(['NATURAL', 'LEGAL'] as const),
    clinicId: faker.string.uuid(),
    birthDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    email: {},
    emergencyContactName: {},
    emergencyContactPhone: {},
    address: {
        ...{street: {}, number: {}, complement: {}, neighborhood: {}, city: {}, state: {}, zipCode: {}, country: {}},
    },
    insurancePlanId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    insuranceCardNumber: {},
    insuranceValidUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    insurancePlan: {
        ...{
            id: faker.string.uuid(),
            name: faker.string.alpha({length: {min: 10, max: 20}}),
            code: {},
            isActive: faker.datatype.boolean(),
        },
    },
    ...overrideResponse,
});

export const getUpdatePatientResponseMock200 = (overrideResponse: Partial<Patient> = {}): Patient => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    documentId: faker.string.alpha({length: {min: 10, max: 20}}),
    phone: {},
    gender: faker.helpers.arrayElement([faker.helpers.arrayElement(['MALE', 'FEMALE', 'OTHER'] as const), null]),
    personType: faker.helpers.arrayElement(['NATURAL', 'LEGAL'] as const),
    clinicId: faker.string.uuid(),
    birthDate: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    email: {},
    emergencyContactName: {},
    emergencyContactPhone: {},
    address: {
        ...{street: {}, number: {}, complement: {}, neighborhood: {}, city: {}, state: {}, zipCode: {}, country: {}},
    },
    insurancePlanId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    insuranceCardNumber: {},
    insuranceValidUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, null]),
    insurancePlan: {
        ...{
            id: faker.string.uuid(),
            name: faker.string.alpha({length: {min: 10, max: 20}}),
            code: {},
            isActive: faker.datatype.boolean(),
        },
    },
    ...overrideResponse,
});

export const getUpdatePatientResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getDeletePatientResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getCreatePatientMockHandler = (
    overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Patient> | Patient),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/patients',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreatePatientResponseMock()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreatePatientMockHandler201 = (
    overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Patient> | Patient),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/patients',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreatePatientResponseMock201()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreatePatientMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/patients',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreatePatientResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getSearchPatientsMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getSearchPatientsMockHandler200 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getSearchPatientsMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSearchPatientsResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetPatientMockHandler = (
    overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Patient> | Patient),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetPatientResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetPatientMockHandler200 = (
    overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Patient> | Patient),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetPatientResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetPatientMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patients/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetPatientResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdatePatientMockHandler = (
    overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Patient> | Patient),
    options?: RequestHandlerOptions
) => {
    return http.put(
        '*/api/v1/patients/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdatePatientResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdatePatientMockHandler200 = (
    overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Patient> | Patient),
    options?: RequestHandlerOptions
) => {
    return http.put(
        '*/api/v1/patients/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdatePatientResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdatePatientMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.put(
        '*/api/v1/patients/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdatePatientResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeletePatientMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        '*/api/v1/patients/:id',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getDeletePatientMockHandler200 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        '*/api/v1/patients/:id',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getDeletePatientMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        '*/api/v1/patients/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeletePatientResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getPatientMock = () => [
    getCreatePatientMockHandler(),
    getSearchPatientsMockHandler(),
    getGetPatientMockHandler(),
    getUpdatePatientMockHandler(),
    getDeletePatientMockHandler(),
];
