import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {CreatePatientSubscriptionPlanDto, UpdatePatientSubscriptionPlanInputDto} from '../models';
import type {ApiProblem, PatientSubscriptionPlan} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lists the subscription plan catalog for the current clinic
 */
export const listPlans = (options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<PatientSubscriptionPlan[]>(
        {url: `/api/v1/patient-subscription-plans`, method: 'GET', signal},
        options
    );
};

export const getListPlansQueryKey = () => {
    return [`/api/v1/patient-subscription-plans`] as const;
};

export const getListPlansQueryOptions = <
    TData = Awaited<ReturnType<typeof listPlans>>,
    TError = ErrorType<ApiProblem>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
}) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListPlansQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlans>>> = ({signal}) =>
        listPlans(requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof listPlans>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type ListPlansQueryResult = NonNullable<Awaited<ReturnType<typeof listPlans>>>;
export type ListPlansQueryError = ErrorType<ApiProblem>;

export function useListPlans<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listPlans>>,
                    TError,
                    Awaited<ReturnType<typeof listPlans>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListPlans<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listPlans>>,
                    TError,
                    Awaited<ReturnType<typeof listPlans>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListPlans<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Lists the subscription plan catalog for the current clinic
 */

export function useListPlans<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getListPlansQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getListPlansSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listPlans>>,
    TError = ErrorType<ApiProblem>,
>(options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
}) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListPlansQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlans>>> = ({signal}) =>
        listPlans(requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPlans>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type ListPlansSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listPlans>>>;
export type ListPlansSuspenseQueryError = ErrorType<ApiProblem>;

export function useListPlansSuspense<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListPlansSuspense<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useListPlansSuspense<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Lists the subscription plan catalog for the current clinic
 */

export function useListPlansSuspense<TData = Awaited<ReturnType<typeof listPlans>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listPlans>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getListPlansSuspenseQueryOptions(options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Creates a patient subscription plan in the catalog
 */
export const createPlan = (
    createPatientSubscriptionPlanDto: CreatePatientSubscriptionPlanDto,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<PatientSubscriptionPlan>(
        {
            url: `/api/v1/patient-subscription-plans`,
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            data: createPatientSubscriptionPlanDto,
            signal,
        },
        options
    );
};

export const getCreatePlanMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createPlan>>,
        TError,
        {data: CreatePatientSubscriptionPlanDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createPlan>>,
    TError,
    {data: CreatePatientSubscriptionPlanDto},
    TContext
> => {
    const mutationKey = ['createPlan'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createPlan>>,
        {data: CreatePatientSubscriptionPlanDto}
    > = (props) => {
        const {data} = props ?? {};

        return createPlan(data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type CreatePlanMutationResult = NonNullable<Awaited<ReturnType<typeof createPlan>>>;
export type CreatePlanMutationBody = CreatePatientSubscriptionPlanDto;
export type CreatePlanMutationError = ErrorType<ApiProblem>;

/**
 * @summary Creates a patient subscription plan in the catalog
 */
export const useCreatePlan = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createPlan>>,
            TError,
            {data: CreatePatientSubscriptionPlanDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof createPlan>>,
    TError,
    {data: CreatePatientSubscriptionPlanDto},
    TContext
> => {
    const mutationOptions = getCreatePlanMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Updates a patient subscription plan
 */
export const updatePlan = (
    id: string,
    updatePatientSubscriptionPlanInputDto: UpdatePatientSubscriptionPlanInputDto,
    options?: SecondParameter<typeof apiClient>
) => {
    return apiClient<PatientSubscriptionPlan>(
        {
            url: `/api/v1/patient-subscription-plans/${id}`,
            method: 'PATCH',
            headers: {'Content-Type': 'application/json'},
            data: updatePatientSubscriptionPlanInputDto,
        },
        options
    );
};

export const getUpdatePlanMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updatePlan>>,
        TError,
        {id: string; data: UpdatePatientSubscriptionPlanInputDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updatePlan>>,
    TError,
    {id: string; data: UpdatePatientSubscriptionPlanInputDto},
    TContext
> => {
    const mutationKey = ['updatePlan'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updatePlan>>,
        {id: string; data: UpdatePatientSubscriptionPlanInputDto}
    > = (props) => {
        const {id, data} = props ?? {};

        return updatePlan(id, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type UpdatePlanMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlan>>>;
export type UpdatePlanMutationBody = UpdatePatientSubscriptionPlanInputDto;
export type UpdatePlanMutationError = ErrorType<ApiProblem>;

/**
 * @summary Updates a patient subscription plan
 */
export const useUpdatePlan = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updatePlan>>,
            TError,
            {id: string; data: UpdatePatientSubscriptionPlanInputDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updatePlan>>,
    TError,
    {id: string; data: UpdatePatientSubscriptionPlanInputDto},
    TContext
> => {
    const mutationOptions = getUpdatePlanMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Deactivates a patient subscription plan
 */
export const deactivatePlan = (id: string, options?: SecondParameter<typeof apiClient>) => {
    return apiClient<PatientSubscriptionPlan>(
        {url: `/api/v1/patient-subscription-plans/${id}/deactivate`, method: 'PATCH'},
        options
    );
};

export const getDeactivatePlanMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deactivatePlan>>, TError, {id: string}, TContext>;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof deactivatePlan>>, TError, {id: string}, TContext> => {
    const mutationKey = ['deactivatePlan'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivatePlan>>, {id: string}> = (props) => {
        const {id} = props ?? {};

        return deactivatePlan(id, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type DeactivatePlanMutationResult = NonNullable<Awaited<ReturnType<typeof deactivatePlan>>>;

export type DeactivatePlanMutationError = ErrorType<ApiProblem>;

/**
 * @summary Deactivates a patient subscription plan
 */
export const useDeactivatePlan = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof deactivatePlan>>, TError, {id: string}, TContext>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deactivatePlan>>, TError, {id: string}, TContext> => {
    const mutationOptions = getDeactivatePlanMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getListPlansResponseMock = (): PatientSubscriptionPlan[] =>
    Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        id: faker.string.uuid(),
        createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        clinicId: faker.string.uuid(),
        name: faker.string.alpha({length: {min: 10, max: 20}}),
        description: {},
        monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        isActive: faker.datatype.boolean(),
    }));

export const getListPlansResponseMock200 = (): PatientSubscriptionPlan[] =>
    Array.from({length: faker.number.int({min: 1, max: 10})}, (_, i) => i + 1).map(() => ({
        id: faker.string.uuid(),
        createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
        clinicId: faker.string.uuid(),
        name: faker.string.alpha({length: {min: 10, max: 20}}),
        description: {},
        monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
        isActive: faker.datatype.boolean(),
    }));

export const getListPlansResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getCreatePlanResponseMock = (
    overrideResponse: Partial<PatientSubscriptionPlan> = {}
): PatientSubscriptionPlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getCreatePlanResponseMock201 = (
    overrideResponse: Partial<PatientSubscriptionPlan> = {}
): PatientSubscriptionPlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getCreatePlanResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getUpdatePlanResponseMock = (
    overrideResponse: Partial<PatientSubscriptionPlan> = {}
): PatientSubscriptionPlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getUpdatePlanResponseMock200 = (
    overrideResponse: Partial<PatientSubscriptionPlan> = {}
): PatientSubscriptionPlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getUpdatePlanResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getDeactivatePlanResponseMock = (
    overrideResponse: Partial<PatientSubscriptionPlan> = {}
): PatientSubscriptionPlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getDeactivatePlanResponseMock200 = (
    overrideResponse: Partial<PatientSubscriptionPlan> = {}
): PatientSubscriptionPlan => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicId: faker.string.uuid(),
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    description: {},
    monthlyAppointmentQuota: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    priceBrl: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    isActive: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getDeactivatePlanResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getListPlansMockHandler = (
    overrideResponse?:
        | PatientSubscriptionPlan[]
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0]
          ) => Promise<PatientSubscriptionPlan[]> | PatientSubscriptionPlan[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patient-subscription-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListPlansResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getListPlansMockHandler200 = (
    overrideResponse?:
        | PatientSubscriptionPlan[]
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0]
          ) => Promise<PatientSubscriptionPlan[]> | PatientSubscriptionPlan[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patient-subscription-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListPlansResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getListPlansMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/patient-subscription-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getListPlansResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreatePlanMockHandler = (
    overrideResponse?:
        | PatientSubscriptionPlan
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<PatientSubscriptionPlan> | PatientSubscriptionPlan),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/patient-subscription-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreatePlanResponseMock()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreatePlanMockHandler201 = (
    overrideResponse?:
        | PatientSubscriptionPlan
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<PatientSubscriptionPlan> | PatientSubscriptionPlan),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/patient-subscription-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreatePlanResponseMock201()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getCreatePlanMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/patient-subscription-plans',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getCreatePlanResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdatePlanMockHandler = (
    overrideResponse?:
        | PatientSubscriptionPlan
        | ((
              info: Parameters<Parameters<typeof http.patch>[1]>[0]
          ) => Promise<PatientSubscriptionPlan> | PatientSubscriptionPlan),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/patient-subscription-plans/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdatePlanResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdatePlanMockHandler200 = (
    overrideResponse?:
        | PatientSubscriptionPlan
        | ((
              info: Parameters<Parameters<typeof http.patch>[1]>[0]
          ) => Promise<PatientSubscriptionPlan> | PatientSubscriptionPlan),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/patient-subscription-plans/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdatePlanResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdatePlanMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/patient-subscription-plans/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdatePlanResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeactivatePlanMockHandler = (
    overrideResponse?:
        | PatientSubscriptionPlan
        | ((
              info: Parameters<Parameters<typeof http.patch>[1]>[0]
          ) => Promise<PatientSubscriptionPlan> | PatientSubscriptionPlan),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/patient-subscription-plans/:id/deactivate',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeactivatePlanResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeactivatePlanMockHandler200 = (
    overrideResponse?:
        | PatientSubscriptionPlan
        | ((
              info: Parameters<Parameters<typeof http.patch>[1]>[0]
          ) => Promise<PatientSubscriptionPlan> | PatientSubscriptionPlan),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/patient-subscription-plans/:id/deactivate',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeactivatePlanResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeactivatePlanMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/patient-subscription-plans/:id/deactivate',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeactivatePlanResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getPatientSubscriptionPlanMock = () => [
    getListPlansMockHandler(),
    getCreatePlanMockHandler(),
    getUpdatePlanMockHandler(),
    getDeactivatePlanMockHandler(),
];
