import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useMutation, useQuery, useSuspenseQuery} from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {ChangeUserPasswordDto, DeleteUserInputDto, SignUpUserDto, UpdateUserInputDto} from '../models';
import type {ApiProblem, User} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Signs up a new user
 */
export const signUp = (
    signUpUserDto: SignUpUserDto,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<User>(
        {
            url: `/api/v1/user/sign-up`,
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            data: signUpUserDto,
            signal,
        },
        options
    );
};

export const getSignUpMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError, {data: SignUpUserDto}, TContext>;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError, {data: SignUpUserDto}, TContext> => {
    const mutationKey = ['signUp'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof signUp>>, {data: SignUpUserDto}> = (props) => {
        const {data} = props ?? {};

        return signUp(data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type SignUpMutationResult = NonNullable<Awaited<ReturnType<typeof signUp>>>;
export type SignUpMutationBody = SignUpUserDto;
export type SignUpMutationError = ErrorType<ApiProblem>;

/**
 * @summary Signs up a new user
 */
export const useSignUp = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError, {data: SignUpUserDto}, TContext>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof signUp>>, TError, {data: SignUpUserDto}, TContext> => {
    const mutationOptions = getSignUpMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Gets the current user
 */
export const getCurrentUser = (options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<User>({url: `/api/v1/user/me`, method: 'GET', signal}, options);
};

export const getGetCurrentUserQueryKey = () => {
    return [`/api/v1/user/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
    TData = Awaited<ReturnType<typeof getCurrentUser>>,
    TError = ErrorType<ApiProblem>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
}) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({signal}) =>
        getCurrentUser(requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUser>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
export type GetCurrentUserQueryError = ErrorType<ApiProblem>;

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = ErrorType<ApiProblem>>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCurrentUser>>,
                    TError,
                    Awaited<ReturnType<typeof getCurrentUser>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCurrentUser>>,
                    TError,
                    Awaited<ReturnType<typeof getCurrentUser>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Gets the current user
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = ErrorType<ApiProblem>>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetCurrentUserQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetCurrentUserSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getCurrentUser>>,
    TError = ErrorType<ApiProblem>,
>(options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
    request?: SecondParameter<typeof apiClient>;
}) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({signal}) =>
        getCurrentUser(requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUser>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetCurrentUserSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
export type GetCurrentUserSuspenseQueryError = ErrorType<ApiProblem>;

export function useGetCurrentUserSuspense<
    TData = Awaited<ReturnType<typeof getCurrentUser>>,
    TError = ErrorType<ApiProblem>,
>(
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetCurrentUserSuspense<
    TData = Awaited<ReturnType<typeof getCurrentUser>>,
    TError = ErrorType<ApiProblem>,
>(
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetCurrentUserSuspense<
    TData = Awaited<ReturnType<typeof getCurrentUser>>,
    TError = ErrorType<ApiProblem>,
>(
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Gets the current user
 */

export function useGetCurrentUserSuspense<
    TData = Awaited<ReturnType<typeof getCurrentUser>>,
    TError = ErrorType<ApiProblem>,
>(
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetCurrentUserSuspenseQueryOptions(options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Gets a user
 */
export const getUser = (id: string, options?: SecondParameter<typeof apiClient>, signal?: AbortSignal) => {
    return apiClient<User>({url: `/api/v1/user/${id}`, method: 'GET', signal}, options);
};

export const getGetUserQueryKey = (id?: string) => {
    return [`/api/v1/user/${id}`] as const;
};

export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({signal}) =>
        getUser(id, requestOptions, signal);

    return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getUser>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>;
export type GetUserQueryError = ErrorType<ApiProblem>;

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getUser>>,
                    TError,
                    Awaited<ReturnType<typeof getUser>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getUser>>,
                    TError,
                    Awaited<ReturnType<typeof getUser>>
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Gets a user
 */

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetUserQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetUserSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getUser>>,
    TError = ErrorType<ApiProblem>,
>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    }
) => {
    const {query: queryOptions, request: requestOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({signal}) =>
        getUser(id, requestOptions, signal);

    return {queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUser>>,
        TError,
        TData
    > & {queryKey: DataTag<QueryKey, TData, TError>};
};

export type GetUserSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>;
export type GetUserSuspenseQueryError = ErrorType<ApiProblem>;

export function useGetUserSuspense<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options: {
        query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetUserSuspense<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
export function useGetUserSuspense<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>};
/**
 * @summary Gets a user
 */

export function useGetUserSuspense<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ApiProblem>>(
    id: string,
    options?: {
        query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & {queryKey: DataTag<QueryKey, TData, TError>} {
    const queryOptions = getGetUserSuspenseQueryOptions(id, options);

    const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Updates a user
 */
export const updateUser = (
    id: string,
    updateUserInputDto: UpdateUserInputDto,
    options?: SecondParameter<typeof apiClient>
) => {
    return apiClient<User>(
        {
            url: `/api/v1/user/${id}`,
            method: 'PUT',
            headers: {'Content-Type': 'application/json'},
            data: updateUserInputDto,
        },
        options
    );
};

export const getUpdateUserMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {id: string; data: UpdateUserInputDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    {id: string; data: UpdateUserInputDto},
    TContext
> => {
    const mutationKey = ['updateUser'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateUser>>,
        {id: string; data: UpdateUserInputDto}
    > = (props) => {
        const {id, data} = props ?? {};

        return updateUser(id, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;
export type UpdateUserMutationBody = UpdateUserInputDto;
export type UpdateUserMutationError = ErrorType<ApiProblem>;

/**
 * @summary Updates a user
 */
export const useUpdateUser = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateUser>>,
            TError,
            {id: string; data: UpdateUserInputDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    {id: string; data: UpdateUserInputDto},
    TContext
> => {
    const mutationOptions = getUpdateUserMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Deletes a user
 */
export const deleteUser = (
    id: string,
    deleteUserInputDto: DeleteUserInputDto,
    options?: SecondParameter<typeof apiClient>
) => {
    return apiClient<void>(
        {
            url: `/api/v1/user/${id}`,
            method: 'DELETE',
            headers: {'Content-Type': 'application/json'},
            data: deleteUserInputDto,
        },
        options
    );
};

export const getDeleteUserMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: string; data: DeleteUserInputDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    {id: string; data: DeleteUserInputDto},
    TContext
> => {
    const mutationKey = ['deleteUser'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteUser>>,
        {id: string; data: DeleteUserInputDto}
    > = (props) => {
        const {id, data} = props ?? {};

        return deleteUser(id, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;
export type DeleteUserMutationBody = DeleteUserInputDto;
export type DeleteUserMutationError = ErrorType<ApiProblem>;

/**
 * @summary Deletes a user
 */
export const useDeleteUser = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteUser>>,
            TError,
            {id: string; data: DeleteUserInputDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    {id: string; data: DeleteUserInputDto},
    TContext
> => {
    const mutationOptions = getDeleteUserMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Changes the user password
 */
export const changeUserPassword = (
    changeUserPasswordDto: ChangeUserPasswordDto,
    options?: SecondParameter<typeof apiClient>
) => {
    return apiClient<void>(
        {
            url: `/api/v1/user/change-password`,
            method: 'PATCH',
            headers: {'Content-Type': 'application/json'},
            data: changeUserPasswordDto,
        },
        options
    );
};

export const getChangeUserPasswordMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof changeUserPassword>>,
        TError,
        {data: ChangeUserPasswordDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof changeUserPassword>>,
    TError,
    {data: ChangeUserPasswordDto},
    TContext
> => {
    const mutationKey = ['changeUserPassword'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof changeUserPassword>>,
        {data: ChangeUserPasswordDto}
    > = (props) => {
        const {data} = props ?? {};

        return changeUserPassword(data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type ChangeUserPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changeUserPassword>>>;
export type ChangeUserPasswordMutationBody = ChangeUserPasswordDto;
export type ChangeUserPasswordMutationError = ErrorType<ApiProblem>;

/**
 * @summary Changes the user password
 */
export const useChangeUserPassword = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof changeUserPassword>>,
            TError,
            {data: ChangeUserPasswordDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof changeUserPassword>>,
    TError,
    {data: ChangeUserPasswordDto},
    TContext
> => {
    const mutationOptions = getChangeUserPasswordMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getSignUpResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getSignUpResponseMock201 = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getSignUpResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetCurrentUserResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetCurrentUserResponseMock200 = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetCurrentUserResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetUserResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetUserResponseMock200 = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getGetUserResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getUpdateUserResponseMock = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getUpdateUserResponseMock200 = (overrideResponse: Partial<User> = {}): User => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    username: faker.string.alpha({length: {min: 10, max: 20}}),
    email: {},
    name: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getUpdateUserResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getDeleteUserResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getChangeUserPasswordResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getSignUpMockHandler = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/user/sign-up',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSignUpResponseMock()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getSignUpMockHandler201 = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/user/sign-up',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSignUpResponseMock201()
                ),
                {status: 201, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getSignUpMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/user/sign-up',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getSignUpResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetCurrentUserMockHandler = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/user/me',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetCurrentUserResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetCurrentUserMockHandler200 = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/user/me',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetCurrentUserResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetCurrentUserMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/user/me',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetCurrentUserResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetUserMockHandler = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/user/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetUserResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetUserMockHandler200 = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/user/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetUserResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getGetUserMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/v1/user/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getGetUserResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdateUserMockHandler = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.put(
        '*/api/v1/user/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdateUserResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdateUserMockHandler200 = (
    overrideResponse?: User | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<User> | User),
    options?: RequestHandlerOptions
) => {
    return http.put(
        '*/api/v1/user/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdateUserResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpdateUserMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.put(
        '*/api/v1/user/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpdateUserResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getDeleteUserMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        '*/api/v1/user/:id',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getDeleteUserMockHandler200 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        '*/api/v1/user/:id',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getDeleteUserMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        '*/api/v1/user/:id',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getDeleteUserResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getChangeUserPasswordMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/user/change-password',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getChangeUserPasswordMockHandler200 = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/user/change-password',
        async (info) => {
            if (typeof overrideResponse === 'function') {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options
    );
};

export const getChangeUserPasswordMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.patch(
        '*/api/v1/user/change-password',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getChangeUserPasswordResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUserMock = () => [
    getSignUpMockHandler(),
    getGetCurrentUserMockHandler(),
    getGetUserMockHandler(),
    getUpdateUserMockHandler(),
    getDeleteUserMockHandler(),
    getChangeUserPasswordMockHandler(),
];
