import {faker} from '@faker-js/faker';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import {useMutation} from '@tanstack/react-query';
import type {MutationFunction, QueryClient, UseMutationOptions, UseMutationResult} from '@tanstack/react-query';
import {HttpResponse, http} from 'msw';
import type {RequestHandlerOptions} from 'msw';
import {apiClient} from '../api-client';
import type {ErrorType} from '../api-client';
import type {UpsertWorkingHoursDto} from '../models';
import type {ApiProblem, WorkingHours} from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Creates or updates the working hours for a day
 */
export const upsert = (
    memberId: string,
    upsertWorkingHoursDto: UpsertWorkingHoursDto,
    options?: SecondParameter<typeof apiClient>,
    signal?: AbortSignal
) => {
    return apiClient<WorkingHours>(
        {
            url: `/api/v1/members/${memberId}/working-hours`,
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            data: upsertWorkingHoursDto,
            signal,
        },
        options
    );
};

export const getUpsertMutationOptions = <TError = ErrorType<ApiProblem>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof upsert>>,
        TError,
        {memberId: string; data: UpsertWorkingHoursDto},
        TContext
    >;
    request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof upsert>>,
    TError,
    {memberId: string; data: UpsertWorkingHoursDto},
    TContext
> => {
    const mutationKey = ['upsert'];
    const {mutation: mutationOptions, request: requestOptions} = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, request: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof upsert>>,
        {memberId: string; data: UpsertWorkingHoursDto}
    > = (props) => {
        const {memberId, data} = props ?? {};

        return upsert(memberId, data, requestOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type UpsertMutationResult = NonNullable<Awaited<ReturnType<typeof upsert>>>;
export type UpsertMutationBody = UpsertWorkingHoursDto;
export type UpsertMutationError = ErrorType<ApiProblem>;

/**
 * @summary Creates or updates the working hours for a day
 */
export const useUpsert = <TError = ErrorType<ApiProblem>, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof upsert>>,
            TError,
            {memberId: string; data: UpsertWorkingHoursDto},
            TContext
        >;
        request?: SecondParameter<typeof apiClient>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof upsert>>,
    TError,
    {memberId: string; data: UpsertWorkingHoursDto},
    TContext
> => {
    const mutationOptions = getUpsertMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

export const getUpsertResponseMock = (overrideResponse: Partial<WorkingHours> = {}): WorkingHours => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicMemberId: faker.string.uuid(),
    dayOfWeek: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    startTime: faker.string.alpha({length: {min: 10, max: 20}}),
    endTime: faker.string.alpha({length: {min: 10, max: 20}}),
    slotDuration: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    active: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getUpsertResponseMock200 = (overrideResponse: Partial<WorkingHours> = {}): WorkingHours => ({
    id: faker.string.uuid(),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    clinicMemberId: faker.string.uuid(),
    dayOfWeek: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    startTime: faker.string.alpha({length: {min: 10, max: 20}}),
    endTime: faker.string.alpha({length: {min: 10, max: 20}}),
    slotDuration: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),
    active: faker.datatype.boolean(),
    ...overrideResponse,
});

export const getUpsertResponseMockDefault = (overrideResponse: Partial<ApiProblem> = {}): ApiProblem => ({
    title: faker.string.alpha({length: {min: 10, max: 20}}),
    type: faker.internet.url(),
    detail: faker.string.alpha({length: {min: 10, max: 20}}),
    status: faker.helpers.arrayElement([
        400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423,
        424, 428, 429, 456, 500, 501, 502, 503, 504, 505, 507, 508,
    ] as const),
    instance: faker.string.alpha({length: {min: 10, max: 20}}),
    ...overrideResponse,
});

export const getUpsertMockHandler = (
    overrideResponse?:
        | WorkingHours
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<WorkingHours> | WorkingHours),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/members/:memberId/working-hours',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpsertResponseMock()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpsertMockHandler200 = (
    overrideResponse?:
        | WorkingHours
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<WorkingHours> | WorkingHours),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/members/:memberId/working-hours',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpsertResponseMock200()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getUpsertMockHandlerDefault = (
    overrideResponse?:
        | ApiProblem
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiProblem> | ApiProblem),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/v1/members/:memberId/working-hours',
        async (info) => {
            return new HttpResponse(
                JSON.stringify(
                    overrideResponse !== undefined
                        ? typeof overrideResponse === 'function'
                            ? await overrideResponse(info)
                            : overrideResponse
                        : getUpsertResponseMockDefault()
                ),
                {status: 200, headers: {'Content-Type': 'application/json'}}
            );
        },
        options
    );
};

export const getWorkingHoursMock = () => [getUpsertMockHandler()];
