/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Pesos de prioridade por tipo de contexto
 * @nullable
 */
export type AiAgentProfileContextPriority = {[key: string]: unknown} | null;
