/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Grupo de especialidade de IA
 * @nullable
 */
export type AiAgentProfileSpecialtyGroup =
    | (typeof AiAgentProfileSpecialtyGroup)[keyof typeof AiAgentProfileSpecialtyGroup]
    | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AiAgentProfileSpecialtyGroup = {
    SAUDE_MENTAL: 'SAUDE_MENTAL',
    REABILITACAO: 'REABILITACAO',
    MEDICINA_GERAL: 'MEDICINA_GERAL',
    MEDICINA_ESPECIALIZADA: 'MEDICINA_ESPECIALIZADA',
    NUTRICAO_DIETETICA: 'NUTRICAO_DIETETICA',
    ENFERMAGEM: 'ENFERMAGEM',
    OUTROS: 'OUTROS',
} as const;
