/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {AuditLogResult} from './auditLogResult';

export type AuditLog = {
    id: string;
    clinicId: string;
    actorUserId: string;
    actorMemberId: string;
    resource: string;
    /** @nullable */
    resourceId: string | null;
    action: string;
    result: AuditLogResult;
    statusCode: number;
    ip: string;
    occurredAt: string;
};
