/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type AuditLogResult = (typeof AuditLogResult)[keyof typeof AuditLogResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditLogResult = {
    SUCCESS: 'SUCCESS',
    DENIED: 'DENIED',
    ERROR: 'ERROR',
} as const;
