/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type ChangePaymentPlanDtoPaymentMethod =
    (typeof ChangePaymentPlanDtoPaymentMethod)[keyof typeof ChangePaymentPlanDtoPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangePaymentPlanDtoPaymentMethod = {
    CREDIT_CARD: 'CREDIT_CARD',
    PIX: 'PIX',
    BOLETO: 'BOLETO',
} as const;
