import type {ClinicalDocumentContentJson} from './clinicalDocumentContentJson';
import type {ClinicalDocumentStatus} from './clinicalDocumentStatus';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {ClinicalDocumentType} from './clinicalDocumentType';

export type ClinicalDocument = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    clinicId: string;
    patientId: string;
    createdByMemberId: string;
    responsibleProfessionalId: string;
    type: ClinicalDocumentType;
    /** @nullable */
    templateId?: string | null;
    contentJson: ClinicalDocumentContentJson;
    /** @nullable */
    fileId?: string | null;
    /** @nullable */
    generatedAt?: string | null;
    status: ClinicalDocumentStatus;
    /** @nullable */
    appointmentId?: string | null;
    /** @nullable */
    recordId?: string | null;
};
