/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {ClinicPatientAccessAccessLevel} from './clinicPatientAccessAccessLevel';
import type {ClinicPatientAccessReason} from './clinicPatientAccessReason';

export type ClinicPatientAccess = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    clinicId: string;
    memberId: string;
    patientId: string;
    accessLevel: ClinicPatientAccessAccessLevel;
    /** @nullable */
    reason: ClinicPatientAccessReason;
};
