/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type ClinicalDocumentType = (typeof ClinicalDocumentType)[keyof typeof ClinicalDocumentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClinicalDocumentType = {
    PRESCRIPTION: 'PRESCRIPTION',
    PRESCRIPTION_SPECIAL: 'PRESCRIPTION_SPECIAL',
    MEDICAL_CERTIFICATE: 'MEDICAL_CERTIFICATE',
    REFERRAL: 'REFERRAL',
    EXAM_REQUEST: 'EXAM_REQUEST',
} as const;
