import type {ClinicMemberColor} from './clinicMemberColor';
import type {ClinicMemberDisplayName} from './clinicMemberDisplayName';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {ClinicMemberRole} from './clinicMemberRole';

export type ClinicMember = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    /** Clinic id */
    clinicId: string;
    /** User id */
    userId: string;
    /** Role inside the clinic */
    role: ClinicMemberRole;
    /**
     * Display name (UI label)
     * @nullable
     */
    displayName: ClinicMemberDisplayName;
    /**
     * Calendar color
     * @nullable
     */
    color: ClinicMemberColor;
    /** Is the membership active */
    isActive: boolean;
    /**
     * Inviter member id
     * @nullable
     */
    invitedByMemberId: string | null;
};
