/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import type { ClinicalProfileAllergies } from './clinicalProfileAllergies';
import type { ClinicalProfileChronicConditions } from './clinicalProfileChronicConditions';
import type { ClinicalProfileCurrentMedications } from './clinicalProfileCurrentMedications';
import type { ClinicalProfileSurgicalHistory } from './clinicalProfileSurgicalHistory';
import type { ClinicalProfileFamilyHistory } from './clinicalProfileFamilyHistory';
import type { ClinicalProfileSocialHistory } from './clinicalProfileSocialHistory';
import type { ClinicalProfileGeneralNotes } from './clinicalProfileGeneralNotes';

export interface ClinicalProfile {
  /** The unique identifier of the entity */
  id: string;
  /** The date and time the entity was created */
  createdAt: string;
  /** The date and time the entity was last updated */
  updatedAt: string;
  /** The patient ID */
  patientId: string;
  /** The professional ID */
  professionalId: string;
  /**
   * Known allergies
   * @nullable
   */
  allergies: ClinicalProfileAllergies;
  /**
   * Chronic conditions
   * @nullable
   */
  chronicConditions: ClinicalProfileChronicConditions;
  /**
   * Current medications
   * @nullable
   */
  currentMedications: ClinicalProfileCurrentMedications;
  /**
   * Surgical history
   * @nullable
   */
  surgicalHistory: ClinicalProfileSurgicalHistory;
  /**
   * Family history
   * @nullable
   */
  familyHistory: ClinicalProfileFamilyHistory;
  /**
   * Social history
   * @nullable
   */
  socialHistory: ClinicalProfileSocialHistory;
  /**
   * General notes
   * @nullable
   */
  generalNotes: ClinicalProfileGeneralNotes;
}
