/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import type { ClinicalDocumentType } from './clinicalDocumentType';
import type { ClinicalDocumentTemplateId } from './clinicalDocumentTemplateId';
import type { ClinicalDocumentContentJson } from './clinicalDocumentContentJson';
import type { ClinicalDocumentFileId } from './clinicalDocumentFileId';
import type { ClinicalDocumentGeneratedAt } from './clinicalDocumentGeneratedAt';
import type { ClinicalDocumentStatus } from './clinicalDocumentStatus';
import type { ClinicalDocumentAppointmentId } from './clinicalDocumentAppointmentId';
import type { ClinicalDocumentRecordId } from './clinicalDocumentRecordId';

export interface ClinicalDocument {
  /** The unique identifier of the entity */
  id: string;
  /** The date and time the entity was created */
  createdAt: string;
  /** The date and time the entity was last updated */
  updatedAt: string;
  clinicId: string;
  patientId: string;
  createdByMemberId: string;
  responsibleProfessionalId: string;
  type: ClinicalDocumentType;
  /** @nullable */
  templateId?: ClinicalDocumentTemplateId;
  contentJson: ClinicalDocumentContentJson;
  /** @nullable */
  fileId?: ClinicalDocumentFileId;
  /** @nullable */
  generatedAt?: ClinicalDocumentGeneratedAt;
  status: ClinicalDocumentStatus;
  /** @nullable */
  appointmentId?: ClinicalDocumentAppointmentId;
  /** @nullable */
  recordId?: ClinicalDocumentRecordId;
}
