import type {ClinicCity} from './clinicCity';
import type {ClinicClinicSpecialtiesItem} from './clinicClinicSpecialtiesItem';
import type {ClinicComplement} from './clinicComplement';
import type {ClinicCountry} from './clinicCountry';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {ClinicDocumentId} from './clinicDocumentId';
import type {ClinicEmail} from './clinicEmail';
import type {ClinicLogoUrl} from './clinicLogoUrl';
import type {ClinicNeighborhood} from './clinicNeighborhood';
import type {ClinicNumber} from './clinicNumber';
import type {ClinicPhone} from './clinicPhone';
import type {ClinicState} from './clinicState';
import type {ClinicStreet} from './clinicStreet';
import type {ClinicZipCode} from './clinicZipCode';

export type Clinic = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    /** Clinic name */
    name: string;
    /**
     * CNPJ/CPF
     * @nullable
     */
    documentId: ClinicDocumentId;
    /**
     * Phone
     * @nullable
     */
    phone: ClinicPhone;
    /**
     * Email
     * @nullable
     */
    email: ClinicEmail;
    /** true = autônomo (sem equipe). Front esconde menus de membros. */
    isPersonalClinic: boolean;
    /**
     * Street name
     * @nullable
     */
    street: ClinicStreet;
    /**
     * Street number
     * @nullable
     */
    number: ClinicNumber;
    /**
     * Address complement
     * @nullable
     */
    complement: ClinicComplement;
    /**
     * Neighborhood
     * @nullable
     */
    neighborhood: ClinicNeighborhood;
    /**
     * City
     * @nullable
     */
    city: ClinicCity;
    /**
     * State
     * @nullable
     */
    state: ClinicState;
    /**
     * Zip code
     * @nullable
     */
    zipCode: ClinicZipCode;
    /**
     * Country code
     * @nullable
     */
    country: ClinicCountry;
    /**
     * Logo URL
     * @nullable
     */
    logoUrl: ClinicLogoUrl;
    /** Specialties offered by the clinic */
    clinicSpecialties: ClinicClinicSpecialtiesItem[];
};
