/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type ClinicalDocumentStatus = (typeof ClinicalDocumentStatus)[keyof typeof ClinicalDocumentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClinicalDocumentStatus = {
    DRAFT: 'DRAFT',
    GENERATED: 'GENERATED',
    CANCELLED: 'CANCELLED',
} as const;
