/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {ClinicalProfileAllergies} from './clinicalProfileAllergies';
import type {ClinicalProfileChronicConditions} from './clinicalProfileChronicConditions';
import type {ClinicalProfileCurrentMedications} from './clinicalProfileCurrentMedications';
import type {ClinicalProfileFamilyHistory} from './clinicalProfileFamilyHistory';
import type {ClinicalProfileGeneralNotes} from './clinicalProfileGeneralNotes';
import type {ClinicalProfileSocialHistory} from './clinicalProfileSocialHistory';
import type {ClinicalProfileSurgicalHistory} from './clinicalProfileSurgicalHistory';

export type ClinicalProfile = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    /** The clinic this profile belongs to */
    clinicId: string;
    /** The patient ID */
    patientId: string;
    /** ClinicMember who created/edited the profile */
    createdByMemberId: string;
    /** Professional clinically responsible */
    responsibleProfessionalId: string;
    /**
     * Known allergies
     * @nullable
     */
    allergies: ClinicalProfileAllergies;
    /**
     * Chronic conditions
     * @nullable
     */
    chronicConditions: ClinicalProfileChronicConditions;
    /**
     * Current medications
     * @nullable
     */
    currentMedications: ClinicalProfileCurrentMedications;
    /**
     * Surgical history
     * @nullable
     */
    surgicalHistory: ClinicalProfileSurgicalHistory;
    /**
     * Family history
     * @nullable
     */
    familyHistory: ClinicalProfileFamilyHistory;
    /**
     * Social history
     * @nullable
     */
    socialHistory: ClinicalProfileSocialHistory;
    /**
     * General notes
     * @nullable
     */
    generalNotes: ClinicalProfileGeneralNotes;
};
