/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type CreateRecordDtoTemplateType =
    (typeof CreateRecordDtoTemplateType)[keyof typeof CreateRecordDtoTemplateType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRecordDtoTemplateType = {
    SOAP: 'SOAP',
    DAP: 'DAP',
} as const;
