/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type CreateRecordDtoConductTagsItem =
    (typeof CreateRecordDtoConductTagsItem)[keyof typeof CreateRecordDtoConductTagsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRecordDtoConductTagsItem = {
    GUIDANCE: 'GUIDANCE',
    PRESCRIPTION: 'PRESCRIPTION',
    EXAM_REQUESTED: 'EXAM_REQUESTED',
    REFERRAL: 'REFERRAL',
    FOLLOW_UP_SCHEDULED: 'FOLLOW_UP_SCHEDULED',
    THERAPY_ADJUSTMENT: 'THERAPY_ADJUSTMENT',
} as const;
