/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type CreateClinicMemberDtoRole = (typeof CreateClinicMemberDtoRole)[keyof typeof CreateClinicMemberDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateClinicMemberDtoRole = {
    OWNER: 'OWNER',
    ADMIN: 'ADMIN',
    PROFESSIONAL: 'PROFESSIONAL',
    SECRETARY: 'SECRETARY',
    VIEWER: 'VIEWER',
} as const;
