/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type CreatePatientDtoAddress = {
    /** @nullable */
    street?: string | null;
    /** @nullable */
    number?: string | null;
    /** @nullable */
    complement?: string | null;
    /** @nullable */
    neighborhood?: string | null;
    /** @nullable */
    city?: string | null;
    /** @nullable */
    state?: string | null;
    /** @nullable */
    zipCode?: string | null;
    /** @nullable */
    country?: string | null;
} | null;
