/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {CreateClinicDtoClinicSpecialtiesItem} from './createClinicDtoClinicSpecialtiesItem';

export type CreateClinicDto = {
    /**
     * @minLength 1
     * @maxLength 255
     */
    name: string;
    /** @nullable */
    documentId?: string | null;
    /** @nullable */
    phone?: string | null;
    /** @nullable */
    email?: string | null;
    isPersonalClinic?: boolean;
    /** @nullable */
    street?: string | null;
    /** @nullable */
    number?: string | null;
    /** @nullable */
    complement?: string | null;
    /** @nullable */
    neighborhood?: string | null;
    /** @nullable */
    city?: string | null;
    /** @nullable */
    state?: string | null;
    /** @nullable */
    zipCode?: string | null;
    /** @nullable */
    country?: string | null;
    /** @nullable */
    logoUrl?: string | null;
    clinicSpecialties?: CreateClinicDtoClinicSpecialtiesItem[];
};
