/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type CreateInsurancePlanDto = {
    /**
     * @minLength 1
     * @maxLength 255
     */
    name: string;
    /** @nullable */
    code?: string | null;
};
