/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {DocumentPermissionEntityType} from './documentPermissionEntityType';
import type {DocumentPermissionReason} from './documentPermissionReason';

export type DocumentPermission = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    clinicId: string;
    memberId: string;
    entityType: DocumentPermissionEntityType;
    entityId: string;
    canView: boolean;
    /** @nullable */
    grantedByMemberId: string | null;
    /** @nullable */
    reason: DocumentPermissionReason;
};
