/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import type { DraftEvolutionImportedDocumentId } from './draftEvolutionImportedDocumentId';
import type { DraftEvolutionTemplateType } from './draftEvolutionTemplateType';
import type { DraftEvolutionTitle } from './draftEvolutionTitle';
import type { DraftEvolutionAttendanceType } from './draftEvolutionAttendanceType';
import type { DraftEvolutionClinicalStatus } from './draftEvolutionClinicalStatus';
import type { DraftEvolutionConductTagsItem } from './draftEvolutionConductTagsItem';
import type { DraftEvolutionSubjective } from './draftEvolutionSubjective';
import type { DraftEvolutionObjective } from './draftEvolutionObjective';
import type { DraftEvolutionAssessment } from './draftEvolutionAssessment';
import type { DraftEvolutionPlan } from './draftEvolutionPlan';
import type { DraftEvolutionFreeNotes } from './draftEvolutionFreeNotes';
import type { DraftEvolutionEventDate } from './draftEvolutionEventDate';
import type { DraftEvolutionOverallConfidence } from './draftEvolutionOverallConfidence';
import type { DraftEvolutionStatus } from './draftEvolutionStatus';
import type { DraftEvolutionApprovedByMemberId } from './draftEvolutionApprovedByMemberId';
import type { DraftEvolutionApprovedAt } from './draftEvolutionApprovedAt';
import type { DraftEvolutionRecordId } from './draftEvolutionRecordId';

export interface DraftEvolution {
  /** The unique identifier of the entity */
  id: string;
  /** The date and time the entity was created */
  createdAt: string;
  /** The date and time the entity was last updated */
  updatedAt: string;
  clinicId: string;
  patientId: string;
  createdByMemberId: string;
  /** @nullable */
  importedDocumentId: DraftEvolutionImportedDocumentId;
  /** @nullable */
  templateType: DraftEvolutionTemplateType;
  /** @nullable */
  title: DraftEvolutionTitle;
  /** @nullable */
  attendanceType: DraftEvolutionAttendanceType;
  /** @nullable */
  clinicalStatus: DraftEvolutionClinicalStatus;
  conductTags: DraftEvolutionConductTagsItem[];
  /** @nullable */
  subjective: DraftEvolutionSubjective;
  /** @nullable */
  objective: DraftEvolutionObjective;
  /** @nullable */
  assessment: DraftEvolutionAssessment;
  /** @nullable */
  plan: DraftEvolutionPlan;
  /** @nullable */
  freeNotes: DraftEvolutionFreeNotes;
  /** @nullable */
  eventDate: DraftEvolutionEventDate;
  /**
   * Overall AI confidence score (0.0-1.0)
   * @nullable
   */
  overallConfidence: DraftEvolutionOverallConfidence;
  status: DraftEvolutionStatus;
  /** Whether the professional edited any field before approval */
  wasHumanEdited: boolean;
  /** Whether a human review is required before approval */
  reviewRequired: boolean;
  /** @nullable */
  approvedByMemberId: DraftEvolutionApprovedByMemberId;
  /** @nullable */
  approvedAt: DraftEvolutionApprovedAt;
  /**
   * ID of the Record created upon approval
   * @nullable
   */
  recordId: DraftEvolutionRecordId;
}
