/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type FileDto = {
    id: string;
    fileName: string;
    url: string;
    description: string;
};
