import type {FormTemplateVersionDefinitionJson} from './formTemplateVersionDefinitionJson';
import type {FormTemplateVersionSchemaJson} from './formTemplateVersionSchemaJson';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {FormTemplateVersionStatus} from './formTemplateVersionStatus';

export type FormTemplateVersion = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    /** Template ID */
    templateId: string;
    /** Auto-incremented version number */
    versionNumber: number;
    /** Version lifecycle status */
    status: FormTemplateVersionStatus;
    /** Form field structure (JSON) */
    definitionJson: FormTemplateVersionDefinitionJson;
    /**
     * Optional JSON schema for validation
     * @nullable
     */
    schemaJson: FormTemplateVersionSchemaJson;
    /**
     * When this version was published
     * @nullable
     */
    publishedAt: string | null;
};
