/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Version lifecycle status
 */
export type FormTemplateVersionStatus = (typeof FormTemplateVersionStatus)[keyof typeof FormTemplateVersionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormTemplateVersionStatus = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    DEPRECATED: 'DEPRECATED',
} as const;
