/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import type { FormTemplateVersionStatus } from './formTemplateVersionStatus';
import type { FormTemplateVersionDefinitionJson } from './formTemplateVersionDefinitionJson';
import type { FormTemplateVersionSchemaJson } from './formTemplateVersionSchemaJson';
import type { FormTemplateVersionPublishedAt } from './formTemplateVersionPublishedAt';

export interface FormTemplateVersion {
  /** The unique identifier of the entity */
  id: string;
  /** The date and time the entity was created */
  createdAt: string;
  /** The date and time the entity was last updated */
  updatedAt: string;
  /** Template ID */
  templateId: string;
  /** Auto-incremented version number */
  versionNumber: number;
  /** Version lifecycle status */
  status: FormTemplateVersionStatus;
  /** Form field structure (JSON) */
  definitionJson: FormTemplateVersionDefinitionJson;
  /**
   * Optional JSON schema for validation
   * @nullable
   */
  schemaJson: FormTemplateVersionSchemaJson;
  /**
   * When this version was published
   * @nullable
   */
  publishedAt: FormTemplateVersionPublishedAt;
}
