/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type GetClinicBillingReportParams = {
    /**
     * Year (e.g. 2026)
     */
    year: number;
    /**
     * Month 1-12
     */
    month: number;
};
