/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Internal or TISS code
 * @nullable
 */
export type InsurancePlanCode = {[key: string]: unknown} | null;
