/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {InsurancePlanCode} from './insurancePlanCode';

export type InsurancePlan = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    /** Clinic this plan belongs to */
    clinicId: string;
    /** Plan name */
    name: string;
    /**
     * Internal or TISS code
     * @nullable
     */
    code: InsurancePlanCode;
    /** Whether the plan is active */
    isActive: boolean;
};
