/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type InsuranceClaimClaimStatus = (typeof InsuranceClaimClaimStatus)[keyof typeof InsuranceClaimClaimStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsuranceClaimClaimStatus = {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    PAID: 'PAID',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    DENIED: 'DENIED',
    APPEALED: 'APPEALED',
    CANCELLED: 'CANCELLED',
} as const;
