/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type ListSessionsStatus = (typeof ListSessionsStatus)[keyof typeof ListSessionsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListSessionsStatus = {
    ACTIVE: 'ACTIVE',
    CLOSED: 'CLOSED',
    ARCHIVED: 'ARCHIVED',
} as const;
