/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {CurrentUsage} from './currentUsage';

export type MemberUsageSummary = {
    memberId: string;
    usage: CurrentUsage;
};
