import type {PackagePlanAppointmentType} from './packagePlanAppointmentType';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {PackagePlanDescription} from './packagePlanDescription';
import type {PackagePlanValidityDays} from './packagePlanValidityDays';

export type PackagePlan = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    clinicId: string;
    name: string;
    /** @nullable */
    description: PackagePlanDescription;
    totalCredits: number;
    priceBrl: number;
    /** @nullable */
    validityDays: PackagePlanValidityDays;
    /** @nullable */
    appointmentType: PackagePlanAppointmentType;
    isActive: boolean;
};
