/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * @nullable
 */
export type PackagePlanAppointmentType =
    | (typeof PackagePlanAppointmentType)[keyof typeof PackagePlanAppointmentType]
    | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackagePlanAppointmentType = {
    FIRST_VISIT: 'FIRST_VISIT',
    RETURN: 'RETURN',
    WALK_IN: 'WALK_IN',
    TELEMEDICINE: 'TELEMEDICINE',
    PROCEDURE: 'PROCEDURE',
} as const;
