/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {PatientSubscriptionPlanDescription} from './patientSubscriptionPlanDescription';

export type PatientSubscriptionPlan = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    clinicId: string;
    name: string;
    /** @nullable */
    description: PatientSubscriptionPlanDescription;
    monthlyAppointmentQuota: number;
    priceBrl: number;
    isActive: boolean;
};
