/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type PatientFormStatus = (typeof PatientFormStatus)[keyof typeof PatientFormStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientFormStatus = {
    DRAFT: 'DRAFT',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
} as const;
