/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * The patient phone
 * @nullable
 */
export type PatientPhone = {[key: string]: unknown} | null;
