/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type PatientPackagePaymentMethod =
    (typeof PatientPackagePaymentMethod)[keyof typeof PatientPackagePaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientPackagePaymentMethod = {
    CASH: 'CASH',
    PIX: 'PIX',
    CREDIT_CARD: 'CREDIT_CARD',
    DEBIT_CARD: 'DEBIT_CARD',
    BANK_TRANSFER: 'BANK_TRANSFER',
    INSURANCE: 'INSURANCE',
    COURTESY: 'COURTESY',
    PACKAGE: 'PACKAGE',
    SUBSCRIPTION: 'SUBSCRIPTION',
} as const;
