/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {PatientInsurancePlanDto} from './patientInsurancePlanDto';

/**
 * Insurance plan details
 * @nullable
 */
export type PatientInsurancePlan = PatientInsurancePlanDto | null;
