/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type PatientChatMessageRole = (typeof PatientChatMessageRole)[keyof typeof PatientChatMessageRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientChatMessageRole = {
    USER: 'USER',
    ASSISTANT: 'ASSISTANT',
    SYSTEM: 'SYSTEM',
    INTERNAL: 'INTERNAL',
} as const;
