/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import type { PatientChatSessionAgentProfileId } from './patientChatSessionAgentProfileId';
import type { PatientChatSessionAgentName } from './patientChatSessionAgentName';
import type { PatientChatSessionAgentSlug } from './patientChatSessionAgentSlug';
import type { PatientChatSessionTitle } from './patientChatSessionTitle';
import type { PatientChatSessionStatus } from './patientChatSessionStatus';
import type { PatientChatSessionDeletedAt } from './patientChatSessionDeletedAt';

export interface PatientChatSession {
  /** The unique identifier of the entity */
  id: string;
  /** The date and time the entity was created */
  createdAt: string;
  /** The date and time the entity was last updated */
  updatedAt: string;
  clinicId: string;
  patientId: string;
  /** ClinicMember owner of the session */
  memberId: string;
  /** @nullable */
  agentProfileId: PatientChatSessionAgentProfileId;
  /**
   * Agent name resolved automatically from the member's professional profile. Render as "Active agent: {agentName}".
   * @nullable
   */
  agentName: PatientChatSessionAgentName;
  /**
   * Human-readable agent slug
   * @nullable
   */
  agentSlug: PatientChatSessionAgentSlug;
  /** @nullable */
  title: PatientChatSessionTitle;
  status: PatientChatSessionStatus;
  lastActivityAt: string;
  /** @nullable */
  deletedAt: PatientChatSessionDeletedAt;
}
