/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Summarized clinical timeline
 * @nullable
 */
export type PatientContextSnapshotTimelineSummary = {[key: string]: unknown} | null;
