/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type PrepareUploadInputDto = {
    /** @minLength 1 */
    filename: string;
    /** @minLength 1 */
    mimeType: string;
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    size: number;
    checksum?: string;
};
