/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {ProfessionalRegistrationNumber} from './professionalRegistrationNumber';
import type {ProfessionalSpecialty} from './professionalSpecialty';
import type {ProfessionalSpecialtyNormalized} from './professionalSpecialtyNormalized';

export type Professional = {
    /** The unique identifier of the entity */
    id: string;
    /** The date and time the entity was created */
    createdAt: string;
    /** The date and time the entity was last updated */
    updatedAt: string;
    /** The clinic member that owns this professional record */
    clinicMemberId: string;
    /**
     * Professional registration number (CRM, CRP, etc.)
     * @nullable
     */
    registrationNumber: ProfessionalRegistrationNumber;
    /**
     * Free-form specialty
     * @nullable
     */
    specialty: ProfessionalSpecialty;
    /**
     * Normalized specialty group
     * @nullable
     */
    specialtyNormalized: ProfessionalSpecialtyNormalized;
};
