/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type ProfessionalSubscriptionStatus =
    (typeof ProfessionalSubscriptionStatus)[keyof typeof ProfessionalSubscriptionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessionalSubscriptionStatus = {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    CANCELLED: 'CANCELLED',
    TRIAL: 'TRIAL',
} as const;
