/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {ProfessionalSubscriptionPlanCode} from './professionalSubscriptionPlanCode';
import type {ProfessionalSubscriptionPreviousPlanCode} from './professionalSubscriptionPreviousPlanCode';
import type {ProfessionalSubscriptionStatus} from './professionalSubscriptionStatus';

export type ProfessionalSubscription = {
    id: string;
    memberId: string;
    clinicId: string;
    planCode: ProfessionalSubscriptionPlanCode;
    status: ProfessionalSubscriptionStatus;
    currentPeriodStart: string;
    currentPeriodEnd: string;
    /** @nullable */
    previousPlanCode: ProfessionalSubscriptionPreviousPlanCode;
    /** @nullable */
    planChangedAt: string | null;
    createdAt: string;
    updatedAt: string;
};
