/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type ProfessionalSubscriptionPlanCode =
    (typeof ProfessionalSubscriptionPlanCode)[keyof typeof ProfessionalSubscriptionPlanCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfessionalSubscriptionPlanCode = {
    STARTER: 'STARTER',
    CONSULTORIO: 'CONSULTORIO',
    CLINICA: 'CLINICA',
    ESPECIALISTA: 'ESPECIALISTA',
} as const;
