/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

/**
 * Legacy free-text description
 * @nullable
 */
export type RecordDescription = {[key: string]: unknown} | null;
