/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type RegisterPaymentDtoPaymentMethod =
    (typeof RegisterPaymentDtoPaymentMethod)[keyof typeof RegisterPaymentDtoPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterPaymentDtoPaymentMethod = {
    CASH: 'CASH',
    PIX: 'PIX',
    CREDIT_CARD: 'CREDIT_CARD',
    DEBIT_CARD: 'DEBIT_CARD',
    BANK_TRANSFER: 'BANK_TRANSFER',
    INSURANCE: 'INSURANCE',
    COURTESY: 'COURTESY',
} as const;
