/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchFormTemplatesScope = (typeof SearchFormTemplatesScope)[keyof typeof SearchFormTemplatesScope];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchFormTemplatesScope = {
    public: 'public',
    mine: 'mine',
    all: 'all',
} as const;
