/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchPatientAlertsSortSeverity =
    (typeof SearchPatientAlertsSortSeverity)[keyof typeof SearchPatientAlertsSortSeverity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchPatientAlertsSortSeverity = {
    asc: 'asc',
    desc: 'desc',
} as const;
