/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchFormTemplatesSortCreatedAt =
    (typeof SearchFormTemplatesSortCreatedAt)[keyof typeof SearchFormTemplatesSortCreatedAt];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchFormTemplatesSortCreatedAt = {
    asc: 'asc',
    desc: 'desc',
} as const;
