/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchPatientAlertsSortUpdatedAt =
    (typeof SearchPatientAlertsSortUpdatedAt)[keyof typeof SearchPatientAlertsSortUpdatedAt];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchPatientAlertsSortUpdatedAt = {
    asc: 'asc',
    desc: 'desc',
} as const;
