/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchPatientAlertsSortCreatedAt =
    (typeof SearchPatientAlertsSortCreatedAt)[keyof typeof SearchPatientAlertsSortCreatedAt];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchPatientAlertsSortCreatedAt = {
    asc: 'asc',
    desc: 'desc',
} as const;
