import type {SearchRecordsAttendanceType} from './searchRecordsAttendanceType';
import type {SearchRecordsClinicalStatus} from './searchRecordsClinicalStatus';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {SearchRecordsSortCreatedAt} from './searchRecordsSortCreatedAt';
import type {SearchRecordsSortEventDate} from './searchRecordsSortEventDate';
import type {SearchRecordsSortUpdatedAt} from './searchRecordsSortUpdatedAt';
import type {SearchRecordsSource} from './searchRecordsSource';

export type SearchRecordsParams = {
    /**
     * The cursor to start from
     * @nullable
     */
    cursor: string | null;
    /**
     * The number of items to return
     * @minimum 0
     * @exclusiveMinimum
     */
    limit: number;
    /**
     * The fields to sort by
     * @nullable
     */
    sort: {
        createdAt?: SearchRecordsSortCreatedAt;
        updatedAt?: SearchRecordsSortUpdatedAt;
        eventDate?: SearchRecordsSortEventDate;
    } | null;
    /**
     * Search term to filter records by description
     */
    term: string;
    /**
     * Filter by patient ID
     */
    patientId: string;
    /**
     * Filter by attendance type
     */
    attendanceType: SearchRecordsAttendanceType;
    /**
     * Filter by clinical status
     */
    clinicalStatus: SearchRecordsClinicalStatus;
    /**
     * Filter events from this date (eventDate)
     */
    dateStart: string;
    /**
     * Filter events up to this date (eventDate)
     */
    dateEnd: string;
    /**
     * Filter by record source
     */
    source: SearchRecordsSource;
};
