/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchRecordsSortEventDate = (typeof SearchRecordsSortEventDate)[keyof typeof SearchRecordsSortEventDate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchRecordsSortEventDate = {
    asc: 'asc',
    desc: 'desc',
} as const;
