/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchPatientsSortUpdatedAt =
    (typeof SearchPatientsSortUpdatedAt)[keyof typeof SearchPatientsSortUpdatedAt];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchPatientsSortUpdatedAt = {
    asc: 'asc',
    desc: 'desc',
} as const;
