/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type SearchRecordsSortUpdatedAt = (typeof SearchRecordsSortUpdatedAt)[keyof typeof SearchRecordsSortUpdatedAt];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchRecordsSortUpdatedAt = {
    asc: 'asc',
    desc: 'desc',
} as const;
