import type {UpdateDraftBodyDtoAttendanceType} from './updateDraftBodyDtoAttendanceType';
import type {UpdateDraftBodyDtoClinicalStatus} from './updateDraftBodyDtoClinicalStatus';
import type {UpdateDraftBodyDtoConductTagsItem} from './updateDraftBodyDtoConductTagsItem';
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {UpdateDraftBodyDtoTemplateType} from './updateDraftBodyDtoTemplateType';

export type UpdateDraftBodyDto = {
    templateType: UpdateDraftBodyDtoTemplateType;
    /**
     * @maxLength 255
     * @nullable
     */
    title: string | null;
    attendanceType: UpdateDraftBodyDtoAttendanceType;
    /** @nullable */
    clinicalStatus: UpdateDraftBodyDtoClinicalStatus;
    conductTags: UpdateDraftBodyDtoConductTagsItem[];
    /** @nullable */
    subjective: string | null;
    /** @nullable */
    objective: string | null;
    /** @nullable */
    assessment: string | null;
    /** @nullable */
    plan: string | null;
    /** @nullable */
    freeNotes: string | null;
    /** @nullable */
    eventDate: string | null;
};
