/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */

export type UpdateRecordInputDtoAttendanceType =
    (typeof UpdateRecordInputDtoAttendanceType)[keyof typeof UpdateRecordInputDtoAttendanceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRecordInputDtoAttendanceType = {
    FIRST_VISIT: 'FIRST_VISIT',
    FOLLOW_UP: 'FOLLOW_UP',
    EVALUATION: 'EVALUATION',
    PROCEDURE: 'PROCEDURE',
    TELEMEDICINE: 'TELEMEDICINE',
    INTERCURRENCE: 'INTERCURRENCE',
} as const;
