/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {UpdateProfessionalInputDtoSpecialtyNormalized} from './updateProfessionalInputDtoSpecialtyNormalized';

export type UpdateProfessionalInputDto = {
    /** @nullable */
    registrationNumber: string | null;
    /** @nullable */
    specialty: string | null;
    /** @nullable */
    specialtyNormalized: UpdateProfessionalInputDtoSpecialtyNormalized;
};
