/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {UpdatePatientAlertInputDtoSeverity} from './updatePatientAlertInputDtoSeverity';

export type UpdatePatientAlertInputDto = {
    /**
     * @minLength 1
     * @maxLength 255
     */
    title: string;
    /** @nullable */
    description: string | null;
    severity: UpdatePatientAlertInputDtoSeverity;
    isActive: boolean;
};
