/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Automo API
 * OpenAPI spec version: 0.0.0
 */
import type {UpdateAppointmentInputDtoType} from './updateAppointmentInputDtoType';

export type UpdateAppointmentInputDto = {
    /** A datetime in ISO 8601 format. */
    startAt: string;
    /** A datetime in ISO 8601 format. */
    endAt: string;
    type: UpdateAppointmentInputDtoType;
    /** @nullable */
    note: string | null;
};
