/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automo API
 * The backend API for the Automo project<h3>Authentication</h3>
                For the protected routes, you must first <b>sign up</b> (<code>/user/sign-up</code>) and then <b>sign in</b> (<code>/auth/sign-in</code>).
                After that, you already can request the protected routes.
                The API will return a token that will be included automatically in the cookie and will be sent in subsequent requests for authentication.
                To sign out, simply make a request to the <code>/auth/sign-out</code> endpoint,
                the token will be invalidated and removed from the cookie.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiProblem,
  RejectProposalDto
} from '../../models';

import { apiClient } from '../../api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List pending proposals for the actor's current clinic
 */
export const listPending = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/agent-proposals`, method: 'GET', signal
    },
      options);
    }
  



export const getListPendingQueryKey = () => {
    return [
    `/api/v1/agent-proposals`
    ] as const;
    }

    
export const getListPendingQueryOptions = <TData = Awaited<ReturnType<typeof listPending>>, TError = ApiProblem>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPendingQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPending>>> = ({ signal }) => listPending(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPendingQueryResult = NonNullable<Awaited<ReturnType<typeof listPending>>>
export type ListPendingQueryError = ApiProblem


export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = ApiProblem>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPending>>,
          TError,
          Awaited<ReturnType<typeof listPending>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPending>>,
          TError,
          Awaited<ReturnType<typeof listPending>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List pending proposals for the actor's current clinic
 */

export function useListPending<TData = Awaited<ReturnType<typeof listPending>>, TError = ApiProblem>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPending>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPendingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Confirm a proposal and execute the action
 */
export const confirm = (
    id: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/agent-proposals/${id}/confirm`, method: 'POST', signal
    },
      options);
    }
  


export const getConfirmMutationOptions = <TError = void | ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirm>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof confirm>>, TError,{id: string}, TContext> => {

const mutationKey = ['confirm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirm>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  confirm(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof confirm>>>
    
    export type ConfirmMutationError = void | ApiProblem

    /**
 * @summary Confirm a proposal and execute the action
 */
export const useConfirm = <TError = void | ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirm>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirm>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getConfirmMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reject a proposal
 */
export const reject = (
    id: string,
    rejectProposalDto: RejectProposalDto,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/agent-proposals/${id}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectProposalDto, signal
    },
      options);
    }
  


export const getRejectMutationOptions = <TError = void | ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{id: string;data: RejectProposalDto}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{id: string;data: RejectProposalDto}, TContext> => {

const mutationKey = ['reject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reject>>, {id: string;data: RejectProposalDto}> = (props) => {
          const {id,data} = props ?? {};

          return  reject(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RejectMutationResult = NonNullable<Awaited<ReturnType<typeof reject>>>
    export type RejectMutationBody = RejectProposalDto
    export type RejectMutationError = void | ApiProblem

    /**
 * @summary Reject a proposal
 */
export const useReject = <TError = void | ApiProblem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{id: string;data: RejectProposalDto}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reject>>,
        TError,
        {id: string;data: RejectProposalDto},
        TContext
      > => {

      const mutationOptions = getRejectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    